### ISSUE TITLE
how to handle exposure with pymc3 a.ka. offset parameter

### ISSUE THREAD

**Issue by olivier-lacroix** [pymc-devs/pymc#1789] opened 2017-02-15 03:09 UTC
Hi,

I am considering using pymc3 for a Poisson GLM application, and am looking for a way to take into account an exposure parameter.

In R or statsmodel, this can be indicated via an offset function or parameter, basically indicating that regression parameter shall be 1. see for instance https://stat.ethz.ch/R-manual/R-devel/library/stats/html/offset.html

I have not found a straightforward way to this with pymc3. Have I missed something? Is this doable?

Thank you,

Olivier

**Comment by fonnesbeck** [comment] 2017-02-15 03:17
I'm going to close this because it is not a bug report. The best place for questions is either on our Gitter channel (see our README for the link) or the `pymc` tag on StackOverflow.

The brief answer to your question is that you can easily add offsets as a multiplicative factor to the Poisson parameter (or equivalently, an additive factor on the log scale). For example:

```
theta = tt.log(N) + tt.dot(X, beta)
y_obs = Poisson('y_obs', tt.exp(theta), observed=y)
```

where here `N` is the offset.

**Closed as completed by fonnesbeck** 2017-02-15 03:17 UTC

**Comment by olivier-lacroix** [comment] 2017-02-15 03:22
fair enough. thx for your (very fast) answer
