### ISSUE TITLE
LKJCorr and cholesky problems

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#1922] opened 2017-03-20 04:47 UTC
I'm starting to think that there is still some issues with LKJcorr. I set the `n` parameter to 1000 hoping that it would lead to a identity matrix. Please see the following gist (only part 2).
https://gist.github.com/sachinruk/caebbda2175d68179500213e076fc598

1. It is saying that the covariance matrix is not positive definite. This happens regardless of how small or large `n` is. When I replace `corr_matrix_u` with `T.eye(dim)`, it starts working. However, shouldn't increasing `n` equate to roughly the identity matrix?

2. Is there a way to implement jitChol? It is well know that occasionally the cholesky would fail (I doubt that this is the problem I'm having currently). A workaround is to add a small positive number to the diagonal until it is positive semi definite. Using the cholesky to workout the log determinant  especially (as shown below) can be quite useful I think.

```
# multivariate random walk using cholesky
class mvNormalRandomWalk(Continuous):
    def __init__(self, mu=0., cov=1., *args, **kwargs):
        super(mvNormalRandomWalk, self).__init__(*args, **kwargs)
        self.cov = cov
        self.mu = mu

    def logp(self, x):
        mu = self.mu

        x_im1 = x[:-1]
        x_i = x[1:]
        
        L = sla.cholesky(self.cov)
        log_det = T.log(L.diagonal()).sum()
        delta = x_i - (x_im1+mu)

        solve_lower_triangular = sla.Solve(A_structure='lower_triangular', lower=True)
        Linv_delta = solve_lower_triangular(L,delta.T)
        
        k = L.shape[0]
        innov_like = -(0.5*k*T.log(2*np.pi) + log_det + 0.5*T.sum(Linv_delta*Linv_delta,axis=0))
        return T.sum(innov_like)
```

**Comment by twiecki** [comment] 2017-03-20 09:04
Have you checked https://github.com/pymc-devs/pymc3/pull/1898?

**Comment by sachinruk** [comment] 2017-03-21 07:15
I'm not entirely sure if this is related to that directly to be honest. I changed the cholesky part to just the correlation matrix (so that I can simply multipy with diag(sigmas) later) and this still gave the positive definite error.

Thoughts? Also is that PR near the point of merging with master?

Thanks,
Sachin
```
class mvNormalRandomWalk(Continuous):
    def __init__(self, mu=0., corr=1., sds=1.0, *args, **kwargs):
        super(mvNormalRandomWalk, self).__init__(*args, **kwargs)
        self.corr = corr
        self.sds = sds
        self.mu = mu

    def logp(self, x):
        mu = self.mu

        x_im1 = x[:-1]
        x_i = x[1:]
        
        L = T.diag(self.sds).dot(sla.cholesky(self.corr))
        log_det = T.log(L.diagonal()).sum()
        delta = x_i - (x_im1+mu)

        solve_lower_triangular = sla.Solve(A_structure='lower_triangular', lower=True)
        Linv_delta = solve_lower_triangular(L,delta.T)
        
        k = L.shape[0]
        innov_like = -(0.5*k*T.log(2*np.pi) + log_det + 0.5*T.sum(Linv_delta*Linv_delta,axis=0))
        return T.sum(innov_like)
```

**Comment by aseyboldt** [comment] 2017-03-21 13:56
I think the problem is that pymc3 stops sampling the first time it gets to a matrix that is not positive definite. This is because sla.cholesky throws an error, and pymc3 doesn't catch theano errors (for good reasons I think). You can prevent that by checking first if the matrix is positive definite and if not return -inf (you can do that using `tt.switch`). For an example of how to do that, see `pm.LKJCorr.logp`.

This problem should go away entirely with #1898.

**Comment by aseyboldt** [comment] 2017-03-22 19:43
The cholesky lkj pull request is merged now.

**Comment by sachinruk** [comment] 2017-03-24 04:10
@aseyboldt I tried doing:
```
    try:
            L = tt.slinalg.cholesky(self.cov)
    except:
            return -np.inf
```
but this still gives me the cholesky non positive definite error. I got a feeling that theano doesn't play with `try-except` statements. Would appreciate any help. This would go a long way in helping me with creating a PR for doing the log determinants as well.

With regards to the `tt.switch` statement, this won't deal with exceptions would it. Regardless it would be nice to calculate the cholesky once rather than a few times if I simply check if the matrix is pos definite.

Thanks in advance.

**Comment by twiecki** [comment] 2017-03-24 06:35
Yes, that's not how theano works. This code is only executed once. The code graph is built up and then executed irrespective of this if-else or try-catch. Is there no other way to check if the matrix is pos-def ahead of time?

**Comment by sachinruk** [comment] 2017-03-24 07:13
You can always look at the smallest eigen value and check if this is negative, but that would possibly mean doing a full SVD, which doesn't always guarantee that cholesky would succeed due to numerical problems.

btw in distributions/multivariate.py, you have the following:
```
def posdef(AA):
    try:
        np.linalg.cholesky(AA)
        return 1
    except np.linalg.LinAlgError:
        return 0
```
does this mean that you are switching from theano to numpy at some point?

Also lastly it was quite common in GPs to do jitChol where:
```
def jitChol(Sigma):
    eps = 1e-10
    tries = 0
    while chol_found==False and tries<5:
        try:
            L = np.linalg.cholesky(Sigma)
            chol_found = True
        catch:
            np.fill_diagonal(Sigma, np.diag(Sigma)+eps)
            eps = eps*10
            tries += 1

    if chol_found:
        return L
    else:
        error('Not a positive definite matrix')
```
so would be good to find some sort of work around to 'catch' these errors.

**Comment by aseyboldt** [comment] 2017-03-24 10:11
`posdef` is used in `PosDefMatrix`, which is a new theano Op. It's possible to write a new theano op similar to that, that wraps `jitChol`. But I think I'd prefer an op that returns two values, one flag to report if the cholesky was successful, and the cholesky itself.

**Comment by sachinruk** [comment] 2017-03-27 01:12
So I did the following using theanos ifelse statement (switch still evaluate the cholesky unnecessarily):
```
from pymc3.distributions import Continuous
from theano.ifelse import ifelse
from pymc3.distributions.multivariate import PosDefMatrix

class mvNormalRandomWalk2(Continuous):
    def __init__(self, mu=0., cov=1., *args, **kwargs):
        super(mvNormalRandomWalk2, self).__init__(*args, **kwargs)
        self.cov = cov
        self.mu = mu
        
    def log_normal(self,x):
        x_im1 = x[:-1]
        x_i = x[1:]
        
        L = sla.cholesky(self.cov)
        log_det = T.log(L.diagonal()).sum()
        delta = x_i - (x_im1+self.mu)

        solve_lower_triangular = sla.Solve(A_structure='lower_triangular', lower=True)
        Linv_delta = solve_lower_triangular(L,delta.T)
        
        k = L.shape[0]
        innov_lik = -(0.5*k*T.log(2*np.pi) + log_det + 0.5*T.sum(Linv_delta*Linv_delta,axis=0))
        return T.sum(innov_lik)
        

    def logp(self, x):        
        return ifelse(PosDefMatrix()(self.cov),self.log_normal(x),np.array([-np.inf])[0])
```

fingers crossed I'm getting warmer but its still complaining about not being positive definite. Any thoughts? I'm really new to theano so forgive the ignorance/ pestering.

**Comment by sachinruk** [comment] 2017-03-27 22:45
Also raised this in theano: https://github.com/Theano/Theano/issues/5766#issuecomment-289460217

Your input would be highly appreciated.

**Comment by bwengals** [comment] 2017-03-27 23:44
What about adding a small diagonal regardless?

    L = sla.cholesky(self.cov + 1e-8 * tt.eye(n))

This should be OK if the scale of the elements of `cov` aren't on the same order of magnitude of the fudge factor.

**Comment by sachinruk** [comment] 2017-03-28 00:05
That's a really good idea. Possibly better used on correlation matrix than covariance. I will wait to see what the theano guys get back with. Still prefer the `try-except` block for the sake of my learning experience.

**Comment by aseyboldt** [comment] 2017-03-28 00:06
I still don't understand why you're not using `LKJCholeskyCov`. This would not need any hacks to get around numerical problems. Am I missing part of the problem here?

**Comment by sachinruk** [comment] 2017-03-28 07:16
Few reasons:
1. When pip install the git version `LKJCholeskyCov` is still not there.
2. The `jitChol` method will help me implement the `logp` for general multivariate. This is especially useful for Gaussian processes when the Cholesky is not always able to be computed (due to small eigen values).

But yes you are right that LKJCholeskyCov would solve this specific problem since there is no explicit cholesky decomposition.

**Comment by twiecki** [comment] 2017-03-28 15:09
@aseyboldt Re 1: Perhaps something is wrong with the import?

**Comment by aseyboldt** [comment] 2017-03-28 15:22
No idea, it works for me:
```
In [1]: import pymc3
In [2]: pymc3.LKJCholeskyCov
```

**Comment by aseyboldt** [comment] 2017-03-28 15:23
Oh, it only works in the pymc3 directory. So yes, that looks like a problem with the imports.

**Comment by aseyboldt** [comment] 2017-03-28 15:41
Sorry, I had an old package installed. It works in a fresh environment.

**Comment by twiecki** [comment] 2017-04-07 18:10
@sachinruk Is this solved? I'm closing it but feel free to reopen if the problem persists.

**Closed as completed by twiecki** 2017-04-07 18:10 UTC
