### ISSUE TITLE
Notebook: Getting started with pymc3 (version 3.8) Issue: got an unexpected keyword argument 'dims'

### ISSUE THREAD

**Issue by banshiv** [pymc-devs/pymc#4028] opened 2020-07-23 12:39 UTC
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem
On running notebook 'getting_started_with_pymc3' run into an error

**Please provide the full traceback.**
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-2f38476066b1> in <module>
      2     # The model remembers the datetime index with the name 'date'
      3     change_returns = pm.Data(
----> 4         "returns", returns["change"], dims="date", export_index_as_coords=True
      5     )
      6 

TypeError: __new__() got an unexpected keyword argument 'dims
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.7
* Operating system: Linux
* How did you install PyMC3: (conda/pip) conda install pymc3, conda update pymc3

**Comment by AlexAndorra** [comment] 2020-07-23 13:11
Hi,
Yes it's because the `dims` argument was introduced in 3.9. I suppose you're running the NB present on the master branch? If you run it with 3.9.2, it should work 😉 
Closing as this is expected behavior.

**Closed as completed by AlexAndorra** 2020-07-23 13:11 UTC
