### ISSUE TITLE
how to use pm.traceplot to show a specific parameter

### ISSUE THREAD

**Issue by xialang2012** [pymc-devs/pymc#3587] opened 2019-08-14 03:36 UTC
Hello,
My model like this, 
```
with pm.Model() as basic_model1:

    # Priors for unknown model parameters
    beta = pm.Uniform('beta', lower=uniMin, upper=uniMax, shape=varNum)
    #beta = pm.TruncatedNormal('beta', sigma=10, lower=uniMin, upper=uniMax, shape=varNum)
    sigma = pm.HalfNormal('sigma', sigma=1)

   # Expected value of outcome
    mu, observedYGpp = CallOutFunc(beta)
    #print(mu)

    # Likelihood (sampling distribution) of observations
    Y_obs = pm.Normal('Y_obs', mu=mu, sigma=sigma, observed=observedYGpp)
```
The summary showed

> mean         sd  mc_error    hpd_2.5   hpd_97.5        n_eff       Rhat
> beta__0   0.249684   0.028431  0.000368   0.205333   0.299698  4806.975880   0.999800
> beta__1   1.526045   0.292212  0.004429   1.049262   1.999820  4430.624578   0.999889
> beta__2  31.930996   7.191544  0.123749  20.280235  43.499886  4012.944395   0.999818
> beta__3  75.259162  10.943734  0.159996  57.341661  92.985441  3723.871450   0.999947
> beta__4  52.268268   5.396875  0.094701  43.302025  61.097688  3756.195182   0.999831
> beta__5   0.324796   0.039853  0.000645   0.259021   0.390000  4107.612072   1.000899
> beta__6   0.553403   0.028949  0.000455   0.506692   0.599996  3615.974080   0.999845
> beta__7  19.998619   7.458532  0.114492   7.725570  31.940577  3752.045594   1.000350
> beta__8   0.102020   0.030513  0.000500   0.051829   0.149996  3570.146106   0.999811
> sigma    19.425252  18.630350  1.862747   0.797885  38.663130     1.000374  79.013995

I can use `pm.traceplot(trace, var_names=['beta'])` to draw all the betas, but the screen is too small to show it well. Hence, I would like to know how I can draw one of beta on one picture? e.g. `pm.traceplot(trace, var_names=['beta__0 '])`.  Thanks.

**Comment by fonnesbeck** [comment] 2019-08-14 03:56
Since this is not a bug, I am closing this. Please post questions to discourse.pymc.io.

**Closed as completed by fonnesbeck** 2019-08-14 03:56 UTC
