### ISSUE TITLE
BUG NUTS and HamiltonianMC samplers broken for a simple problem

### ISSUE THREAD

**Issue by beckermr** [pymc-devs/pymc#1428] opened 2016-10-05 19:23 UTC
Hello pymc3 devs! Thanks for all of your help so far! 

Here is a weird thing. I made some simple changes to the model I sent previously, introducing some extra structure in the prior. 

Now the NUTS and HMC samplers are just completely failing. 

BTW, I had to turn up the number of samples taken for emcee to get it to even start to converge for this problem. STAN has no trouble and samples the problem in ~0.5 seconds once the C++ compiles.

The plot:
![mcmc_is_hard](https://cloud.githubusercontent.com/assets/5296416/19127978/ed98e498-8b06-11e6-8147-e44f2f20048f.png)

The code:

``` python
#!/usr/bin/env python
import numpy as np
import matplotlib.pyplot as plt
import seaborn

import pystan
import emcee
import pymc3

def run_emcee(X1, X2, Y):

    def loglike(x):
        """loglike in python"""
        alpha = x[0]
        beta1 = x[1]
        beta2 = x[2]
        sigma = x[3]
        sigma_beta = x[4]

        if sigma <= 0.0 or sigma > 1.0:
            return -np.inf

        if sigma_beta <= 0.0 or sigma_beta > 1.0:
            return -np.inf

        sigma_beta2 = sigma_beta * sigma_beta
        log_sigma_beta = np.log(sigma_beta)

        loglike = 0.0
        loglike += -0.5 * alpha * alpha / 1
        loglike += -0.5 * beta1 * beta1 / sigma_beta2
        loglike -= log_sigma_beta
        loglike += -0.5 * beta2 * beta2 / sigma_beta2
        loglike -= log_sigma_beta
        mu = alpha + beta1 * X1 + beta2 * X2
        loglike += np.sum(-0.5 * ((Y - mu)**2) / sigma / sigma - np.log(sigma))

        return loglike

    ndim = 5
    nwalkers = 80

    p0 = [np.random.rand(ndim) for i in range(nwalkers)]
    sampler = emcee.EnsembleSampler(nwalkers, ndim, loglike)
    sampler.run_mcmc(p0, 10000)

    _chains = sampler.chain[0:4, 5000:, -1]
    chains = []
    for i in range(4):
        chains.append(_chains[i, :])

    return chains

def run_stan(X1, X2, Y):
    stan_code = """
data {
    int<lower=0> num_obs;
    vector[num_obs] y;
    vector[num_obs] x1;
    vector[num_obs] x2;
}

parameters {
    real<lower=-10, upper=10> alpha;
    vector[2] beta;
    real<lower=0.0, upper=1.0> sigma;
    real<lower=0.0, upper=1.0> sigma_beta;
}

transformed parameters {
    vector[num_obs] mu;
    mu = alpha + beta[1] * x1 + beta[2] * x2;
}

model {
    alpha ~ normal(0, 1);
    beta ~ normal(0, sigma_beta);
    y ~ normal(mu, sigma);
}
"""
    model = pystan.StanModel(model_code=stan_code)

    mcmc_data = {'num_obs': len(Y), 'y': Y, 'x1': X1, 'x2': X2}
    base_init = {'alpha': 0.1, 'beta': [0.2, 0.5], 'sigma': 0.3, 'sigma_beta': 0.2}
    init = [base_init] * 4

    fitted = model.sampling(warmup=500,
                            verbose=True,
                            thin=1,
                            init=init,
                            iter=1000,
                            n_jobs=4,
                            data=mcmc_data,
                            chains=4,
                            pars=['alpha', 'beta', 'sigma', 'sigma_beta'],
                            seed=46576)

    return fitted

# Initialize random number generator
np.random.seed(123)

# True parameter values
alpha, sigma = 1, 0.5
beta = [-1, 2.5]
sigma_beta = 0.4

# Size of dataset
size = 100

# Predictor variable
X1 = np.random.randn(size)
X2 = np.random.randn(size) * 0.2

# Simulate outcome variable
Y = alpha + beta[0] * sigma_beta * X1 + beta[1] * sigma_beta * X2 + np.random.randn(size) * sigma

# build pymc3 model
verbose = 2
with pymc3.Model(verbose=verbose) as basic_model:
    # Priors for unknown model parameters
    sigma_beta = pymc3.Uniform('sigma_beta', lower=0.0, upper=1.0)
    alpha = pymc3.Normal('alpha', mu=0, sd=1)
    sigma = pymc3.Uniform('sigma', lower=0.0, upper=1.0)
    beta = pymc3.Normal('beta', mu=0, sd=sigma_beta, shape=2)

    mu = alpha + beta[0] * X1 + beta[1] * X2

    # Likelihood (sampling distribution) of observations
    Y_obs = pymc3.Normal('Y_obs', mu=mu, sd=sigma, observed=Y)


# now sample
chains = []
names = []

pymc3_samplers = [(pymc3.NUTS, 'pymc3 NUTS'),
                  (pymc3.HamiltonianMC, 'pymc3 HamiltonianMC'),
                  (pymc3.Metropolis, 'pymc3 Metropolis'),
                  (pymc3.Slice, 'pymc3 Slice'),]

for stepper, name in pymc3_samplers:
    with basic_model:
        trace = pymc3.sample(1000, njobs=4, progressbar=bool(verbose),
                             step=stepper(basic_model.cont_vars),
                             random_seed=[89, 50, 51, 34])

    chains.append(trace.get_values('sigma_beta', combine=False, burn=500))
    names.append(name)

# run STAN
if True:
    fitted = run_stan(X1, X2, Y)
    sigma_index = fitted.flatnames.index('sigma_beta')
    _schains = fitted.extract('sigma_beta', permuted=False)[:, :, sigma_index]
    schains = []
    for i in range(4):
        schains.append(_schains[:, i])
    chains.append(schains)
    names.append('STAN NUTS')

# run emcee
if True:
    _echains = run_emcee(X1, X2, Y)
    chains.append(_echains)
    names.append('emcee')

# make the plot
fig, axs = plt.subplots(nrows=3, ncols=2, sharex=True, figsize=(10, 10))

axs = axs.ravel()

for ax, chain, name in zip(axs, chains, names):
    try:
        for c in chain:
            seaborn.kdeplot(c, ax=ax, legend=False);
    except:
        for c in chain:
            seaborn.distplot(c, bins=25, kde=False, rug=True, ax=ax);
    ax.set_title(name)

axs[-2].set_xlabel('sigma beta')
axs[-1].set_xlabel('sigma beta')

fig.tight_layout()
plt.show()
```

**Comment by fonnesbeck** [comment] 2016-10-05 22:19
Yes, I can confirm this. Switching to a Beta(1,1) does not improve the outcome, so its not an issue with `Uniform` per se. I wonder if its an interval transform issue.

Changing the sigmas to `HalfNormal` fixes the issue; expanding the range of the uniform prior does not.

**Comment by fonnesbeck** [comment] 2016-10-06 16:35
Adding a `transform=None` to the uniforms allows the sampler to work properly, albeit inefficiently, so it does appear to be an interval transform problem.

**Comment by fonnesbeck** [comment] 2016-10-07 02:45
Our interval transform does not handle the endpoints of the interval correctly. When the endpoints are evaluated by the forward transform, they are infinite:

```
In [48]: interval = pymc3.distributions.transforms.interval(0, 1)

In [49]: interval.forward(np.linspace(0, 1)).tag.test_value
Out[49]: 
array([       -inf, -3.87120101, -3.15700042, -2.73002911, -2.42036813,
       -2.17475172, -1.96944065, -1.79175947, -1.63413053, -1.49165488,
       -1.36097655, -1.23969089, -1.12601126, -1.01856958, -0.91629073,
       -0.81831032, -0.72391884, -0.63252256, -0.54361545, -0.4567584 ,
       -0.37156356, -0.28768207, -0.20479441, -0.12260232, -0.04082199,
        0.04082199,  0.12260232,  0.20479441,  0.28768207,  0.37156356,
        0.4567584 ,  0.54361545,  0.63252256,  0.72391884,  0.81831032,
        0.91629073,  1.01856958,  1.12601126,  1.23969089,  1.36097655,
        1.49165488,  1.63413053,  1.79175947,  1.96944065,  2.17475172,
        2.42036813,  2.73002911,  3.15700042,  3.87120101,         inf])
```

This is not what we want, because the uniform distribution is on the closed interval.

**Comment by beckermr** [comment] 2016-10-07 04:03
Hmmm. Practically, the Jacobian terms that multiply the likelihood would be zero here so that these end point things don't matter for the MCMC chain anyways since the probability that the chain will wander to the ends of the interval should be vanishingly small. 

I wonder how this is handled numerically though by theano. Here are is some output:

``` python
In [11]: val = interval.forward(np.linspace(0+1e-16, 1-1e-16))

In [12]: interval.jacobian_det(val).tag.test_value
Out[12]: 
array([-36.84136149,  -3.91243959,  -3.24034581,  -2.85638691,
        -2.59068375,  -2.39001305,  -2.23068101,  -2.10006083,
        -1.99062699,  -1.89753656,  -1.81749386,  -1.74815916,
        -1.68781603,  -1.6351723 ,  -1.58923521,  -1.54922987,
        -1.51454431,  -1.48469135,  -1.45928163,  -1.43800424,
        -1.42061249,  -1.40691365,  -1.39676128,  -1.39004984,
        -1.38671094,  -1.38671094,  -1.39004984,  -1.39676128,
        -1.40691365,  -1.42061249,  -1.43800424,  -1.45928163,
        -1.48469135,  -1.51454431,  -1.54922987,  -1.58923521,
        -1.6351723 ,  -1.68781603,  -1.74815916,  -1.81749386,
        -1.89753656,  -1.99062699,  -2.10006083,  -2.23068101,
        -2.39001305,  -2.59068375,  -2.85638691,  -3.24034581,
        -3.91243959, -36.04365339])

In [13]: val = interval.forward(np.linspace(0, 1))

In [14]: interval.jacobian_det(val).tag.test_value
Out[14]: 
array([       -inf, -3.91243959, -3.24034581, -2.85638691, -2.59068375,
       -2.39001305, -2.23068101, -2.10006083, -1.99062699, -1.89753656,
       -1.81749386, -1.74815916, -1.68781603, -1.6351723 , -1.58923521,
       -1.54922987, -1.51454431, -1.48469135, -1.45928163, -1.43800424,
       -1.42061249, -1.40691365, -1.39676128, -1.39004984, -1.38671094,
       -1.38671094, -1.39004984, -1.39676128, -1.40691365, -1.42061249,
       -1.43800424, -1.45928163, -1.48469135, -1.51454431, -1.54922987,
       -1.58923521, -1.6351723 , -1.68781603, -1.74815916, -1.81749386,
       -1.89753656, -1.99062699, -2.10006083, -2.23068101, -2.39001305,
       -2.59068375, -2.85638691, -3.24034581, -3.91243959,         nan])
```

The `nan` on the last one worries me a bit. Maybe the log abs det of the Jacobian should be coded by hand instead of autodiff for this transform?

Also, from what I have read online and remember from real analysis, I don't think a continuous transform from a closed interval to the real line exists.

**Comment by fonnesbeck** [comment] 2016-10-07 04:34
If you increase the lower bound of `sigma_beta` even nominally (say to 0.001), the model works fine. The upper bound and both bounds for `sigma` are fine if you make this change. PR #1430 is a first pass at fixing it, but it does not yet do so.

**Comment by fonnesbeck** [comment] 2016-10-07 13:47
I wonder if the problem isnt with the Normal that `sigma_beta` is being passed to. If you substitute another distribution there (e.g. StudentT) NUTS is happy.

**Comment by fonnesbeck** [comment] 2016-10-07 14:19
I can confirm that when the Uniform has a lower bound equal to zero, the `q` returned from `astep` is always an array of zeros, so the chain never moves. Seems like an odd corner case.

**Comment by fonnesbeck** [comment] 2016-10-07 15:17
So, the problem is that NUTS is doing a poor job of assigning itself a scaling. If you pass it the MAP estimate, it does fine:

```
with basic_model:
    start = pymc3.find_MAP()
    trace = pymc3.sample(2000, step=pymc3.NUTS(scaling=start), start=start)
```

![](http://d.pr/i/2xbF/4QODwQ5I+)

Perhaps we can add some better logic for detecting obviously-poor scalings?

**Comment by beckermr** [comment] 2016-10-07 15:18
Hmmm. I tried a bunch of iterations on this but apparently did not happen to get this one!

**Comment by fonnesbeck** [comment] 2016-10-07 15:41
In #1430 I have drastically narrowed the bounds of `adjust_precision` when it is trying to guess a scaling based on the Hessian. I wouldn't think you would usually want a very large (small) value there most of the time, so perhaps this is a better interval to use. It does fix this particular issue.

**Comment by beckermr** [comment] 2016-10-08 15:30
I think this was closed by accident. It would be good to figure out exactly which of the changes in #1430 fix this.

**Comment by fonnesbeck** [comment] 2016-10-08 16:28
Yes I accidentally merged the PR that is designed to close it, which closed this automatically. Will reopen.

**Comment by beckermr** [comment] 2016-10-09 15:21
I did some testing locally on various combinations of the changes in #1430. A few things:
1. No combination I found fixed this for the HamiltonianMC sampler. 
2. The changes to the uniform distribution are not needed. 
3. Just running the example as is, but starting _and_ scaling the chain at the MAP works fine. 
4. With bounding the initial scaling, starting the chain at all zeros is OK too.

So I think two options are palatable for this.
1. Have the sampler call find_MAP and start and scale the chain at the initial point by default. 
2. Put in the changes to bound the scaling.

As a pymc3 user, I would prefer 1 over 2 since chains run with 1 tend to be a lot faster unsurprisingly.

In general, I found it confusing that starting the chain at some did not automatically scale the momentum distribution at that point for the HMC-like samplers. Not sure what to do about that...

**Comment by twiecki** [comment] 2016-10-10 10:42
Yeah, I have contemplated a better sample method that takes care of initialization. Specifically, ADVI initialization for NUTS works really well but few people know about it. Just have to think of API. The current approach is pretty transparent which is good, but does not make reasonable things easy. 

Maybe something like:
`sample_init(5000, 'nuts', init='advi')`?

Why pass in strings? I think for this high-level method we want to handle a few common cases specifically. For example, `nuts` and `advi` would use `advi` to estimate the scaling matrix, something that's not required for metropolis (even though we could use it for the proposal distribution there).

Thoughts? Not sure the name is great.

**Comment by beckermr** [comment] 2016-10-10 13:31
This looks good. I am a fan of keywords for most things. There should be a MAP initialization as well maybe. Like this?

```
sampling_init(5000, step='nuts', init='advi')
sampling_init(5000, step='nuts', init='map')
```

**Comment by fonnesbeck** [comment] 2016-10-18 19:55
For the 3.0 release, I suggest we adopt the changes in #1461 and then we can implement the use of more robust initializations in future versions.

**Comment by beckermr** [comment] 2016-10-18 19:59
I just want to reiterate that the changes to the uniform distribution scaling are not needed.

**Comment by fonnesbeck** [comment] 2016-10-18 20:04
I agree. They still make the the function more robust, so I suggest we adopt them.

**Comment by beckermr** [comment] 2016-10-18 20:05
Robust in what sense? The jacobian of this transformation is zero at the end points anyways so it doesn't actually matter what the function does as long as the Jacobian properly gives -inf when taking the log of it.

**Comment by fonnesbeck** [comment] 2016-10-18 20:14
For example:

```
import numpy as np


def forward1(x, a, b):
    return np.log((x - a) / (b - x))

def forward2(x, a, b, e=1e-6):
    return np.log(np.maximum((x - a) / np.maximum(b - x, e), e))

tiny_val = 1e-30
x = np.array([tiny_val, 1 - tiny_val])

print(forward1(x, 0, 1))
print(forward2(x, 0, 1))
```

yields:

```
[-69.07755279          inf]
[-13.81551056  13.81551056]
```

We don't ever want a nan returned, no matter how small the value is, since they are always going to be tranformed back to the [a,b] interval.

**Comment by beckermr** [comment] 2016-10-19 02:59
This doesn't return nan on my machine. It gives back inf which should be handled correctly by numpy.

**Comment by fonnesbeck** [comment] 2016-10-21 20:36
We need a solution that works on all platforms.

However, I am going to add some warnings for variance parameters that they should not include variables with negative support. This whole problem goes away if an appropriate variable is chosen for sigma.

**Comment by springcoil** [comment] 2016-10-27 18:06
@fonnesbeck is this still something that needs fixed, or are the warnings for variance parameters a sufficient solution?

**Comment by fonnesbeck** [comment] 2016-10-28 12:55
The model presented above now runs under the current master, so I'm going to close this. If there are ideas for a better fix, please submit a PR.

**Closed as completed by fonnesbeck** 2016-10-28 12:55 UTC
