### ISSUE TITLE
Utilise external GP model (or other) as deterministic for model calibration (or should it be DensityDist?)

### ISSUE THREAD

**Issue by adam-rysanek** [pymc-devs/pymc#1574] opened 2016-12-05 09:17 UTC
Hi all,

Thanks to pymc's developers for putting together such an accessible library for non-statisticians like me. That statement serves as a disclaimer as well: I am a scientist, not a statistician, so my early apologies for any poor Bayes form here below. 

My problem requires some background: I'm working on an implementation of Kennedy & O'Hagan's model calibration framework using pymc3 and scikit.

For consistency's sake, the basic form of the calibration model is as follows:
![equation1](http://www.sciweavers.org/tex2img.php?eq=%5Coverbrace%7By_%7Bobs%7D%7D%5E%7B%5Ctextrm%7Bmeasured%20data%7D%7D%3D%20%5Coverbrace%7By_%7Bmodel%7D%7D%5E%7B%5Ctextrm%7Bmodelled%20data%7D%7D%20%2B%20%5Coverbrace%7Bb%7D%5E%7B%5Ctextrm%7Bmodel%20error%7D%7D%20%20%2B%20%20%5Coverbrace%7B%20%5Cvarepsilon%20%7D%5E%7B%5Ctextrm%7Bmeasured%20data%20error%7D%7D%20&bc=White&fc=Black&im=jpg&fs=12&ff=mathdesign&edit=0)

A complex physics model - the one being calibrated - generates deterministic values of "y_model" for every combination of input variables: {var1, var2, var3, etc..}
This model is too computationally expensive for a Bayes Metropolis-Hastings routine to infer posteriors of inputs. It is also time-varying, which in its own right adds complexity (as I understand it) to the calibration methodology post-simulation. Thus, I'm attempting to try something different... not sure if it works or is the right thing to do. I have used scikit.gaussianprocessregressor to generate a GP emulator that predicts the RMSE of time-aggregate outputs of the model as compared to observed data. The model is formulated such that, if 'mu' is the mean output of the GP at {var1, var2, var3, etc.}, and 'theta' is the standard error of the GP at this sample, then:

![equation2](http://latex.codecogs.com/gif.latex?%5Cmu&plus;%20%5Ctheta%20%5Capprox%20%28y_%7Bmodel%7D-y_%7Bobs%7D%29)

On this basis, reverting back to the calibration model, I should now have:

![equation3](http://latex.codecogs.com/gif.latex?0%20%3D%20%5Coverbrace%7B%5Cmu&plus;%20%5Ctheta%7D%5E%7B%5Ctextrm%7Bfrom%20GP%7D%7D%20&plus;%20b%20&plus;%20%5Cvarepsilon)

At least on paper, this looks simple enough. As the GP emulator is in charge of processing the observed data, it seems I only need to produce a calibration model that infers posteriors based on a single "observed" data point: zero. As I see it, the outcome of the calibration model should be posterior distributions of input variables that drive the main physical model to an RMSE of 0 - and that's exactly what one should want when comparing a time-varying model to time-varying data.

If I'm right so far, the next question is how best this is implemented in pymc3.
Saved as a pickle,  I am loading the GP into pymc3 as follows:

```python
from sklearn.externals import joblib
gp = joblib.load('GPmodel.pkl')
```

I can call predictions from the model instantaneously as follows:
```python
mu,theta = gp.predict([[var1,var2,var3]],return_std=True)
```

This is where it gets tricky for me. I'm not sure whether I am to include the GP into pymc3 as a deterministic or as a DensityDist. It's certainly been easier for me to implement it as a deterministic, and I've done the following so far.

I create a deterministic @as_op that calls the GP model
```python
@as_op(itypes=[tt.dscalar,tt.dscalar,tt.dscalar], otypes=[tt.dvector,tt.dvector])
    def muSample(var1,var2,var3):
        muFunc=np.empty(1)
        thetaFunc=np.empty(1)
        mufunc[0],thetafunc[0] = gp.predict([[var1,var2,var3]],return_std=True)
        return mufunc, thetafunc
```

I set up my model as follows:
```python
with pm.Model() as basic_model:

    var1 = pm.Uniform('var1', lower=0, upper=1) # Input variable 1
    var2 = pm.Uniform('var2', lower=0, upper=1) # Input variable 2
    var3 = pm.Uniform('var3', lower=0, upper=1) # Input variable 3
    b = pm.Uniform('b', lower=0, upper=0.02) # Physical model bias, prior set by expert
    eps = pm.HalfNormal('epsilon', sd=10) # Measured data error, prior set by expert

    mu,errSamp = musamp(var1,var2,var3) # Sample from GP model as deterministic
    theta = pm.HalfNormal('theta', sd=errSamp[0]) # Convert deterministic theta (GP model bias/error) into normal distribution about mu

    mu = mu+b+theta 

    result = pm.Normal('y_obs', mu=mu, sd=eps, observed=0)

```

Surprisingly enough, this process seems to be working for me.
I am getting posteriors for var1, var2, var3, etc... and I've been able to create a few proofs based on simple physical models - e.g., means of posteriors = true deterministic values. The question is, despite it 'seeming' to work, does the method actually really make sense? Should I be handling the GP as a deterministic? Would it be easier / faster to handle it as a DensityDist? If so, is that easy to do without breaking down the GP into its own equations? Are there big caveats to this approach? I have to say that despite it working, it's seems particularly slow... Perhaps its due to the expense of calling scikit's model, I'm not sure, but it right now takes 15-18 s/iter when trying to run this routine with the GP of my core physics problem model (21 input variables).

One question you may have is why I am generating a GP a-priori, and not setting up emulation+calibration in an integrated manner, as some research papers have done. The main reason I want to keep emulation and calibration separate is to give myself (and future users) flexibility to replace the GP with other types of deterministic/stochastic surrogate models (i.e., SVR), or omit them completely for computationally inexpensive problems. Hence, I want the pymc3 code to be as robust to future calibration problems as possible.

Thanks very much for reading, and much appreciated for any comments on my approach.
I have written this in the "issues" section for lack of a better forum to ask the pymc experts.

Adam

**Comment by fonnesbeck** [comment] 2016-12-06 21:30
I'm going to close this because, as you say, it is not a bug. Feel free to discuss here, however better outlets would be either the PyMC [Gitter channel](https://gitter.im/pymc-devs/pymc) or on StackOverflow under the [pymc tag](http://stackoverflow.com/questions/tagged/pymc).

I would look at the variational inference methods for fitting GPs, as there are better able to cope with the estimation than MCMC, since they are optimizing rather than sampling.

**Closed as completed by fonnesbeck** 2016-12-06 21:30 UTC

**Comment by adam-rysanek** [comment] 2016-12-07 08:17
Understood. Will post it there. Thanks for the recommendation.

**Comment by twiecki** [comment] 2016-12-07 08:26
@adam-rysanek I did skim your post and it seems like you're on a good track.

**Comment by kejzlarv** [comment] 2018-03-14 17:20
@adam-rysanek did you end up posting the thread somewhere else? I am dealing with the same problem: Bayesian model calibration based on Kennedy-O'Hagan framework with PyMC3, and I am struggling with the implementation with pm.GP.marginal due to the need of the unknown parameteres `$\theta$` being the part of input into cov and mean functions.
