### ISSUE TITLE
BUG: NUTS sampler for Gaussian process regression uses all system cores, even with cores=1

### ISSUE THREAD

**Issue by andrew-angus** [pymc-devs/pymc#6640] opened 2023-03-31 13:36 UTC
### Describe the issue:

Fitting Gaussian process hyperparameters using NUTS sampler uses all system cores (24 in my case), no matter what the cores argument is set to in pm.sample(). The behaviour remains when setting environment variables such as OMP_NUM_THREADS = 1, MKL_NUM_THREADS=1, OPENBLAS_NUM_THREADS=1 within the python script. This is not desired behaviour.

### Reproduceable code example:

```python
import pymc as pm
import numpy as np
import os

# Input and output data for GP
x = np.random.rand(100,2)
y = x[:,0]**2 + x[:,0]- 0.5*x[:,0]*x[:,1] - np.random.normal(scale=0.1)

# Ensure thread environment variables set to one
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"

# PyMC Model
m = pm.Model()
with m:

  # GP Hyperparameters
  gsig = pm.HalfNormal('gs')
  kls = pm.LogNormal('l',shape=2)
  kvar = pm.LogNormal('kv')

  # GP Instance
  kern = pm.gp.cov.ExpQuad(2,ls=kls)
  gp = pm.gp.Marginal(cov_func = kern)
  y_ = gp.marginal_likelihood('y_',X=x,y=y,sigma=gsig)

  # MCMC Sampling
  idata = pm.sample(cores=1)
```

### PyMC version information:

PyMC Version: 5.2.0
PyTensor Version: 2.10.1
Python Version: 3.10.6
Operating System: Ubuntu 22.04.2 LTS x86_64
Install: via pip

### Context for the issue:

Using all system cores, no matter what settings are chosen, is not desirable. It inhibits use of the system for anything else while the sampler is running, which can be for substantial periods of time. It is also likely not optimal to have such an extent of threading on systems with a lot of cores.

**Comment by aseyboldt** [comment] 2023-03-31 21:07
This is strange, thank you for reporting this.
On my machine this is only using one core as expected, but I think @fonnesbeck saw something similar some time ago...

If you could help debug this a bit more, that would be very helpful. Some things I'd try to figure out where this is coming from:

- First, make sure the environment variables are set soon enough. Could you move the `os.environ` calls to the beginning, before numpy is even imported?
- Next, it would be good to see which blas this is using. What is the output of `np.show_config()`?
- Finally, `perf` might give us an idea where this is coming from. To run it under perf you'll have to put the code into a python script and then run it as `perf record -- env PATH=$PATH python thescript.py`. After this is finished, you can run `perf report` to see what it was doing. If you could share a screenshot or so of that, that might help as well.

**Comment by andrewanguswarwick** [comment] 2023-04-02 17:44
Hello, thanks for getting back to me. It seems the issue is resolved by placing the os.environ calls before pymc is imported (doesn't matter if numpy is imported earlier), and in particular setting one of either OMP_NUM_THREADS or OPENBLAS_NUM_THREADS in my case. Thank you for your help.

Nonetheless, in case you are still interested, here is the output of np.show_config():

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL

**Comment by aseyboldt** [comment] 2023-04-02 22:37
Good to hear it's just BLAS being BLAS...
I'll close this since it seems this isn't really a PyMC bug as such.
Maybe it would actually make sense for pymc to call use something like https://github.com/joblib/threadpoolctl internally, so that we can come up with better defaults, and don't surprise users as much. I'm not sure what that should look like in detail though...

**Closed as completed by aseyboldt** 2023-04-02 22:37 UTC
Labels: bug
