### ISSUE TITLE
PyMC causes theano to crash

### ISSUE THREAD

**Issue by vhaasteren** [pymc-devs/pymc#783] opened 2015-07-05 19:44 UTC
I am trying out a tutorial of Theano, and I notice that pymc3 makes it throw a ValueError. The code below fails. However, if I simply remove the pymc3 import, it runs fine. Example:

import pymc3 as pm
import theano as th

print(pm.**version**)

> > 3.0

print(th.**version**)

> > 0.7.0.dev-3e84371d4e0f4d24c5bc784291ee8c0d85e84005

a = th.tensor.dscalar()
b = th.tensor.dscalar()
c = a + b

ValueError                                Traceback (most recent call last)
<ipython-input-3-212e6562b218> in <module>()
      4 
      5 # create a simple expression
----> 6 c = a + b

/Users/vhaaster/env/pint/lib/python2.7/site-packages/theano/tensor/var.pyc in **add**(self, other)
    131     def **add**(self, other):
    132         try:
--> 133             return theano.tensor.basic.add(self, other)
    134         # We should catch the minimum number of exception here.
    135         # Otherwise this will convert error when Theano flags

/Users/vhaaster/env/pint/lib/python2.7/site-packages/theano/gof/op.pyc in **call**(self, _inputs, *_kwargs)
    524                         run_perform = False
    525                     elif config.compute_test_value == 'raise':
--> 526                         raise ValueError('Cannot compute test value: input %i (%s) of Op %s missing default value' % (i, ins, node))
    527                     elif config.compute_test_value == 'ignore':
    528                         # silently skip test

ValueError: Cannot compute test value: input 0 (<TensorType(float64, scalar)>) of Op Elemwise{add,no_inplace}(<TensorType(float64, scalar)>, <TensorType(float64, scalar)>) missing default value

**Comment by twiecki** [comment] 2015-07-05 20:49
This is probably caused by https://github.com/pymc-devs/pymc3/issues/566

**Comment by jsalvatier** [comment] 2015-07-05 21:59
@vhaasteren there's some ideas on how to do this in #566 like thomas said. Would you be interested in making a pull request to fix this?

**Comment by vhaasteren** [comment] 2015-07-05 22:22
@jsalvatier I am definitely willing to contribute. However, given that my first experience with PyMC was two days ago (looks very cool, btw), I am not sure of how much help I can be until I familiarize myself a bit more with the codebase. I will look into it

**Comment by jsalvatier** [comment] 2015-07-05 22:26
Makes sense: the relevant things are in https://github.com/pymc-devs/pymc3/blob/master/pymc3/model.py. The class `Model` inherits from `Context`, and `theano.config.compute_test_value = 'raise'` is done at the bottom of the file, which are likely the things you want to change. 

Let me know if you want to chat for help.

**Comment by vhaasteren** [comment] 2015-07-06 15:18
Thank you for the pointers, that is a good start. I will be in touch if I need help.

**Comment by fonnesbeck** [comment] 2016-07-27 03:30
Closing. Please re-open if you need additional support.

**Closed as completed by fonnesbeck** 2016-07-27 03:30 UTC
