### ISSUE TITLE
Cannot plot any plot which involves arviz

### ISSUE THREAD

**Issue by rlloretb** [pymc-devs/pymc#3960] opened 2020-06-13 10:26 UTC
I cannot plot any plot which seems to depend on arviz, i.e.:

```python
pm.traceplot(trace)
pm.plot_posterior(trace)
```

**Please provide the full traceback.**
```
  File "/Users/lloretroger/Documents/GS_CL_OPT/bayesian_test.py", line 37, in <module>
    pm.traceplot(trace)

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/pymc3/plots/__init__.py", line 23, in wrapped
    return func(*args, **kwargs)

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/pymc3/plots/__init__.py", line 41, in traceplot
    return az.plot_trace(*args, **kwargs)

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/arviz/plots/traceplot.py", line 300, in plot_trace
    plot = get_plotting_function("plot_trace", "traceplot", backend)

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/arviz/plots/plot_utils.py", line 605, in get_plotting_function
    backend=backend, plot_module=plot_module

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/arviz/plots/backends/matplotlib/__init__.py", line 43, in <module>
    from .ppcplot import plot_ppc

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/arviz/plots/backends/matplotlib/ppcplot.py", line 4, in <module>
    from matplotlib import animation, get_backend

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 737, in <module>
    class ImageMagickWriter(ImageMagickBase, MovieWriter):

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 120, in wrapper
    if writerClass.isAvailable():

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 730, in isAvailable
    return super().isAvailable()

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 427, in isAvailable
    return shutil.which(cls.bin_path()) is not None

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 724, in bin_path
    binpath = mpl._get_executable_info('magick').executable

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/__init__.py", line 385, in _get_executable_info
    return impl([path, "--version"], r"^Version: ImageMagick (\S*)")

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/__init__.py", line 330, in impl
    raise _cpe

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/__init__.py", line 325, in impl
    universal_newlines=True, errors="replace")

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)

CalledProcessError: Command '['convert', '--version']' returned non-zero exit status 255.
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.7.7
* Operating system: mac.OS 14.6 Mojave
* How did you install PyMC3: (conda/pip) conda

**Comment by michaelosthege** [comment] 2020-06-13 15:11
This looks like it could be related to the matplotlib backend.

Can you provide a minimal reproducible example? My first guess is that it's a problem with your environment.

**Comment by rpgoldman** [comment] 2020-06-14 00:04
I can't say for sure, but this looks like a problem coming from matplotlib trying to find an installed copy of ImageMagick (the software package, not a python library) and not finding it. This does not look like a problem with Arviz -- it seems to be entirely internal to matplotlib, and more specifically an animation module in matplotlib. 

I'm going to close this and suggest that you ask for help from some matplotlib community. Or don't fight it and just install IM.

**Closed as completed by rpgoldman** 2020-06-14 00:04 UTC
