### ISSUE TITLE
Runtime issue when distribution depends on an observed parameter that use `pm.Data`

### ISSUE THREAD

**Issue by caspbian** [pymc-devs/pymc#4505] opened 2021-03-05 19:52 UTC
## Description of your problem
As per the example below an error is thrown when a distribution or deterministic variable depends upon observed data that is stored within the `pm.Data` class. Commenting out the `temp = pm.Deterministic('temp', a1 * X)` would stop the error arising.

Credit @cluhmann for the minimal example and help refining the issue.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm
x = [0,1]
with pm.Model() as model:
    x_data = pm.Data('x_data', x)
    X = pm.Normal('X', 0, 1, observed=x_data)
    a1 = pm.Normal('a1', 0, 5)
    temp = pm.Deterministic('temp', a1 * X)
    trace = pm.sample()
```

**Please provide the full traceback.**
```python
/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/pymc3/sampling.py:468: FutureWarning: In an upcoming release, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  FutureWarning,
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [a1]
ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_useless_fill,local_useless_alloc,local_subtensor_make_vector,local_useless_elemwise,local_useless_inc_subtensor,local_useless_slice,local_subtensor_of_alloc,local_useless_inc_subtensor_alloc,local_useless_rebroadcast,local_join_1,local_join_empty,local_join_make_vector,local_useless_switch,local_useless_tile,local_useless_split,local_useless_reshape,local_useless_elemwise_comparison,local_useless_reduce,local_view_op,local_merge_alloc,local_useless_topk)
ERROR (theano.gof.opt): node: ViewOp(Elemwise{Cast{float64}}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/gof/opt.py", line 2172, in process_node
    fgraph.replace_all_validate_remove(repl_pairs, reason=lopt, remove=remove)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/gof/toolbox.py", line 613, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/gof/toolbox.py", line 542, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/gof/fg.py", line 496, in replace
    new,
theano.gof.toolbox.BadOptimization: BadOptimization Error 
  Variable: id 139851998833464 Elemwise{Cast{float64}}.0
  Op Elemwise{Cast{float64}}(x_data)
  Value Type: <class 'NoneType'>
  Old Value:  None
  New Value:  None
  Reason:  LocalOptGroup(local_useless_fill,local_useless_alloc,local_subtensor_make_vector,local_useless_elemwise,local_useless_inc_subtensor,local_useless_slice,local_subtensor_of_alloc,local_useless_inc_subtensor_alloc,local_useless_rebroadcast,local_join_1,local_join_empty,local_join_make_vector,local_useless_switch,local_useless_tile,local_useless_split,local_useless_reshape,local_useless_elemwise_comparison,local_useless_reduce,local_view_op,local_merge_alloc,local_useless_topk). The type of the replacement must be the same.
  Old Graph:
  ViewOp [id A] <TensorType(int32, vector)> 'X'   
   |Elemwise{Cast{float64}} [id B] <TensorType(float64, vector)> ''   
     |x_data [id C] <TensorType(int32, vector)>
  New Graph:
  Elemwise{Cast{float64}} [id B] <TensorType(float64, vector)> ''   
Hint: relax the tolerance by setting tensor.cmp_sloppy=1
  or even tensor.cmp_sloppy=2 for less-strict comparison
ERROR (theano.gof.opt): Optimization failure due to: local_view_op
ERROR (theano.gof.opt): node: ViewOp(Elemwise{Cast{float64}}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/gof/opt.py", line 2172, in process_node
    fgraph.replace_all_validate_remove(repl_pairs, reason=lopt, remove=remove)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/gof/toolbox.py", line 613, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/gof/toolbox.py", line 542, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/gof/fg.py", line 496, in replace
    new,
theano.gof.toolbox.BadOptimization: BadOptimization Error 
  Variable: id 139851998833464 Elemwise{Cast{float64}}.0
  Op Elemwise{Cast{float64}}(x_data)
  Value Type: <class 'NoneType'>
  Old Value:  None
  New Value:  None
  Reason:  local_view_op. The type of the replacement must be the same.
  Old Graph:
  ViewOp [id A] <TensorType(int32, vector)> 'X'   
   |Elemwise{Cast{float64}} [id B] <TensorType(float64, vector)> ''   
     |x_data [id C] <TensorType(int32, vector)>
  New Graph:
  Elemwise{Cast{float64}} [id B] <TensorType(float64, vector)> ''   
Hint: relax the tolerance by setting tensor.cmp_sloppy=1
  or even tensor.cmp_sloppy=2 for less-strict comparison
Traceback (most recent call last):
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/compile/function/types.py", line 974, in __call__
    if output_subset is None
TypeError: expected type_num 5 (NPY_INT32) got 12
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-03ed62d87df9>", line 8, in <module>
    trace = pm.sample()
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/pymc3/sampling.py", line 557, in sample
    trace = _mp_sample(**sample_args, **parallel_args)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/pymc3/sampling.py", line 1450, in _mp_sample
    strace = _choose_backend(None, idx, model=model)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/pymc3/sampling.py", line 1378, in _choose_backend
    return NDArray(**kwds)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/pymc3/backends/ndarray.py", line 219, in __init__
    super().__init__(name, model, vars, test_point)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/pymc3/backends/base.py", line 77, in __init__
    var_values = list(zip(self.varnames, self.fn(test_point)))
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/pymc3/model.py", line 1539, in __call__
    return self.f(**state)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/compile/function/types.py", line 989, in __call__
    storage_map=getattr(self.fn, "storage_map", None),
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/gof/link.py", line 343, in raise_with_op
    raise exc_value.with_traceback(exc_trace)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/theano/compile/function/types.py", line 974, in __call__
    if output_subset is None
TypeError: expected type_num 5 (NPY_INT32) got 12
Apply node that caused the error: Elemwise{mul,no_inplace}(InplaceDimShuffle{x}.0, X)
Toposort index: 4
Inputs types: [TensorType(float64, (True,)), TensorType(int32, vector)]
Inputs shapes: [(1,), (2,)]
Inputs strides: [(8,), (8,)]
Inputs values: [array([0.]), array([0., 1.])]
Outputs clients: [['output']]
Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/snap/pycharm-professional/230/plugins/python/helpers/pydev/_pydev_bundle/pydev_ipython_console_011.py", line 482, in add_exec
    self.ipython.run_cell(line, store_history=True)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2867, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3072, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/aj8907/.virtualenvs/tmp-a4b1a4aabcd6ddc/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-03ed62d87df9>", line 7, in <module>
    temp = pm.Deterministic('temp', a1 * X)
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Please provide any additional information below.**
Discourse discussion on the issue can be found here:
https://discourse.pymc.io/t/bernoulli-distribution-issues-when-using-data-class/6910/5

## Versions and main components

* PyMC3 Version: 3.10.0
* Aesara Version: Theano==1.0.5 and Theano-PyMC==1.0.11
* Python Version: 3.6.9
* Operating system: Ubuntu 18.04.5 LTS
* How did you install PyMC3: pip

**Comment by cluhmann** [comment] 2021-04-06 01:49
Two bits of additional information.  First, creating data to be a vector of floats (`x = [0., 1.]`) resolves the problem.  So it seems like there is a type conflict that comes about when wrapping the list of ints in `pm.Data()`?  The same can be achieved by creating the data as a numpy array:

```python
# works
x_data = pm.Data('x_data', np.array([0,1], dtype=float))
```

```python
# doesn't work
x_data = pm.Data('x_data', np.array([0,1], dtype=int))
```

Second, pymc 3.8/theano 1.0.5 doesn't seem to suffer from this problem, suggesting that this is a regression  (I'm testing on pymc3 3.11/theano 1.1).  Hopefully that helps.

**Comment by ricardoV94** [comment] 2021-12-22 09:08
This now samples fine in `main`, although we get a `UserWarning` when creating the InferenceData because the data is "ocluded" by the casting to float:

```
 UserWarning: Could not extract data from symbolic observation X
```

```python
print(X.tag.observations)
# Elemwise{Cast{float64}}.0
```

**Comment by michaelosthege** [comment] 2022-01-10 13:04
I the data container is fed a NumPy array, it takes whichever dtype that ndarray has.

Also we now have `pm.ConstantData` that might be easier to work because it gives a `TensorConstant`.

I'm closing this issue, since the examples above are working fine on `main`.

**Closed as completed by michaelosthege** 2022-01-10 13:04 UTC
