### ISSUE TITLE
Tutorial real work about simple and multiple linear regression bayesian.

### ISSUE THREAD

**Issue by nguyenhoaiThanhbk2811** [pymc-devs/pymc#3195] opened 2018-09-14 16:54 UTC
## Versions and main components

* PyMC3 Version: pyMC3
* Theano Version: 1.0.2
* Python Version:3.53
* Operating system: window
* How did you install PyMC3: (conda/pip) anacoda

Dear everyone.
I am newer using Pymc3. I have a problem need everyone help me. My problem is I have a function F(x,y,z). the variable (x,y,z) has the distribution is Uniform and have the value corresponding to ([0.3;0.6],[0.9;1.1],[45;55]). The first, I keep the Y and Z value in the center position. I conducted experiments with the X value I employ random value of X with 10 samples. I have 10 values of function F.

example: I have x value [ 0.3,0.32,0.35,0.37,0.4,0.43,0.45,0.5,0.55,0.6] then I have corresponding values functions F [0.002,0.0025,0.0024,0.0026,0.0027,0.00278,0.0265,0.0281,0.0286,0.0295]

How to apply Bayesian to my problem? 
My target is to find the Mean, variance of the Function value and predict the value of the function when I have the x value.

My future target, don't keep the value of Y and Z. I find the Mean, variance of the function and predict the value of the function when I do not fix Y, Z which I fix value above.
everyone Who has an idea helps me, please

sincerely thanks

HoaiThanh

**Comment by fonnesbeck** [comment] 2018-09-14 17:55
This is not a bug report, so I am closing. Please post to our Discourse site.

**Closed as completed by fonnesbeck** 2018-09-14 17:55 UTC
