### ISSUE TITLE
Really slow glm with increasing samples

### ISSUE THREAD

**Issue by napsternxg** [pymc-devs/pymc#884] opened 2015-12-08 02:12 UTC
I am trying out `pymc3` and was using the R style formula feature to train a simple GLM model using a very small data of just 10 instances as described below:

```
In [23]: with Model() as model_glm:
    glm("y~X", data)
    trace = sample(10)
   ....:     
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to Intercept
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to X
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to sd_log
 [-----------------100%-----------------] 10 of 10 complete in 0.0 sec
In [24]: with Model() as model_glm:
    glm("y~X", data)
    trace = sample(100)
   ....:     
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to Intercept
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to X
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to sd_log
 [-----------------100%-----------------] 100 of 100 complete in 0.2 sec

In [25]: with Model() as model_glm:
    glm("y~X", data)
    trace = sample(1000)
   ....:     
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to Intercept
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to X
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to sd_log
 [-----------------45%                  ] 450 of 1000 complete in 222.6 sec
```

Why is it that the sampling of 10 to 100 is taking very less time but for 1000 is taking exponentially more time. I had to stop it after some time. However, when I increase the data size to 1000 or 100000 samples then the sampling finishes faster. 

```
In [26]: X = np.random.randn(1000)

In [27]: y = 2*X + 1

In [28]: data = pd.DataFrame(np.vstack((X,y)).T, columns=["X","y"])

In [29]: with Model() as model_glm:
    glm("y~X", data) # data is 1000 instances
    trace = sample(1000)
   ....:     
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to Intercept
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to X
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to sd_log
 [-----------------100%-----------------] 1000 of 1000 complete in 4.4 sec

In [34]: with Model() as model_glm:
    glm("y~X", data)  # data is 100000 instances
    trace = sample(1000)
   ....:     
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to Intercept
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to X
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to sd_log
 [-----------------100%-----------------] 1000 of 1000 complete in 29.9 sec
```

However, with 100000 instances the sampling of 100000 samples also takes a lot of time for the same model. 

```
In [36]: with Model() as model_glm:
    glm("y~X", data)
    trace = sample(100000)
   ....:     
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to Intercept
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to X
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to sd_log
 [--                5%                  ] 5667 of 100000 complete in 319.0 sec

```

**Comment by fonnesbeck** [comment] 2015-12-08 13:39
Is this happening stochastically, or every time you run the model under these settings? Do you have some data to share so that I can try to replicate it?

My first suggestion is to run `find_MAP()` before sampling to get some decent starting values:

``` python
with model_glm:
    start = find_MAP()
    trace = sample(100000, start=start)
```

The NUTS sampler stalling under some conditions is a known issue (e.g. #555) for which we have not yet conjured a solution. We should be coming up with a way of at least halting sampling when this happens.

**Comment by napsternxg** [comment] 2015-12-08 18:43
@fonnesbeck thanks for the reply. The following example replicates the issue:

```
X = np.random.randn(1000)
y = 2*X + 1
data = pd.DataFrame(np.vstack((X,y)).T, columns=["X","y"])
with Model() as model_glm:
    glm("y~X", data)
    print "Finished GLM"
    start = find_MAP()
    print "Finished MAP"
    trace = sample(100000, start=start)
```

The above examples gets stuck after the following lines:

```
Finished GLM
Finished MAP
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to Intercept
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to X
Assigned <class 'pymc3.step_methods.nuts.NUTS'> to sd_log
```

**Comment by fonnesbeck** [comment] 2015-12-08 19:05
OK, I can confirm this. I get stuck right away.

``` python
In [1]: run -i stuck.py
Finished GLM
Finished MAP
Assigned NUTS to Intercept
Assigned NUTS to X
Assigned NUTS to sd_log
 [-------          20%                  ] 20 of 100 complete in 0.5 sec
```

Particularly after starting with the MAP estimate, this simple model should run very fast.

**Comment by tyarkoni** [comment] 2016-01-24 21:26
I'm pretty new this whole MCMC sampling thing, so apologies if my comments here are incoherent or (more likely) obvious to everyone else. But I've been running into similar issues, and have spent some time experimenting with this. Some observations:
- As far as I can tell, NUTS primarily gets "stuck" when it manages to very quickly converge on (what appears to be) the correct solution. This is evident in @napsternxg's toy model: the MAP estimate is basically correct, and the gradient around it is very steep, so in a sense, it's not clear what the point of further sampling would be. The posteriors produced by Metropolis (which nominally "succeeds" in generating an arbitrary number of samples) when applied to the same problem have a variance of essentially zero. So presumably Metropolis avoids stalling by accepting very small (but unhelpful) proposals, whereas NUTS refuses to. Adding even a small amount of noise to @napsternxg's model appears to "unstick" the NUTS sampler, as does omitting the find_MAP step (though, naturally, it still stalls once it converges on the right solution).
- It's not obvious to me that it would be a good thing for the NUTS algorithm to forcibly unstick itself if there's very little variance and the sampler is unable to move to another reasonable point. If the probability of finding a better state via large jumps is very low, accepting bad estimates is only going to artificially increase the variance of the posterior and waste cycles. Conversely, if the sampler nominally keeps running even though it's not really going anywhere--as Metropolis does in the above example--this could inspire overconfidence in the resulting estimate. Personally, in such cases, I would actually _prefer_ that the sampler halt early--I can use that information to inform my subsequent analyses. So I second @fonnesbeck's suggestion to halt if necessary, but would argue that this should maybe be seen as a feature and not a bug. Ideally it would be nice to have some accessible explanation or metric produced alongside the trace that provides some insight into the halting (e.g., would it be meaningful to store a trace of the rate of proposal rejections across samples? Apologies if something like this is already implemented; as I said, this is all new to me).
- One counterintuitive behavior I've noticed in some of my datasets (which I think may also explain @napsternxg's sample size-related observations) is that when the dataset is small, or the model is close to unidentified, NUTS paradoxically runs fine, because there isn't enough data to converge on the correct estimate. As you add data (holding model structure constant), the estimates can converge quite quickly, so if the gradient is steep, you can find that even adding relatively small amounts of data (e.g., going from 100 to 200 data points) causes NUTS to go from extremely fast sampling to completely stuck. But again, this seems to me like a feature and not a bug (or at least, it would be, if the sampler spontaneously halted).
- +1 on @twiecki's suggestion in #555 to provide some guidance to users on data scaling or NUTS parameter tuning. I've played around a bit with the NUTS parameters but can't seem to ever prevent it from getting stuck.
- Are there any systematic (or even casual) explorations of the quality of the solutions NUTS produces when it gets stuck? My limited experience so far has been that even when NUTS stalls, it usually produces posteriors at least as good as those generated by Metropolis after many more "successful" samples. So, again, I probably wouldn't characterize this as a failure of the algorithm, except in the sense that it should maybe stop sampling sooner.

**Comment by twiecki** [comment] 2016-01-25 13:27
Thanks for the detailed thoughts @tyarkoni. I wonder if we could get the thoughts of some @stan-dev members here who I'm sure have encountered and solved this problem of NUTS getting stuck when the gradient is very steep. CC @syclik @betanalpha @bob-carpenter

**Comment by syclik** [comment] 2016-01-25 13:56
@twiecki, the stepsize needs to be smaller. Perhaps your tuning is terminating much too early and only exploring the space with less steep gradients?

**Comment by bob-carpenter** [comment] 2016-01-25 21:00
As Daniel said, sometimes setting the step size smaller can work
(both the initial step size and the target of adaptated acceptance
rate, assuming we're talking about NUTS here).  That lets the
first-order gradient following algorithm of HMC compensate for
steep curvature.

A better bet, where possible, is to reparameterize.  If there
are small numbers of data points in hierarchical groups, you want
to use a non-centered parameterization rather than the textbook one.
It reduces posterior curvature as we describe in the Stan manual and
as described in Betancourt (aka @betanalpha) and Girolami's arXiv
paper on hierarchical models.
- Bob

**Comment by twiecki** [comment] 2016-01-25 21:12
Many thanks for the responses @bob-carpenter and @syclik, that's very helpful.

I had another look at the example and I actually think something else is going on with the `glm` function. The model:

``` python
import pandas as pd
import numpy as np
import pymc3 as pm
X = np.random.randn(1000)
y = 2*X + 1

with pm.Model():
    beta = pm.Normal('beta', 0, 1)
    alpha = pm.Normal('alpha', 0, 1)
    sd = pm.HalfCauchy('sd', beta=10)

    pm.Normal('obs', mu=alpha + beta*X, observed=y)
    print("Finished GLM")
    start = pm.find_MAP()
    print("Finished MAP")
    print(start)
    #hess = pm.find_hessian(start)
    #start['sd_log'] = np.array(0.)
    step = pm.NUTS(scaling=start, step_scale=.25)
    trace = pm.sample(1000, step, start=start)
```

Runs fine while it should be equivalent with the `glm` version. I'll have a look soon.

**Comment by fonnesbeck** [comment] 2016-01-26 17:03
@tyarkoni I would hope that the issue is not what you suggest. The NUTS algorithm satisfies detailed balance, which means that it is not merely climbing to the maximum, but moving to all parts of the target posterior as governed by the posterior probabilities. So, I'm confident that there is just something in our implementation of the algorithm that needs changing.

Tweaking the step size is probably the easiest place to start. If we can automatically detect when the sampler stalls, we should be able to trigger a reduction in step size by some factor. I suppose the trace to that point should be tossed out, and have the sampling start again from zero.

**Comment by twiecki** [comment] 2016-01-26 17:04
I'm pretty sure it's a bug in `glm`.

**Comment by fonnesbeck** [comment] 2016-01-26 17:07
Perhaps, but I observe stalling in my own work quite often when using NUTS, for models that I'm not using the `glm` module.

**Comment by ColCarroll** [comment] 2019-08-16 14:46
Closing since so much has changed, and https://pandas.pydata.org/speed/pymc3/ exists.

**Closed as completed by ColCarroll** 2019-08-16 14:46 UTC
