### ISSUE TITLE
theano max works but not min

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/pymc#3831] opened 2020-03-15 12:30 UTC
Its seems that my version of PyMC3/Theano won't compile models containing `tt.min()` but will compile models with `tt.max()`. I've tried replacing `tt.min([a, b], axis=0)` with the workaround `-tt.max([-a, -b], axis=0)` and while this works for the toy example below, in real models, it sometimes yields the same compilation error as using `min`. This must be related but I haven't figured out the critical issue.

```
import pymc3 as pm
import theano.tensor as tt


def main():
    with pm.Model() as m1:

        a = pm.Normal(name="a", shape=5)
        b = pm.Normal(name="b", shape=5)
        c = tt.max([a, b], axis=0)

    pm.sample(model=m1)  # works fine

    with pm.Model() as m2:

        a = pm.Normal(name="a", shape=5)
        b = pm.Normal(name="b", shape=5)
        c = tt.min([a, b], axis=0)

    pm.sample(model=m2)  # raises this exception:
    # ... error: non-constant-expression cannot be narrowed from type 'npy_intp' (aka
    # 'long') to 'int' in initializer list [-Wc++11-narrowing]


if __name__ == '__main__':
    main()
```

* PyMC3 Version: **3.8**
* Theano Version: **1.0.4**
* Python Version: **3.8.1**
* Operating system: **MacOS**
* How did you install PyMC3: **conda**

**Comment by aloctavodia** [comment] 2020-03-19 12:25
I am not able to reproduce this error. 


* PyMC3 Version: master
* Theano Version: 1.0.4
* Python Version: 3.7.6
* Operating system: Linux

**Comment by Ahanmr** [comment] 2020-04-01 21:46
I tried with the exact same specs, I too was not able to reproduce the error, it ran successfully. Not sure, what's causing the error.

`Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Sequential sampling (2 chains in 1 job)
NUTS: [b, a]
Sampling chain 0, 0 divergences: 100%|██████████| 1000/1000 [00:01<00:00, 774.57it/s]
Sampling chain 1, 0 divergences: 100%|██████████| 1000/1000 [00:00<00:00, 1363.44it/s]
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Sequential sampling (2 chains in 1 job)
NUTS: [b, a]
Sampling chain 0, 0 divergences: 100%|██████████| 1000/1000 [00:00<00:00, 1280.23it/s]
Sampling chain 1, 0 divergences: 100%|██████████| 1000/1000 [00:00<00:00, 1363.76it/s]`

- PyMC3 Version: 3.8

- Theano Version: 1.0.4

- Python Version: 3.6.9 and 3.8.1

- Operating system: Linux

**Comment by Ahanmr** [comment] 2020-04-01 21:51
I'm not too sure if this is a work-around, please feel free to correct me, 
`import theano`
`theano.config.gcc.cxxflags = "-Wno-c++11-narrowing"`

**Comment by fonnesbeck** [comment] 2020-04-02 02:19
This flag is set automatically for macOS to solve a different issue, but is not set for Linux. If this solves the problem, we could add it for that platform as well.

**Comment by ricardoV94** [comment] 2021-03-10 15:03
@sammosummo Did you keep encountering this issue in newer releases?

**Comment by sammosummo** [comment] 2021-03-10 15:40
Works fine with this setup:

- PyMC3 Version: 3.9.3
- Theano Version: 1.0.5
- Python Version: 3.8.5
- Operating system: macOS

**Comment by ricardoV94** [comment] 2021-03-10 15:43
Thanks for the feedback. Will close this issue as it seems we did not hear more reports like this

**Closed as completed by ricardoV94** 2021-03-10 15:43 UTC
