### ISSUE TITLE
Scalar constant data is promoted to rank 1 in returned InferenceData

### ISSUE THREAD

**Issue by TimOliverMaier** [pymc-devs/pymc#6755] opened 2023-06-03 14:12 UTC
### Describe the issue:

This week I encountered a strange behavior in a model that employs the `pymc.math.erf` function. 
I tried to investigate this to be able to file a constructive issue, but until now I was only able to generate a "somewhat" ;) minimal example.  

The error function comes into play because I need the integral of the normal pdf.  It's a model for mass spectrometry and the integral is used to estimate the fraction of ions hitting the detector at one measurement. 

Think of the data of interest as a signal like this:
![data](https://github.com/pymc-devs/pymc/assets/25755339/ebfcacb6-540a-4d60-bab1-167c0da5da3a)

What I expect from the model below and what I get without the TensorConstant in the sigma of the normal distribution `pos`: 

![expected](https://github.com/pymc-devs/pymc/assets/25755339/b9155544-ffd2-44ab-b0dd-c89ccbf729bf)

What I get with the Tensorvariable :

![unexpected](https://github.com/pymc-devs/pymc/assets/25755339/b706ad17-2ba2-4862-b0b9-ab7f3607ff85)

Cheers!

### Reproduceable code example:

```python
import numpy as np
import pymc as pm
import pymc.math as pmath
import scipy.stats as sps
import matplotlib.pyplot as plt

# total count of ions
N = 1000
# integral span of detector
d = 0.001

_x = np.arange(-40,40)/(1/d) 
# number of ions in (x_{i},x_{i+1}]
_y = np.diff(sps.norm.cdf(_x,loc=0,scale=0.01))*N
# ion count with some noise
y = sps.norm.rvs(loc=_y,scale=np.sqrt(_y))
# x axis, one x is now representative for one integration 
# interval and positioned in the middle of it
x = _x[:-1]+0.0005

plt.plot(x,y)
plt.show()
with pm.Model() as model:
    X = pm.MutableData("x",x, dims=["data_point"])
    Y = pm.MutableData("y",y, dims=["data_point"])
    # This Container C here is making the problems
    C = pm.MutableData("c",2)
    pos  = pm.Normal("pos", mu=0, sigma=0.04/C ,initval=0) #  unexpected behavior 
    #pos = pm.Normal("pos", mu=0, sigma=0.02, initval=0) # expected behavior
    r = pm.Deterministic("r",var=0.5*(pmath.erf(((X+d/2)-pos)/(0.01*pmath.sqrt(2)))-pmath.erf(((X-d/2)-pos)/(0.01*pmath.sqrt(2)))), dims=["data_point"])
    mu = pm.Deterministic("mu",var=N*r, dims=["data_point"])
    obs = pm.Normal("obs", mu=mu, sigma=pmath.sqrt(mu), observed=Y,dims=["data_point"])

with model:
    trace= pm.sample(init="adapt_diag")
    pm.sample_posterior_predictive(trace, extend_inferencedata=True, var_names=["mu","obs","r"])
    pm.sample_posterior_predictive(trace, extend_inferencedata=True, predictions=True, var_names=["mu","obs","r"])

# extract data and plot
x = trace.constant_data.x.to_dataframe().reset_index()
y_obs = trace.observed_data.obs.to_dataframe().reset_index()
mu = trace.posterior_predictive["mu"].to_dataframe().reset_index()

df = x.merge(y_obs, on ="data_point").merge(mu, on="data_point")
plt.scatter(df.x,df["mu"],color="blue",alpha=0.2)
plt.scatter(df.x,df.obs, color="black")
plt.show()
```

### PyMC version information:

pymc : 5.4.1+1.g4d2b2efc2
pytensor: 2.12.1

**Comment by TimOliverMaier** [comment] 2023-06-05 08:57
I investigated further and found a "more minimal" example:

```python3

import pymc as pm
import numpy as np
import matplotlib.pyplot as plt


x= np.arange(-100,100)/10
y = 2.2*x-0.4+np.random.normal(0,1, size=x.size)
plt.scatter(x,y)

with pm.Model() as model:
    X = pm.MutableData("x",x, dims=["data_point"])
    Y = pm.MutableData("y",y, dims=["data_point"])
    C = pm.MutableData("c",2)
    #m = pm.Normal("m",mu=2,sigma=0.5) # expected behavior
    m = pm.Normal("m",mu=2,sigma=1/C) # unexpected
    
    b  = pm.Normal("b",mu=0,sigma=1)
    
    mu = pm.Deterministic("mu", var=m*X+b, dims=["data_point"])
    obs = pm.Normal("obs", mu=mu, sigma=1, observed=Y, dims=["data_point"])
    
    trace = pm.sample()   
    trace = pm.sample_posterior_predictive(trace,extend_inferencedata=True,var_names=["mu","obs"]) 
    
# extract data and plot
xs = trace.constant_data.x.to_dataframe().reset_index()
mus = trace.posterior_predictive.mu.to_dataframe().reset_index()
df = xs.merge(mus,on="data_point")
plt.scatter(df.x,df.mu)
plt.show()

```
The expected outcome here:
![expected](https://github.com/pymc-devs/pymc/assets/25755339/ff664d5b-b574-4fad-a13d-b32998df413b)

The unexpected outcome:
![unexpected](https://github.com/pymc-devs/pymc/assets/25755339/887bc7e1-7181-46f0-904b-41d2e386cb52)

Also, note that the issue comes with the usage of `sample_posterior_predictive` 
Taking `mu` from the `posterior` group instead of the `posterior_predictive` group seems to work fine for both cases.  The reason why I can't just take the `posterior` group is the need for out-of-sample predictions.

 I am happy to help here, but I am currently too clueless. Any thoughts on this are very much appreciated :)

**Comment by ricardoV94** [comment] 2023-06-08 12:59
The problem is that `m` is resampled (you should be able to see it in the printed log.
Something like: `Sampling: [m, obs]`

The bug seems to be caused by `C` being a scalar...

This works...
```python
import pymc as pm
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(-100, 100) / 10
y = 2.2 * x - 0.4 + np.random.normal(0, 1, size=x.size)

with pm.Model() as model:
    X = pm.MutableData("x", x, dims=["data_point"])
    Y = pm.MutableData("y", y, dims=["data_point"])
    C = pm.MutableData("c", [2])
    # m = pm.Normal("m",mu=2,sigma=0.5) # expected behavior
    m = pm.Normal("m", mu=2, sigma=1 / C[0])  # unexpected

    b = pm.Normal("b", mu=0, sigma=1)

    mu = pm.Deterministic("mu", var=m * X + b, dims=["data_point"])
    obs = pm.Normal("obs", mu=mu, sigma=1, observed=Y, dims=["data_point"])

    trace = pm.sample()
    trace = pm.sample_posterior_predictive(trace, extend_inferencedata=True, var_names=["mu", "obs"])
```

The faulty comparison happens here: https://github.com/pymc-devs/pymc/blob/b17a60de0b8c601246fb21ac3ea3ab5fbb8a4ea1/pymc/sampling/forward.py#L194-L201

Where `old_array_value` is promoted to `[2]` instead of `2`

**Comment by TimOliverMaier** [comment] 2023-06-08 17:05
I understand, thanks for the very good explanation @ricardoV94. I'll have a look and see if I can find the buggy scalar-registration.

**Comment by TimOliverMaier** [comment] 2023-06-08 18:16
Well, I found the function, changed a line and it worked. Wanted to commit it but git said "nothing to commit, working tree clean". Turns out it was an arviz function.

**Comment by ricardoV94** [comment] 2023-06-08 18:18
Really? So it doesn't happen on our side? Can you reproduce with only arviz code?

**Comment by TimOliverMaier** [comment] 2023-06-08 18:19
I edited my comment, that is the function that makes the scalar 1d

**Comment by TimOliverMaier** [comment] 2023-06-08 18:24
Of course, we could change the code in some way on the pymc end and alter what that arviz function is returning. It is funny anyway that such a simple function is outsourced.

**Comment by TimOliverMaier** [comment] 2023-06-08 18:31
I have to check more cloesly where my debugger leads me. It seems, the last pymc function is this one here: 

https://github.com/pymc-devs/pymc/blob/8b5f437bf8c0650eed331c94cc99c1cafef9d8ce/pymc/backends/arviz.py#LL394C1-L407C10

**Comment by TimOliverMaier** [comment] 2023-06-08 18:36
pymc : constant_data as dictionary : {"x":array([...]),"y":array([...]),"c":array(2)}
and then calls `dict_to_dataset` from arviz. Even with `library=pymc`. So maybe this really is rather to handle on arviz side?

**Comment by ricardoV94** [comment] 2023-06-08 18:49
CC @OriolAbril

**Comment by OriolAbril** [comment] 2023-06-08 19:28
I am quite sure this is already fixed in https://github.com/arviz-devs/arviz-base ([dict_to_dataset](https://github.com/arviz-devs/arviz-base/blob/main/src/arviz_base/base.py#L204) should handle both shape 0 arrays and actual scalars), not sure if it is possible to fix as is on arviz itself or if a refactoring would be needed (in which case I am not sure it is worth to duplicate efforts on this partial refactor given the already existing large scale one).

I will add tests for this to arviz-base though, to ensure it works and it can't be broken unknowingly.

In the meantime too, another potential workaround (might be more annoying than the `[2]` though) is:
```
trace = pm.sample()
trace.constant_data["C"] = trace.constant_data["C"].squeeze(drop=True)
trace = pm.sample_posterior_predictive(trace, extend_inferencedata=True, var_names=["mu", "obs"])
```

also possible to do `squeeze("c_dim_0", drop=True)` to remove this dimension and keep other length one dimensions present.

**Comment by TimOliverMaier** [comment] 2023-06-08 19:46
I see. Thanks for the clarification. So maybe (until pymc uses the new arviz) squeeze the dims away for scalars in `constant_data_to_xarray`?

**Comment by ricardoV94** [comment] 2023-06-09 05:21
> I see. Thanks for the clarification. So maybe (until pymc uses the new arviz) squeeze the dims away for scalars in `constant_data_to_xarray`?

Sounds reasonable

**Closed as completed** 2023-06-16 04:32 UTC
Labels: bug, shape problem, trace-backend
