### ISSUE TITLE
ODE Benchmarking

### ISSUE THREAD

**Issue by Dpananos** [pymc-devs/pymc#3694] opened 2019-11-26 17:12 UTC
As per discussion on slack, ODE needs benchmarking.  I'll create a toy example ODE and commit when ready referencing this issue.

**Comment by ColCarroll** [comment] 2019-11-26 18:50
Do you think something like this is appropriate (piggybacking from @michaelosthege's benchmark notebook)? It takes 5 minutes for 200 samples, which feels like it will be a pretty noisy observation. I would love if we had an example that was like, 1000 samples with no warnings in 1-2 minutes, but that may be wishful thinking...

![image](https://user-images.githubusercontent.com/2295568/69663030-6e796180-1053-11ea-84fe-18f6829bde50.png)

**Comment by Dpananos** [comment] 2019-11-26 22:24
The example I wrote in `ODE_API_Introduction.py` makes about 1000 samples in 2 minutes.  It is a pretty simple example: one dimensional ODE with two parameters.  I guess it depends what exactly we want to benchmark.

In the unit tests, I wrote tests for 1/2 parameters in 1/2 dimensions (so a total of 4 tests in total).  Would you want to do the same thing for benchmarking, or would one simple example do?

**Comment by michaelosthege** [comment] 2019-11-26 22:48
Benchmarkings of pm.sample will always be noisy and slow.
In my notebook, there's also a cell to benchmark just the model gradient. It's still noisy, because it's fed with random prior samples, but it's much faster.

**Comment by Dpananos** [comment] 2019-11-27 18:32
Whats the goal for the benchmarking?  What is being measured?

**Comment by ColCarroll** [comment] 2019-11-27 20:45
General goal is as an "integration test" for the project. There are some big changes whose effects might be checked on in some cases (#3605, for example), but it is hard to tell their effect project-wide. 

One goal of this might be to have caught more quickly the regression on the ODE side from our refactor!

So: we want to run through the machinery in a ~real world application, and this will make sure it does not get significantly slower.

Aside: other projects test very small, fast functions, and can check more granularly where regressions happen. We haven't figured out how to do that (alternatively, we decided *not* to do that)

**Comment by Dpananos** [comment] 2019-11-28 17:44
Ok, that clarifies.  I can carve out some time this weekend.

**Comment by michaelosthege** [comment] 2019-12-21 14:07
was closed by #3730

**Closed as completed by michaelosthege** 2019-12-21 14:07 UTC
