### ISSUE TITLE
Encountered an error when using the sample function with pymc3.9.

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#4224] opened 2020-11-12 07:42 UTC
## Description of your problem
When running the following program:

```python
import pymc3 as pm
import numpy as np
import arviz as az
import pandas as pd

y = pd.read_csv('rarecurve.csv')

y.columns = ['sample', 'clonetype']

y = pd.Series(y.iloc[:, 1])

years = np.arange(0, 400000)

with pm.Model() as disaster_model:
    switchpoint = pm.DiscreteUniform("switchpoint", lower=years.min(), upper=years.max())

    early_rate = pm.Exponential("early_rate", 1.0)

    late_rate = pm.Exponential("late_rate", 1.0)

    rate = pm.math.switch(switchpoint >= years, early_rate, late_rate)

    disasters = pm.Poisson("disasters", rate, observed=y)

with disaster_model:
    trace = pm.sample(10000, return_inferencedata=False)

az.plot_trace(trace)

```
**Please provide the full traceback.**
I got an error seems to be related to the sample function, and here are the details:

```python
Multiprocess sampling (4 chains in 4 jobs)
CompoundStep
>Metropolis: [switchpoint]
>NUTS: [late_rate, early_rate]
pymc3.parallel_sampling.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lab/anaconda3/envs/p/lib/python3.7/site-packages/pymc3/parallel_sampling.py", line 137, in run
    self._start_loop()
  File "/home/lab/anaconda3/envs/p/lib/python3.7/site-packages/pymc3/parallel_sampling.py", line 191, in _start_loop
    point, stats = self._compute_point()
  File "/home/lab/anaconda3/envs/p/lib/python3.7/site-packages/pymc3/parallel_sampling.py", line 218, in _compute_point
    point, stats = self._step_method.step(self._point)
  File "/home/lab/anaconda3/envs/p/lib/python3.7/site-packages/pymc3/step_methods/compound.py", line 42, in step
    point, state = method.step(point)
  File "/home/lab/anaconda3/envs/p/lib/python3.7/site-packages/pymc3/step_methods/arraystep.py", line 263, in step
    apoint, stats = self.astep(array)
  File "/home/lab/anaconda3/envs/p/lib/python3.7/site-packages/pymc3/step_methods/hmc/base_hmc.py", line 154, in astep
    self.potential.raise_ok(self._logp_dlogp_func._ordering.vmap)
  File "/home/lab/anaconda3/envs/p/lib/python3.7/site-packages/pymc3/step_methods/hmc/quadpotential.py", line 263, in raise_ok
    raise ValueError('\n'.join(errmsg))
ValueError: Mass matrix contains zeros on the diagonal. 
The derivative of RV `early_rate_log__`.ravel()[0] is zero.

The above exception was the direct cause of the following exception:

ValueError: Mass matrix contains zeros on the diagonal. 
The derivative of RV `early_rate_log__`.ravel()[0] is zero.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lab/zts/zh/tcr_bayes.py", line 26, in <module>
    trace = pm.sample(10000, return_inferencedata=False)
  File "/home/lab/anaconda3/envs/p/lib/python3.7/site-packages/pymc3/sampling.py", line 545, in sample
    trace = _mp_sample(**sample_args, **parallel_args)
  File "/home/lab/anaconda3/envs/p/lib/python3.7/site-packages/pymc3/sampling.py", line 1486, in _mp_sample
    for draw in sampler:
  File "/home/lab/anaconda3/envs/p/lib/python3.7/site-packages/pymc3/parallel_sampling.py", line 492, in __iter__
    draw = ProcessAdapter.recv_draw(self._active)
  File "/home/lab/anaconda3/envs/p/lib/python3.7/site-packages/pymc3/parallel_sampling.py", line 365, in recv_draw
    raise error from old_error
RuntimeError: Chain 1 failed.

```

## Versions and main components

* PyMC3 Version: 3.9.3 
* Theano Version: 1.0.5
* Python Version: 3.7.9
* Operating system: Ubuntu 16.05
* How did you install PyMC3: (conda/pip) pip install pymc3

**Comment by ckrapu** [comment] 2020-11-18 02:13
From the problem description, it's not clear if the issue is with the model, the data, or the code itself. This type of question is more appropriate for the Discourse site (https://discourse.pymc.io/). Can you post it there? Also, it is very challenging to debug this without your data. I would recommend defining the dataset directly in the script (e.g. call `pd.DataFrame(data=...)`), or use a short snippet of fake data that leads to the same problem.

**Comment by fonnesbeck** [comment] 2020-11-18 15:15
Can you provide a summary of the data in rarecurve.csv? Does it contain missing or negative values? Try the model with some fake data and see if the problem persists.

**Comment by MarcoGorelli** [comment] 2020-12-08 09:30
Closing as this doesn't look like it's a bug in PyMC3 - as suggested above, perhaps ask in discourse for help with specifying the model, but let us know here if you think there's a bug

**Closed as completed by MarcoGorelli** 2020-12-08 09:30 UTC
Labels: needs info
