### ISSUE TITLE
No progress bar when sampling

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/pymc#4090] opened 2020-09-08 17:08 UTC
Same setup and code as [my other issue](https://github.com/pymc-devs/pymc3/issues/4089), except setting `chains=1` to prevent PyMC3 from sampling multiple times, produces the following output, which does not contain a progress bar: 

```
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Sequential sampling (1 chains in 1 job)
NUTS: [x]
Sampling 1 chain for 1_000 tune and 1_000 draw iterations (1_000 + 1_000 draws total) took 1 seconds.
Only one chain was sampled, this makes it impossible to run some convergence checks
```

Overtly setting `progressbar=True` does not fix.

**Comment by fonnesbeck** [comment] 2020-10-04 02:42
Is this in a Jupyter notebook?

**Comment by sammosummo** [comment] 2020-11-17 19:59
Sorry, could have sworn I responded to this. No, this is not in a notebook.

**Comment by fonnesbeck** [comment] 2020-11-18 15:12
So IPython, then or the standard Python REPL? I cannot replicate it here, but I am in Linux. Can you try creating a clean virtual environment (conda or other) and trying there? Also, check to see if you have `fastprogress` installed. It is a requirement that should be installed automatically, but something may have happened on your install.

**Comment by MarcoGorelli** [comment] 2020-11-18 15:25
I couldn't reproduce this either, I tried running
```python
>>> import pymc3 as pm
>>> with pm.Model():
...     pm.Binomial('y', n=10, p=.5)
...     pm.sample(10_000, chains=1)
```
in a Python repl and got a progress bar. Likewise when running it in an IPython REPL

---

(this was on the WSL)

**Comment by katosh** [comment] 2020-11-18 15:30
Since the switch to `fastprogress` I do not get the process bar anymore when I run it as a slurm job. I suspect it is because there is no tty for the process. This may be related.

**Comment by sammosummo** [comment] 2020-11-18 15:34
Ah, I think it's because I was running inside PyCharm. I do see the progress bar in a REPL and when a script is executed from a terminal. It might be helpful to the include the option to reinstate the tqdm progressbar, but perhaps this is too much of an edge case?

**Comment by fonnesbeck** [comment] 2020-11-18 15:41
I don't think we want to support multiple progress bars, no. I would suggest raising the issue with the fastprogress project to see if its a bug on their end.

I will close this for now, but if there is anything you come across that would help us make it work in PyCharm, feel free to reopern (or open a new issue/PR).

**Closed as completed by fonnesbeck** 2020-11-18 15:41 UTC
