### ISSUE TITLE
Getting TypeError: bad operand type for unary -: 'NoneType'

### ISSUE THREAD

**Issue by dorondru** [pymc-devs/pymc#3932] opened 2020-05-23 16:50 UTC
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem
Getting TypeError: bad operand type for unary -: 'NoneType'

**Please provide a minimal, self-contained, and reproducible example.**
```python

from pymc3 import Model, Bernoulli, sample, traceplot, BinaryGibbsMetropolis
from pymc3.math import switch
from matplotlib.pyplot import savefig

Nsamples = 10000

with Model() as sprinkler_model:
    Rain = Bernoulli('Rain', .2)
    pSprinkler = switch( Rain, 0.01, 0.4)
    Sprinkler = Bernoulli('Sprinkler', pSprinkler)
    pWetGrass = switch( Rain,
                        switch( Sprinkler, 0.99, 0.8 ),
                        # need to apply some smoothing:
                        switch( Sprinkler, .9, 1/Nsamples ) )
    WetGrass = Bernoulli('WetGrass', pWetGrass, observed=1 )
    _trace = sample(Nsamples, step=[BinaryGibbsMetropolis([Rain, Sprinkler])], tune=5000, random_seed=124)
    #trace = sample(Nsamples)
    #traceplot(trace)
    savefig('_trace_{}.png'.format(Nsamples))
```

**Please provide the full traceback.**
```python
Traceback (most recent call last):
  File "/Users/dorondru/Documents/NPS/Research/2021/Kurt_sponsor/VerifAI/VerifAI-master/verifai/simulators/car_simulator/examples/lanekeeping_LQR/sprinkler.py", line 22, in <module>
    _trace = sample(Nsamples, step=[BinaryGibbsMetropolis([Rain, Sprinkler])], tune=5000, random_seed=124)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/sampling.py", line 498, in sample
    trace.report._run_convergence_checks(trace, model)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/backends/report.py", line 84, in _run_convergence_checks
    self._ess = ess = ess(trace, var_names=varnames)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/stats/__init__.py", line 24, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/stats/diagnostics.py", line 191, in ess
    dataset = convert_to_dataset(data, group="posterior")
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/converters.py", line 177, in convert_to_dataset
    inference_data = convert_to_inference_data(obj, group=group, coords=coords, dims=dims)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/converters.py", line 91, in convert_to_inference_data
    return from_pymc3(trace=kwargs.pop(group), **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/io_pymc3.py", line 485, in from_pymc3
    save_warmup=save_warmup,
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/io_pymc3.py", line 415, in to_inference_data
    "posterior": self.posterior_to_xarray(),
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/base.py", line 37, in wrapped
    return func(cls, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/io_pymc3.py", line 209, in posterior_to_xarray
    self.trace[-self.ndraws :].get_values(var_name, combine=False, squeeze=False)
TypeError: bad operand type for unary -: 'NoneType'

Process finished with exit code 1
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: latest
* Theano Version: latest
* Python Version: 3.7.7
* Operating system: Mojave, 10.14.6
* How did you install PyMC3: (conda/pip) pip

**Comment by AlexAndorra** [comment] 2020-05-23 17:27
Hi @dorondru, thanks for the report.
I think this is an ArviZ issue, which was just addressed by [this PR](https://github.com/arviz-devs/arviz/pull/1203) by @OriolAbril. We're planning on doing a bugfix release soon.

Can I ask you which version of PyMC3 you mean by "latest" though: is it master or 3.8?

**Comment by dorondru** [comment] 2020-05-23 17:31
Sorry for the stupid question: how do I get the version number?

**Comment by dorondru** [comment] 2020-05-23 17:32
Requirement already satisfied: pymc3 in /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (3.8)

**Comment by OriolAbril** [comment] 2020-05-23 17:33
Have you installed pymc3 with `pip install pymc3` or with `pip install git+https://github.com/pymc-devs/pymc3`? If you used the first option, does running the second command solve the issue?

**Comment by dorondru** [comment] 2020-05-23 17:38
Thanks. I'm trying the second option now; it's taking its time installing...

**Comment by dorondru** [comment] 2020-05-23 17:39
No, it doesn't resolve the issue.

**Comment by dorondru** [comment] 2020-05-23 17:42
A few more details:
The error is when I run from Pycharm.
When I run from command-line I get: ModuleNotFoundError: No module named 'pymc3'

**Comment by OriolAbril** [comment] 2020-05-23 17:43
Humm, interesting. I have just merged the bugfix in ArviZ side, do you mind trying to make sure it does work? Development ArviZ version can be installed with `pip install git+git://github.com/arviz-devs/arviz.git`

**Comment by dorondru** [comment] 2020-05-23 17:46
Yea, I just did that. No difference

**Comment by OriolAbril** [comment] 2020-05-23 17:48
> When I run from command-line I get: ModuleNotFoundError: No module named 'pymc3'

This is probably because the python you are running from the command line is not the same as the one executed by PyCharm, does that make sense? Running `which python` and `python --version` may help with the not being able to import pymc3. That should be unrelated to the issue at hand.

> Yea, I just did that. No difference

Not even using ArviZ development version? :/ `pip install git+git://github.com/arviz-devs/arviz.git`

I'll try to reproduce the issue and come back in some minutes

**Comment by dorondru** [comment] 2020-05-23 17:54
I changes the path so now both point to 3.7.7. In commandline I'm getting the dump:
Traceback (most recent call last):
  File "sprinkler.py", line 7, in <module>
    from pymc3 import Model, Bernoulli, sample, traceplot, BinaryGibbsMetropolis, sampling
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/__init__.py", line 13, in <module>
    from .stats import *
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/stats/__init__.py", line 10, in <module>
    import arviz as az
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/__init__.py", line 28, in <module>
    from .data import *
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/__init__.py", line 2, in <module>
    from .inference_data import InferenceData, concat
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/inference_data.py", line 8, in <module>
    import netCDF4 as nc
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netCDF4/_netCDF4.cpython-37m-darwin.so, 2): Symbol not found: __ZNSt3__118shared_timed_mutex13unlock_sharedEv
  Referenced from: /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
  Expected in: /Users/dorondru/Documents/VariousSoftware/deepdive/lib/dw_mac/libc++.1.dylib
 in /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay

**Comment by dorondru** [comment] 2020-05-23 17:55
True, not even after doing: sudo pip install git+git://github.com/arviz-devs/arviz.git

**Comment by OriolAbril** [comment] 2020-05-23 18:12
I have executed the code above in the following combinations:


| arviz \ pymc3 | 3.8 | master |
|---|---|---|
| 0.8.0 | :x: | :x:  |
| master | :heavy_check_mark: | :heavy_check_mark:   |

It looks like you are running into installation issues. Are you using any virtual environment or conda enviroment?

**Comment by dorondru** [comment] 2020-05-23 18:12
no. Plain MacOS Mojave

**Comment by dorondru** [comment] 2020-05-23 18:13
basically 0.8.0 isn't ok. Is it possible that it is still running even though I installed "sudo pip install git+https://github.com/pymc-devs/pymc3 "?

**Comment by OriolAbril** [comment] 2020-05-23 18:15
I generally do not recommend using sudo with pip and prefer to use the `--user` flag. Maybe `pip install --user git+git://github.com/arviz-devs/arviz.git`?

**Comment by dorondru** [comment] 2020-05-23 18:18
pip install --user git+git://github.com/arviz-devs/arviz.git
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
    module = importlib.import_module(module_path)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand, with_cleanup
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>
    from pip._vendor import html5lib, requests
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/html5lib/__init__.py", line 28, in <module>
    from .serializer import serialize
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/html5lib/serializer.py", line 11, in <module>
    from xml.sax.saxutils import escape
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/saxutils.py", line 6, in <module>
    import os, urllib.parse, urllib.request
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2587, in <module>
    from _scproxy import _get_proxy_settings, _get_proxies
ImportError: dlopen(/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_scproxy.cpython-37m-darwin.so, 2): Symbol not found: __ZNSt3__118shared_timed_mutex13unlock_sharedEv
  Referenced from: /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
  Expected in: /Users/dorondru/Documents/VariousSoftware/deepdive/lib/dw_mac/libc++.1.dylib
 in /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay

**Comment by dorondru** [comment] 2020-05-23 18:19
but with sudo it's ok.

**Comment by OriolAbril** [comment] 2020-05-23 18:24
I don't really understand the error message, so I'm afraid I am unable to help further :confused: Thanks for reporting the issue, let's hope that the bugfix release solves the install issues. It will be available between today and tomorrow. Sorry for the inconvenience

**Comment by dorondru** [comment] 2020-05-23 18:51
pip install --user git+git://github.com/arviz-devs/arviz.git --> OK
pip install --user git+https://github.com/pymc-devs/pymc3 --> OK

python3 sprinkler.py 
Multiprocess sampling (4 chains in 4 jobs)
BinaryGibbsMetropolis: [Rain, Sprinkler]
Sampling 4 chains, 0 divergences: 100%|█| 60000/60000 [00:06<00:00, 9457.75draws
Traceback (most recent call last):
  File "sprinkler.py", line 22, in <module>
    _trace = sample(Nsamples, step=[BinaryGibbsMetropolis([Rain, Sprinkler])], tune=5000, random_seed=124)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/sampling.py", line 498, in sample
    trace.report._run_convergence_checks(trace, model)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/backends/report.py", line 84, in _run_convergence_checks
    self._ess = ess = ess(trace, var_names=varnames)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/stats/__init__.py", line 24, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/stats/diagnostics.py", line 191, in ess
    dataset = convert_to_dataset(data, group="posterior")
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/converters.py", line 177, in convert_to_dataset
    inference_data = convert_to_inference_data(obj, group=group, coords=coords, dims=dims)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/converters.py", line 91, in convert_to_inference_data
    return from_pymc3(trace=kwargs.pop(group), **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/io_pymc3.py", line 485, in from_pymc3
    save_warmup=save_warmup,
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/io_pymc3.py", line 415, in to_inference_data
    "posterior": self.posterior_to_xarray(),
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/base.py", line 37, in wrapped
    return func(cls, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arviz/data/io_pymc3.py", line 209, in posterior_to_xarray
    self.trace[-self.ndraws :].get_values(var_name, combine=False, squeeze=False)
TypeError: bad operand type for unary -: 'NoneType'

**Comment by OriolAbril** [comment] 2020-05-23 19:00
Given that both @AlexAndorra and I have been able to reproduce the issue with ArviZ 0.8.0 and then see that an install of ArviZ development version fixed it, this is most probably due to python not using the correct version (similarly to how initially you got an error about pymc3 not being installed right after installing it). I recommend using some kind of virtual or conda environments to make prevent this kind of issues.

Otherwise, try printing `arviz.__path__` to see if it is the same reported during the installation by pip

**Comment by AlexAndorra** [comment] 2020-05-23 19:57
Agreed, I think it will allow a more principled debugging to do all of this in a virtual environment. Both Oriol and I didn't have this issue when using ArviZ master and PyMC 3.8 / master on our env.

I'd advise [using conda](https://towardsdatascience.com/getting-started-with-python-environments-using-conda-32e9f2779307), as it usually pulls in all the necessary C compiled libraries that theano (and hence PyMC3) needs to work.
If you don't want to use anaconda for some reason, [here is a tutorial](https://realpython.com/python-virtual-environments-a-primer/#using-virtual-environments) to create and manage virtual environements with pip.

Hope this helps 🖖

**Comment by lucianopaz** [comment] 2020-05-23 19:57
@dorondru, the problem is that you are not actually installing the arviz version that is on GitHub. The reason this is happening is because the running version of the arviz package that pip is downloading from GitHub is still numbered as 0.8.0. So after downloading the files from GitHub, pip sees that the version of the package it downloaded is the same version as the package it already had installed and concludes that it doesn't have to do anything else.

There are a couple of ways to force pip to really install whatever version it finds on GitHub. I think that the most straightforward is to do: `pip install --force-reinstall git+git://github.com/arviz-devs/arviz.git`

Could you try that and see if the issue is fixed?

**Comment by dorondru** [comment] 2020-05-23 20:22
Thanks! I'll try ASAP

**Comment by truEngineer** [comment] 2020-05-23 21:42
I have the same problem

`pymc3` + `arviz` convergence checks is broken now

<details>
  <summary>error log</summary>
  
  ```python
/usr/local/lib/python3.6/dist-packages/pymc3/sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, **kwargs)
    496             warnings.warn("The number of samples is too small to check convergence reliably.")
    497         else:
--> 498             trace.report._run_convergence_checks(trace, model)
    499 
    500     trace.report._log_summary()

/usr/local/lib/python3.6/dist-packages/pymc3/backends/report.py in _run_convergence_checks(self, trace, model)
     82                 varnames.append(rv_name)
     83 
---> 84         self._ess = ess = ess(trace, var_names=varnames)
     85         self._rhat = rhat = rhat(trace, var_names=varnames)
     86 

/usr/local/lib/python3.6/dist-packages/pymc3/stats/__init__.py in wrapped(*args, **kwargs)
     22                 )
     23                 kwargs[new] = kwargs.pop(old)
---> 24             return func(*args, **kwargs)
     25 
     26     return wrapped

/usr/local/lib/python3.6/dist-packages/arviz/stats/diagnostics.py in ess(data, var_names, method, relative, prob)
    189             raise TypeError(msg)
    190 
--> 191     dataset = convert_to_dataset(data, group="posterior")
    192     var_names = _var_names(var_names, dataset)
    193 

/usr/local/lib/python3.6/dist-packages/arviz/data/converters.py in convert_to_dataset(obj, group, coords, dims)
    175     xarray.Dataset
    176     """
--> 177     inference_data = convert_to_inference_data(obj, group=group, coords=coords, dims=dims)
    178     dataset = getattr(inference_data, group, None)
    179     if dataset is None:

/usr/local/lib/python3.6/dist-packages/arviz/data/converters.py in convert_to_inference_data(obj, group, coords, dims, **kwargs)
     89             return from_pystan(**kwargs)
     90     elif obj.__class__.__name__ == "MultiTrace":  # ugly, but doesn't make PyMC3 a requirement
---> 91         return from_pymc3(trace=kwargs.pop(group), **kwargs)
     92     elif obj.__class__.__name__ == "EnsembleSampler":  # ugly, but doesn't make emcee a requirement
     93         return from_emcee(sampler=kwargs.pop(group), **kwargs)

/usr/local/lib/python3.6/dist-packages/arviz/data/io_pymc3.py in from_pymc3(trace, prior, posterior_predictive, log_likelihood, coords, dims, model, save_warmup)
    483         dims=dims,
    484         model=model,
--> 485         save_warmup=save_warmup,
    486     ).to_inference_data()
    487 

/usr/local/lib/python3.6/dist-packages/arviz/data/io_pymc3.py in to_inference_data(self)
    413         """
    414         id_dict = {
--> 415             "posterior": self.posterior_to_xarray(),
    416             "sample_stats": self.sample_stats_to_xarray(),
    417             "log_likelihood": self.log_likelihood_to_xarray(),

/usr/local/lib/python3.6/dist-packages/arviz/data/base.py in wrapped(cls, *args, **kwargs)
     35                 if all([getattr(cls, prop_i) is None for prop_i in prop]):
     36                     return None
---> 37             return func(cls, *args, **kwargs)
     38 
     39         return wrapped

/usr/local/lib/python3.6/dist-packages/arviz/data/io_pymc3.py in posterior_to_xarray(self)
    207                 )
    208             data[var_name] = np.array(
--> 209                 self.trace[-self.ndraws :].get_values(var_name, combine=False, squeeze=False)
    210             )
    211         return (

TypeError: bad operand type for unary -: 'NoneType'
  ```
</details>

**To Reproduce**

Create google Colab notebook and install `pymc3`+`arviz`

```
!pip install arviz
!pip install pymc3==3.8
```
 
Start sampling for any model.

```python
trace = pm.sample(model=model, tune=500, draws=500, init='advi+adapt_diag')
```

**Additional context**

Python 3.6 Colab notebook

arviz Version: 0.8.0

pymc3 Version: 3.8

**Comment by dorondru** [comment] 2020-05-23 21:56
I worked! Thanks!

**Comment by lucianopaz** [comment] 2020-05-23 22:21
@truEngineer, you have to upgrade arviz to use the development version that is hosted on GitHub. That seems to have solved the problem for @dorondru.

**Closed as completed by lucianopaz** 2020-05-23 22:21 UTC
