### ISSUE TITLE
PyMC3 import sets theano.config.compute_test_value to 'raise'

### ISSUE THREAD

**Issue by abergeron** [pymc-devs/pymc#1514] opened 2016-11-08 19:45 UTC
The main problem is that once you compile a single graph with a PyMC3 op, it is added to the cache and any other Theano code that you run will have this setting and will most likely crash.

**Comment by fonnesbeck** [comment] 2016-11-08 23:12
This is a duplicate of #566 

This is definitely something we need to discuss and resolve.

**Closed as completed by fonnesbeck** 2016-11-08 23:12 UTC
