### ISSUE TITLE
KDE plot failed

### ISSUE THREAD

**Issue by jtamagnan** [pymc-devs/pymc#1072] opened 2016-04-13 22:04 UTC
I was trying to create what I though was a fairly simple model but I got interesting, and disappointing results.

The goal of the model is to fit a parameter `c_to_h` which is the percentage of people who are colonized with a disease who end up in the hospital because of that disease. There are 20 different strains of the disease (`N` in the model), and therefore 20 groups of colonized people, 20 groups of hospitalized people and 20 values of `c_to_h`.  The code of the model appears below

``` python
import pymc3 as pm
import numpy as np
import seaborn p
import matplotlib.pyplot as plt

N = 20
hospitalized_array = np.array([100] * N)
colonized_array = np.array([500] * N)

basic_model = pm.Model()
with basic_model:
    colonized = pm.Dirichlet(name="colonized", a=colonized_array, shape=N)
    c_to_h = pm.Uniform(name="c_to_h", lower=0, upper=1, shape=N)
    model_h = colonized * c_to_h

    hospitalized = pm.Dirichlet(name="hospitalized", a=model_h, observed=hospitalized_array, shape=N)

    trace = pm.sample(10000)

    pm.traceplot(trace)
    plt.show() # graph won't show otherwise
    pm.summary(trace)
```

When I run the code there is no error. The error occurs only in the figure and in the nonsensical summary. The figure appears below.

![figure_1-1](https://cloud.githubusercontent.com/assets/5892061/14510591/33381cf8-01a0-11e6-8266-95f4186500ac.png)

The output for the summary of `c_to_h` appears bellow

```
c_to_h:

  Mean             SD               MC Error         95% HPD interval
  -------------------------------------------------------------------

  0.500            0.000            0.000            [0.500, 0.500]
.
.
.
  0.500            0.000            0.000            [0.500, 0.500]

  Posterior quantiles:
  2.5            25             50             75             97.5
  |--------------|==============|==============|--------------|

  0.500          0.500          0.500          0.500          0.500
.
.
.
  0.500          0.500          0.500          0.500          0.500
```

It would make for sense for the mean to be at .2

Why would this be happening? What does KDE have to do with this?

**Comment by twiecki** [comment] 2016-04-14 10:42
Your model is stuck at the point where you initialize it, no jumps are accepted. I assume model misspecification is the cause, the KDE is just a symptom. I'm closing this as it's not a pymc3 issue per se but feel free to continue to post with questions on your model.

**Closed as completed by twiecki** 2016-04-14 10:42 UTC

**Comment by jtamagnan** [comment] 2016-04-15 18:03
Thank you for your help. After working on the model a bit more I realized that what went wrong. Now my only question is about sampling from a dirichlet and not having it be fit. In pymc2 it was possible to take a diriclet and make it into a "CompleteDirichlet" is there a way to do this. I tried to accomplish this by having 
`pm.Dirichlet(name="colonized", a=colonized_array + 1, observed=colonized_array / colonized_array.sum(), shape=N + 1)`
This does not appear in the trace but I do not know if it appears or not in the loglikelihood that is being fit. 
Also is there a way to view the loglikelihood in the trace?

**Comment by twiecki** [comment] 2016-04-15 19:42
Do you want it unnormalized? You can pass `transform=None`.

**Comment by jtamagnan** [comment] 2016-04-15 19:48
What exactly does unnormalized mean? I was wondering the same thing as related to a uniform. Once again thank you

**Comment by fonnesbeck** [comment] 2016-04-17 04:36
Unnormalized means that it is plotting frequency rather than probability.
