### ISSUE TITLE
Consistently use param: type in docstrings

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4284] opened 2020-12-02 17:30 UTC
The docstring of `sample` (from `pymc3.sampling`) is written as `param : type`:
```python
    draws : int
        The number of samples to draw. Defaults to 1000. The number of tuned samples are discarded
        by default. See ``discard_tuned_samples``.
```
and in the docs this shows up as

![image](https://user-images.githubusercontent.com/33491632/100908407-60aab780-34c3-11eb-8a37-b239af51af96.png)

which, given the PyMC3 docs configurations, doesn't look great.

On the other hand, `fast_sample_posterior_predictive` is written as `param: type`:
```python
    trace: MultiTrace, xarray.Dataset, InferenceData, or List of points (dictionary)
        Trace generated from MCMC sampling.
```

In the docs this shows up as

![image](https://user-images.githubusercontent.com/33491632/100908722-baab7d00-34c3-11eb-841d-b28aba624800.png)

which, given the PyMC3 docs configurations, looks better.

---

Possible fixes here would be:

- change the docs configs so that `param : type` looks better and then apply that consistently
- apply `param: type` consistently

I'd be more inclined towards the latter

UPDATE
------

Please wait before making a big PR for this, we may be able to resolve the custom sphinx theme

**Comment by michaelosthege** [comment] 2021-06-28 21:26
The [numpydoc style guide](https://numpydoc.readthedocs.io/en/latest/format.html#parameters) is very clear about the spaces:

> The colon must be preceded by a space, or omitted if the type is absent.

Not sure if the bug was fixed in the meantime, @OriolAbril ?

It would be great to add a numpydoc style checker to the pre-commit...

**Comment by Sayam753** [comment] 2021-07-03 19:53
> Not sure if the bug was fixed in the meantime, @OriolAbril ?

On v3 docs, the issue is still there. Checkout the function docstring rendering [here](https://pymc3-fork.readthedocs.io/en/v3_rtd_docs/api/inference.html#pymc3.sampling.sample)

> It would be great to add a numpydoc style checker to the pre-commit...

+1. We can use this http://www.pydocstyle.org/en/4.0.0/usage.html#usage-with-the-pre-commit-git-hooks-framework

I just ran pydocstyle check locally at v3 branch
```bash
$ pydocstyle --convention=numpy . | wc -l
    3122
```
So, there are > 1500 docstring warnings 😭

**Comment by OriolAbril** [comment] 2021-07-27 03:37
As @Sayam753 says, this is a combination of not following numpydoc on all the docstrings in the codebase plus a bug in the v3 theme (which is now fixed). I think we should follow numpydoc and like the lint check on it for v4 and I would therefore keep this open.

**Comment by mjhajharia** [comment] 2022-01-26 09:28
this would be an easy thing to do with docs, let’s try to find a couple of numpy docstring violations and create some smaller issues. 

cc: @OriolAbril

**Comment by OriolAbril** [comment] 2022-01-26 09:38
this is already part of https://pymc-data-umbrella--13.org.readthedocs.build/en/13/webinars/contributing_to_documentation/docstring_tutorial.html. I think creating smaller issues for this will be more work than anything. I was planning on a single issue where we'd checkmark those following numpydoc (which I didn't realize before but is the exact opposite, we should use `param : type`). If you can create the issue it would be great. https://github.com/scikit-learn/scikit-learn/issues/21350 is a bit similar to this

**Comment by OriolAbril** [comment] 2022-02-10 21:00
Closing this in favour of https://github.com/pymc-devs/pymc/issues/5459 which covers more changes and is more clear.

**Closed as completed by OriolAbril** 2022-02-10 21:00 UTC
Labels: docs, beginner friendly
