### ISSUE TITLE
`pm.set_data` does not affect posterior predictive shape when `pm.Deterministic` is used

### ISSUE THREAD

**Issue by paw-lu** [pymc-devs/pymc#5512] opened 2022-02-22 02:52 UTC
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**

First making a basic example demonstrating the expected result. I have a model, I make a change to the data using `pm.set_data`, and I expect the posterior predictive to reflect that change. Here I simply change the shape of the data from 100 to 3, and check that the shape of the posterior predictive matches. Everything works as expected.

```pycon
>>> import numpy as np
>>> import pymc as pm
>>> 
>>> raw_data = np.random.default_rng().normal(loc=30, size=100)
>>> fit_data = raw_data + 2
>>> with pm.Model(coords={"index": list(range(raw_data.shape[0]))}) as >>> model:
>>>     alpha = pm.Normal("alpha", mu=0, sd=1)
>>>     shared_data = pm.MutableData("shared_data", value=raw_data)
>>>     pm.Normal("normal", mu=alpha + shared_data, observed=fit_data)
>>> 
>>>     idata = pm.sample(return_inferencedata=True)
>>>     pm.set_data({"shared_data": [1.0, 2.0, 1.0]})
>>>     pp_idata = pm.sample_posterior_predictive(idata, predictions=True)
>>> 
>>> pp_idata["predictions"]["normal"].shape
(4, 1000, 3)
```

Now, I run almost the exact same snippet as above, _except_ I wrap `alpha + shared_data` in `pm.Deterministic`. The rest is identical. Now, when I check the posterior predictive, the values no longer seem to be affected by `pm.set_data`, and the shape is still 100.

```pycon
>>> import numpy as np
>>> import pymc as pm
>>> 
>>> raw_data = np.random.default_rng().normal(loc=30, size=100)
>>> fit_data = raw_data + 2
>>> with pm.Model(coords={"index": list(range(raw_data.shape[0]))}) as model:
>>>     alpha = pm.Normal("alpha", mu=0, sd=1)
>>>     shared_data = pm.MutableData("shared_data", value=raw_data)
>>>     mu = pm.Deterministic("mu", alpha + shared_data)  # New line!
>>>     pm.Normal("normal", mu=mu, observed=fit_data)
>>> 
>>>     idata = pm.sample(return_inferencedata=True)
>>>     pm.set_data({"shared_data": [1.0, 2.0, 1.0]})
>>>     pp_idata = pm.sample_posterior_predictive(idata, predictions=True)
>>> 
>>> pp_idata["predictions"]["normal"].shape
(4, 1000, 100)
```

## Versions and main components

* PyMC/PyMC3 Version: 4.0.0b2 installed directly from source (24f9bd48f528b3ea7ace1d95dece01d26b8882e3)
* Aesara/Theano Version: 2.3.8
* Python Version: 3.9.5
* Operating system: macOS
* How did you install PyMC/PyMC3: pip directly from main branch (24f9bd48f528b3ea7ace1d95dece01d26b8882e3)

**Comment by ricardoV94** [comment] 2022-02-22 05:24
duplicate of #5302

**Closed as completed** 2022-02-22 05:25 UTC

**Comment by paw-lu** [comment] 2022-02-22 05:39
ah didn't see that one!
thanks for linking the issue!
