### ISSUE TITLE
Parallel sampling on macOS slower by default

### ISSUE THREAD

**Issue by dfm** [pymc-devs/pymc#4754] opened 2021-06-07 21:08 UTC
## Description of your problem

Related problems have come up previously, but I couldn't find exactly the same issue. I continue to have trouble with the default forced `mp_ctx="forkserver"` in `sample` on macOS. I find that parallel sampling is significantly *slower* than serial sampling with the default settings and that setting `mp_ctx=mp.get_context("fork")` fixes this. For example, in the following simple example (executed in a Jupyter notebook or wrapped in a `if __name__ == "__main__"` in a script):

```python
import pymc3 as pm
import multiprocessing as mp

with pm.Model():
    pm.Normal("x", shape=50)
    trace1 = pm.sample(tune=5000, draws=5000, cores=1, chains=2)
    trace2 = pm.sample(tune=5000, draws=5000, cores=2, chains=2)
    trace3 = pm.sample(tune=5000, draws=5000, cores=2, chains=2, mp_ctx=mp.get_context("fork"))
```

I find that the samplings take `17`, `27`, and `10` seconds respectively. The specific numbers vary somewhat but the overall trend seems pretty consistent and I find that these issues seem to be worse for higher dimensional/more computationally expensive models. I'm a little at a loss for what would be causing this behavior and I deal with it by just manually setting `mp_ctx`, but I thought it would be worth reporting here in case folks had some clever ideas.

## Versions and main components

* PyMC3 Version: 3.11.2
* Aesara/Theano Version: Theano-pymc 1.1.2
* Python Version: 3.9.4
* Operating system: macOS 10.15.7
* How did you install PyMC3: (conda/pip) pip

**Comment by ArturoBell** [comment] 2021-06-11 21:43
I'm facing a similar issue with a slow sampling on my Mac. I tried your workaround with a bivariate hierarchical model and, unfortunately, I didn't see a speed up.

I checked the CPU usage and what I found is that, apparently, both configurations use all cores for each chain (CPU history on the activity monitor, CPU Usage: ~450% per chain). My guess is that it chokes the machine to some extent when cores > 1 (it then activates virtual cores).

Setting `mp_ctx=mp.get_context("fork")` still activated all cores (including virtual). The times with each configuration (advi+adapt_diag initiation, 3 chains, tune = 25000, draws = 1000) are:

- default, serial: ~ 190s per chain (~ 584 s)
- default, parallel: ~ 308 s
- modified, serial: ~ 180s per chain (~ 540 s)
- modified, parallel: ~ 301 s

Reference time (parallel): 164s, Azure Linux Server, 8 cores @ 3.4 GHz (max. single core: 3.7 GHz).

I'm guessing it has something to do with the interaction of Theano and the BLAS implementation in macOS. Clock speeds were similar to the server specs, hovering around 3.5-3.6 GHz, although it usually hits > 4 GHz in other multicore tasks.

I [tested BLAS](https://theano-pymc.readthedocs.io/en/latest/troubleshooting.html#why-is-my-code-so-slow-uses-so-much-memory) on both machines with:
'python3 \`python3 -c "import os, theano; print(os.path.dirname(theano.\_\_file\_\_))"\`/misc/check_blas.py`

and got 48.5s on CPU (with direct Theano binding to blas) on my machine vs. ~ 7 s on the server (same).


## Versions and main components:
- OS: macOS 11.4
- PyMC3: v.3.11.2
- Theano-pymc: v.1.1.2
- Python 3.8.6:
- Installation: pip
- CPU: Intel core i9, 8 cores

**Comment by tobiasraabe** [comment] 2021-06-22 11:52
I am not sure it is related, but I observe "similar" problems like slower sampling on Linux (WSL2 and native Ubuntu) when using multiple cores which is not related to any `mp_context`.

In my case, if my model grows more complex and I sample multiple chains, sampling will not start. The progress bar will be initialized, but, then, the process will freeze without raising any errors. Sampling serially works.

What I did to sample in parallel was restricting the number of threads blas could use with [``threadpoolctl``](https://github.com/joblib/threadpoolctl) to 1. Thus, I assume there might be a problem with oversubscription which could also explain your problems with slower sampling. Setting it to 2 will cause a freeze.

Even if I sample one chain with one core, sampling is faster while simultaenously restricting the number of threads to 1. Do you see high cpu usage which might be caused by oversubscription as well?

#### Versions and main components

- OS: Ubuntu 20.04
- PyMC3: 3.11.2
- theano-pymc: 1.1.2
- python: 3.9.5
- Installation: conda
- CPU: i5 4 cores (8 logical)

**Comment by ArturoBell** [comment] 2021-06-24 22:13
> I am not sure it is related, but I observe "similar" problems like slower sampling on Linux (WSL2 and native Ubuntu) when using multiple cores which is not related to any `mp_context`.
> 
> In my case, if my model grows more complex and I sample multiple chains, sampling will not start. The progress bar will be initialized, but, then, the process will freeze without raising any errors. Sampling serially works.
> 
> What I did to sample in parallel was restricting the number of threads blas could use with [`threadpoolctl`](https://github.com/joblib/threadpoolctl) to 1. Thus, I assume there might be a problem with oversubscription which could also explain your problems with slower sampling. Setting it to 2 will cause a freeze.
> 
> Even if I sample one chain with one core, sampling is faster while simultaenously restricting the number of threads to 1. Do you see high cpu usage which might be caused by oversubscription as well?
> 
> #### Versions and main components
> * OS: Ubuntu 20.04
> * PyMC3: 3.11.2
> * theano-pymc: 1.1.2
> * python: 3.9.5
> * Installation: conda
> * CPU: i5 4 cores (8 logical)

I do think that is the problem. My global CPU usage with serial sampling is ~50% (It uses every physical core), while with parallel sampling it goes up to ~90% (meaning it also uses logical cores). As soon as I have a chance I'll check your suggestion and report my findings.

**Comment by ArturoBell** [comment] 2021-07-19 23:04
> I am not sure it is related, but I observe "similar" problems like slower sampling on Linux (WSL2 and native Ubuntu) when using multiple cores which is not related to any `mp_context`.
> 
> In my case, if my model grows more complex and I sample multiple chains, sampling will not start. The progress bar will be initialized, but, then, the process will freeze without raising any errors. Sampling serially works.
> 
> What I did to sample in parallel was restricting the number of threads blas could use with [`threadpoolctl`](https://github.com/joblib/threadpoolctl) to 1. Thus, I assume there might be a problem with oversubscription which could also explain your problems with slower sampling. Setting it to 2 will cause a freeze.
> 
> Even if I sample one chain with one core, sampling is faster while simultaenously restricting the number of threads to 1. Do you see high cpu usage which might be caused by oversubscription as well?
> 
> #### Versions and main components
> * OS: Ubuntu 20.04
> * PyMC3: 3.11.2
> * theano-pymc: 1.1.2
> * python: 3.9.5
> * Installation: conda
> * CPU: i5 4 cores (8 logical)

Sorry for the late response. I couldn't make it work with threadpoolctl (perhaps I did it wrong?). What did work was setting `%env OMP_NUM_THREADS = 1` before starting the sampling. With that setting my original time was basically halved when doing parallel sampling. I do not know if that may affect the performance elsewhere, though.

**Comment by fonnesbeck** [comment] 2024-06-16 22:23
This is a very old performance issue, so will close.

**Closed as completed by fonnesbeck** 2024-06-16 22:23 UTC
