### ISSUE TITLE
Input dimension mis-match with GP

### ISSUE THREAD

**Issue by Joshuaalbert** [pymc-devs/pymc#2830] opened 2018-02-01 20:56 UTC
I'm coming from GP tools like gpy, gpflow, self-written stuff and am fairly fluent with gps.
I'm trying to get pymc3 running with GPs because it looks really cool and useful, but am running into significant roadblocks. It seems I must be totally misunderstanding something here. 
I'm attempting to follow http://docs.pymc.io/notebooks/GP-Marginal.html#Making-predictions
Has there been an api change that is not documented?

Running the below gives:
```
ValueError: Input dimension mis-match. (input[0].shape[1] = 200, input[1].shape[1] = 100)
```
## MVCE

```
import numpy as np
import pylab as plt
import pymc3 as pm

X = np.linspace(0, 10, 100)[:,None]
y = X**(0.5) + np.exp(-X/5)*np.sin(10*X)
y += 0.1*np.random.normal(size=y.shape)
plt.scatter(X,y)
plt.show()

Xnew = np.linspace(0, 10, 200)[:,None]
with pm.Model() as model:
    cov_func = pm.gp.cov.ExpQuad(1, ls=1/20.)
    gp = pm.gp.Marginal(cov_func=cov_func)
    f = gp.marginal_likelihood('f',X,y,0.1)
    f_star = gp.conditional('fstar',Xnew)
```

## traceback
https://gist.github.com/Joshuaalbert/ab8619c745667da3552c865280d7362c

## Versions and main components

* PyMC3 Version: 3.3rc2
* Theano Version: 1.0.1
* Python Version: 3.6
* Operating system: Fedora 25 64 Bit
* How did you install PyMC3: (conda/pip)
git clone & python setup.py install

**Comment by junpenglao** [comment] 2018-02-01 21:27
you need to change 
`f = gp.marginal_likelihood('f', X, y, 0.1)`
to
`f = gp.marginal_likelihood('f', X, y.squeeze(), 0.1)`

(This part of the doc is not very clear at times... Sorry about the confusion)
I will close this since it is not a bug - if you have further question please post it to https://discourse.pymc.io/

**Closed as completed by junpenglao** 2018-02-01 21:27 UTC

**Comment by mfouesneau** [comment] 2021-01-18 17:53
Please pin this comment somewhere in the documentation, I spent a while trying to solve this issue before I found this comment.
