### ISSUE TITLE
static type checks take a long time, remove from pre-commit

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#5945] opened 2022-07-03 16:25 UTC
pre-commit is awefully slow because of the static type checks. I think we should remove them from pre-commit.

**Comment by michaelosthege** [comment] 2022-07-03 17:32
Duplicate of #5907 

Over there I proposed to split mypy into a separate job so it runs in CI, but not locally.

**Closed as not planned by michaelosthege** 2022-07-03 17:32 UTC
