### ISSUE TITLE
 RecursionError: when working through PyMC3 tutorial

### ISSUE THREAD

**Issue by jbwhit** [pymc-devs/pymc#893] opened 2015-12-16 23:22 UTC
Working through the Case study 1 example here: https://pymc-devs.github.io/pymc3/getting_started/ 

I have a Jupyter Notebook in this gist that shows the error in context: https://gist.github.com/jbwhit/0be25027ed303a0aea89

Which I will paste here:

```
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-38-08c8b518c57a> in <module>()
      8     # Start next run at the last sampled position.
      9     step = NUTS(scaling=trace[-1], gamma=.25)
---> 10     trace = sample(2000, step, start=trace[-1], progressbar=True, njobs=4)

/Users/jonathan/miniconda2/envs/pm3/lib/python3.5/site-packages/pymc3/sampling.py in sample(draws, step, start, trace, chain, njobs, tune, progressbar, model, random_seed)
    153         sample_args = [draws, step, start, trace, chain,
    154                        tune, progressbar, model, random_seed]
--> 155     return sample_func(*sample_args)
    156 
    157 

/Users/jonathan/miniconda2/envs/pm3/lib/python3.5/site-packages/pymc3/sampling.py in _mp_sample(njobs, args)
    274 def _mp_sample(njobs, args):
    275     p = mp.Pool(njobs)
--> 276     traces = p.map(argsample, args)
    277     p.close()
    278     return merge_traces(traces)

/Users/jonathan/miniconda2/envs/pm3/lib/python3.5/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    258         in a list that is returned.
    259         '''
--> 260         return self._map_async(func, iterable, mapstar, chunksize).get()
    261 
    262     def starmap(self, func, iterable, chunksize=None):

/Users/jonathan/miniconda2/envs/pm3/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    606             return self._value
    607         else:
--> 608             raise self._value
    609 
    610     def _set(self, i, obj):

/Users/jonathan/miniconda2/envs/pm3/lib/python3.5/multiprocessing/pool.py in _handle_tasks(taskqueue, put, outqueue, pool, cache)
    383                         break
    384                     try:
--> 385                         put(task)
    386                     except Exception as e:
    387                         job, ind = task[:2]

/Users/jonathan/miniconda2/envs/pm3/lib/python3.5/multiprocessing/connection.py in send(self, obj)
    204         self._check_closed()
    205         self._check_writable()
--> 206         self._send_bytes(ForkingPickler.dumps(obj))
    207 
    208     def recv_bytes(self, maxlength=None):

/Users/jonathan/miniconda2/envs/pm3/lib/python3.5/multiprocessing/reduction.py in dumps(cls, obj, protocol)
     48     def dumps(cls, obj, protocol=None):
     49         buf = io.BytesIO()
---> 50         cls(buf, protocol).dump(obj)
     51         return buf.getbuffer()
     52 

RecursionError: maximum recursion depth exceeded while pickling an object
```

I'm not seeing what is being pickled or why there would be recursion going on. The trace and step work in the lines above the error: 

```
step = NUTS(scaling=start)
trace = sample(100, step, progressbar=True)
```

So it's not breaking on that in principle, either. Any ideas?

**Comment by jbwhit** [comment] 2015-12-16 23:29
It appears that it's breaking on the njobs line.

**Comment by jbwhit** [comment] 2015-12-16 23:32
I guess there's a problem with njobs, and I don't know where it's failing. If I set njobs= anything other than 1, -1, it breaks with the same error.

**Comment by fonnesbeck** [comment] 2015-12-17 01:53
This is a duplicate of #879

**Closed as completed by fonnesbeck** 2015-12-17 01:53 UTC
