### ISSUE TITLE
Multinomial softmax error: ValueError: object too deep for desired array

### ISSUE THREAD

**Issue by Rachnog** [pymc-devs/pymc#2507] opened 2017-08-16 17:48 UTC
Hi to all,

I am trying to do multinomial classification on example of classical iris dataset.
Here is how I define the model (simply copied MLP from one of tutorials)

```
def make_nn(ann_input, ann_output, n_hidden):
    init_1 = np.random.randn(ann_input.shape[1], n_hidden)
    init_2 = np.random.randn(n_hidden, n_hidden)
    init_out = np.random.randn(n_hidden, ann_output.shape[1])
    
    with pm.Model() as nn_model:
        weights_1 = pm.Normal('w_1', mu=0, sd=1, 
                              shape=(ann_input.shape[1], n_hidden),
                              testval=init_1)
        weights_2 = pm.Normal('w_2', mu=0, sd=1,
                              shape=(n_hidden, n_hidden),
                              testval=init_2)
        weights_out = pm.Normal('w_out', mu=0, sd=1, 
                                shape=(n_hidden, ann_output.shape[1]),
                                testval=init_out)

        acts_1 = pm.Deterministic('activations_1', 
                                  tt.tanh(tt.dot(ann_input, weights_1)))
        acts_2 = pm.Deterministic('activations_2', 
                                  tt.tanh(tt.dot(acts_1, weights_2)))
        acts_out = pm.Deterministic('activations_out', 
                                    tt.nnet.softmax(tt.dot(acts_2, weights_out)))  # noqa
        Define likelihood
        out = pm.Multinomial('likelihood', n=1, p=acts_out, 
                             observed=ann_output)
    return nn_model
```

I am loading Iris dataset like this:
```
iris = datasets.load_iris()
X = iris.data
y = iris.target

enc = LabelEncoder()
enc.fit(y)
y = enc.transform(y) 
y = np_utils.to_categorical(y)

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.33, random_state=42)
n_hidden = 10
```

And this is the way I am trying to train the model:

```
model = make_nn(X_train, Y_train, n_hidden=n_hidden)
with model:
    trace = pm.sample(500, start=pm.find_MAP(), step=pm.Metropolis())

with model:
    samp_ppc = pm.sample_ppc(trace, samples=50)
```

And in the end I get the error in sampling:

```
Traceback (most recent call last):
  File "bb2.py", line 98, in <module>
    samp_ppc = pm.sample_ppc(trace, samples=50)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/sampling.py", line 539, in sample_ppc
    vals = var.distribution.random(point=param, size=size)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/distributions/multivariate.py", line 506, in random
    size=size)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/distributions/distribution.py", line 397, in generate_samples
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/distributions/distribution.py", line 322, in replicate_samples
    samples = generator(size=size, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/distributions/multivariate.py", line 500, in _random
    return np.random.multinomial(n, p, size=size)
  File "mtrand.pyx", line 4613, in mtrand.RandomState.multinomial (numpy/random/mtrand/mtrand.c:37731)
ValueError: object too deep for desired array
```

I googled it, but as far I see, there is no direct solution for this problem (it depends on NumPy). Could someone run any multiclass classification model in PyMC3? Or maybe could use pm.Categorical() instead of Multinomial?

Thanks in advance for any help, snippet of working code would be amazing!

**Comment by junpenglao** [comment] 2017-08-16 17:55
Looks like a Metropolis error, could you please try sampling with the default?
```python
with model:
    trace = pm.sample(1000, njobs=4)
```

**Comment by junpenglao** [comment] 2017-08-16 18:30
Oh sorry I misread -> the problem is the residual issues of multinomial random https://github.com/pymc-devs/pymc3/pull/2432 I think.

**Comment by junpenglao** [comment] 2017-08-16 18:34
Since you are using `n=1` in the Multinomial, could you try Categorical distribution instead?

**Comment by junpenglao** [comment] 2017-09-18 04:17
fixed in https://github.com/pymc-devs/pymc3/pull/2555

**Closed as completed by junpenglao** 2017-09-18 04:17 UTC
