### ISSUE TITLE
Running Weibull Model causes local runtime to crash

### ISSUE THREAD

**Issue by cmp1** [pymc-devs/pymc#4201] opened 2020-10-29 11:35 UTC
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem
When I attempt to fit a Weibull distribution to observed data, it causes my local runtime to crash. I am unsure if this is due to how some of the parameters have been defined?

Any guidance gratefully received! Thank you.

**Please provide a minimal, self-contained, and reproducible example.**
```python
#@title EOM Prod. Bayesian Posterior Inference Model, Students T
N_SAMPLES = 8000
with pm.Model() as eom_prod_model:
    # Priors for unknown model parameters
    alpha_mu = 1.0 / y.mean()
    alpha_std = 1.0 / y.std()
    
    # Define parameter priors
    mu = pm.Exponential('Mu', alpha_mu)
    sigma = pm.Exponential('Sigma', alpha_std)
        
    alpha_raw = pm.Normal("a0", mu=0, sigma=0.1)
    alpha = pm.Deterministic("alpha", tt.exp(alpha_std * alpha_raw))
    beta = pm.Deterministic("beta", tt.exp(mu / alpha))

    eom_production = pm.Weibull("y_obs", alpha=alpha, beta=beta, observed=y)
    eom_prod_trace = pm.sample(N_SAMPLES, tune=2000)
    posterior_predictive = pm.sample_posterior_predictive(eom_prod_trace)
```

**Please provide the full traceback.**
```python
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFF01703B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFF83DA9D93  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFF85A27034  Unknown               Unknown  Unknown
ntdll.dll          00007FFF8641CEC1  Unknown               Unknown  Unknown
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFF01703B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFF83DA9D93  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFF85A27034  Unknown               Unknown  Unknown
ntdll.dll          00007FFF8641CEC1  Unknown               Unknown  Unknown
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFF01703B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFF83DA9D93  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFF85A27034  Unknown               Unknown  Unknown
ntdll.dll          00007FFF8641CEC1  Unknown               Unknown  Unknown
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFF01703B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFF83DA9D93  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFF85A27034  Unknown               Unknown  Unknown
ntdll.dll          00007FFF8641CEC1  Unknown               Unknown  Unknown
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFF01703B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFF83DA9D93  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFF85A27034  Unknown               Unknown  Unknown
ntdll.dll          00007FFF8641CEC1  Unknown               Unknown  Unknown
[I 11:29:41.215 NotebookApp] Interrupted...
[I 11:29:41.221 NotebookApp] Shutting down 1 kernel
[I 11:29:41.336 NotebookApp] Kernel shutdown: f4b87953-ea70-44fe-86a9-717872d6dcbd
[I 11:29:41.338 NotebookApp] Shutting down 0 terminals
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:  3.9.3
* Theano Version: 1.0.5
* Python Version: 3.8
* Operating system: Windows 10
* How did you install PyMC3: (conda/pip) conda-forge

**Comment by cmp1** [comment] 2020-11-10 08:04
Hi, just wondering whether I could please get some help here? I am still unsure of what is causing this. Thank you, much appreciated.

**Comment by AlexAndorra** [comment] 2020-11-10 11:17
Hi,
Looks like you're on Windows, so can you try without multiprocessing: `pm.sample(N_SAMPLES, tune=2000, cores=1)`?

**Comment by cmp1** [comment] 2020-11-10 13:41
Hi Alexandre,

Many thanks for your reply - this worked! Why specifically does this fail
with Windows? is this a Global Interpreter Lock issue?

I also have a separate question as another error has come up in the same
execution when attempting to use pm.fast_sample_posterior_predictive(trace,
100, eom_prod_model), I receive a shape error?:

ValueError: input operand has more dimensions than allowed by the axis
remapping

Thank you!

**Comment by AlexAndorra** [comment] 2020-11-10 15:08
Great, good to hear! Yes, multiprocessing is a common issue on Windows, and for the moment the only workaround we have is to disable it.
Regarding your other question, as this is not a bug, can you post it to [our discourse channel](https://discourse.pymc.io) please? That's where users ask about specific use cases or general modeling questions. 
Closing this in the meantime, and see you on Discourse 😉

**Closed as completed by AlexAndorra** 2020-11-10 15:08 UTC

**Comment by cmp1** [comment] 2020-11-10 15:25
Understood, many thanks for your help Alexandre :)
