### ISSUE TITLE
Nuts seems to generate biased variance estimates

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#1763] opened 2017-02-08 20:15 UTC
While investigating the test failure for #1758 I started writing a little framework for testing estimates of  known posteriors (coming in a separate pull request soon). I stumbled across a systematic error in the posterior samples when sampling from this model:

```python
with pm.Model() as model:
    a = pm.Normal("a", mu=2, sd=np.sqrt(3), shape=10)
```

after sampling a million samples in 4 chains (tuning enabled in the first 1000 samples) I got the variances:
```python
>>> trace[1000:]['a'].var(axis=0)
array([ 3.0126,  3.0087,  3.0103,  3.0138,  3.018 ,  3.0113,  3.0112, 3.0121,  3.0149,  3.0151])
```
The mean values also look a bit off, but not by as much:

```python
array([ 2.0001,  2.0006,  2.0008,  2.0006,  2.0009,  1.9996,  1.9992,  2.0002,  2.0006,  2.0006])
```

**Comment by fonnesbeck** [comment] 2017-02-08 20:28
Can confirm this does not happen for Metropolis:

```
In [15]: tr['a', 10000:].var(axis=0)
Out[15]: 
array([ 2.98618716,  3.00670869,  3.00039494,  2.9964126 ,  3.01218762,
        2.98793436,  2.99903401,  3.00136356,  2.99284512,  3.00070455])
```

**Comment by aseyboldt** [comment] 2017-02-08 20:42
I don't have time to do this now, but it might also be useful to try this on the branch from #1757 with the modified stopping criterion (see description of the pull request). If nobody beats me to it I'll do this tomorrow.

**Comment by twiecki** [comment] 2017-02-09 10:21
This seems like a critical issue, even though the bias seems small. Reminds me of the recent problem in Stan, although I bet the cause is different: andrewgelman.com/2016/12/21/michael-found-bug-stans-new-sampler/

**Comment by aseyboldt** [comment] 2017-02-09 18:09
Good news: This does seem to have been introduced after the 3.0 release, so this is only a problem on master.

The bias depends a lot on the step size, and how this is determined changed recently. I tried different commits with a fixed step size of 0.9 and the problem first appears in 4cef6034ffbd8.

I used this code to test for the problem:
```python
import pymc3 as pm
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np

with pm.Model() as model:
    a = pm.Normal("a", mu=2, sd=np.sqrt(3), shape=10)
    trace = pm.sample(500000, tune=1000, init=None)

vars = trace['a', 1000:].var(0)
stats.ttest_1samp(vars, 3)
```

**Comment by aseyboldt** [comment] 2017-02-09 18:51
I pushed a commit to #1757 that I think fixes this issue. But before I would want to see that merged I really should try to understand how the termination conditions in NUTS influence detailed balance. That's not clear to me at the moment.

**Comment by ColCarroll** [comment] 2017-02-09 19:05
That termination criterion corresponds to equation 4 in the NUTS paper.
The discussion below describes what might happen when violating this:  we
build a tree where a stopping condition was already met, which violates
condition C4, which I guess is a symmetry condition.

**Comment by twiecki** [comment] 2017-02-15 22:09
Closed by https://github.com/pymc-devs/pymc3/pull/1757 I think.

**Closed as completed by twiecki** 2017-02-15 22:09 UTC
