### ISSUE TITLE
njobs > 1 causing RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by grburgess** [pymc-devs/pymc#925] opened 2016-01-03 19:48 UTC
Regardless of what model I am using, when I set njobs to a value greater than 1 then I get the following error:

``` python
/usr/local/lib/python2.7/site-packages/pymc3/sampling.pyc in sample(draws, step, start, trace, chain, njobs, tune, progressbar, model, random_seed)
    154         sample_args = [draws, step, start, trace, chain,
    155                        tune, progressbar, model, random_seed]
--> 156     return sample_func(*sample_args)
    157 
    158 

/usr/local/lib/python2.7/site-packages/pymc3/sampling.pyc in _mp_sample(njobs, args)
    275 def _mp_sample(njobs, args):
    276     p = mp.Pool(njobs)
--> 277     traces = p.map(argsample, args)
    278     p.close()
    279     return merge_traces(traces)

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.pyc in map(self, func, iterable, chunksize)
    249         '''
    250         assert self._state == RUN
--> 251         return self.map_async(func, iterable, chunksize).get()
    252 
    253     def imap(self, func, iterable, chunksize=1):

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.pyc in get(self, timeout)
    565             return self._value
    566         else:
--> 567             raise self._value
    568 
    569     def _set(self, i, obj):

RuntimeError: maximum recursion depth exceeded
```

The code block I am using is the following (some of it is irrelevant to the issue... but for completeness)

``` python
with fitModel2:

    norm  = pm.Uniform('norm',lower=1E-3,upper=1E-1)

    idx=pm.Uniform('idx',lower=-3,upper=0)


    #Aeff =  pm.Normal('Aeff',mu=1,sd=.1,shape=128)
    AeffN1 =  pm.Normal('AeffN0',mu=1,sd=.1,shape=len(n1.GetEnergySelection()))
    AeffB0 =  pm.Normal('AeffB0',mu=1,sd=.1,shape=len(b0.GetEnergySelection()))


    n0.SetParams([norm,idx], pmc=True)
    cnts_n0 = n0.GetModelCnts(pmc=True)

    n1.SetParams([norm,idx], pmc=True)
    #cnts_n1 =n1.GetModelCnts(pmc=True)
    cnts_n1 =T.mul(AeffN1,n1.GetModelCnts(pmc=True))

    b0.SetParams([norm,idx], pmc=True)
    cnts_b0 =T.mul(AeffB0, b0.GetModelCnts(pmc=True))
    #cnts_b0 = b0.GetModelCnts(pmc=True)

    source_n0 = pm.Poisson('source_n0', mu=cnts_n0, observed=simCnts_n0[(n0.GetEnergySelection())])
    source_n1 = pm.Poisson('source_n1', mu=cnts_n1, observed=simCnts_n1_smear[(n1.GetEnergySelection())])
    source_b0 = pm.Poisson('source_b0', mu=cnts_b0, observed=simCnts_b0_smear[(b0.GetEnergySelection())])

with fitModel2:
    start = pm.find_MAP()
    step = pm.NUTS(scaling=start)
    trace2 = pm.sample(5000, step, start=start, progressbar=True,njobs=2,)
```

I note that there was an issue with progressbar=True causing this, but it fails even when it is set to False.

Cheers

**Comment by fonnesbeck** [comment] 2016-01-03 20:14
Duplicate of #879

**Closed as completed by fonnesbeck** 2016-01-03 20:14 UTC
