### ISSUE TITLE
model.logp not calculated correctly

### ISSUE THREAD

**Issue by andrea-cuttone** [pymc-devs/pymc#789] opened 2015-07-22 12:41 UTC
Hi

Me and @baekgaard needed to compute the exact loglikelihood to compare different models and to calculate DIC.
We noticed a strange behavior of the loglikelihood returned by model.logp. The core of the issue is that the value returned by model.logp differs from the theoretical exact loglikelihood by a constant value.
Please see this notebook for an example of a simple binomial model: https://gist.github.com/baekgaard/2e79e73d784f8eaf8a05

We narrowed down the issue to the commit https://github.com/pymc-devs/pymc3/commit/4bb9d47819103b7df699b87e1f35509e89eae25e. Before that commit the model.logp is exactly equal to the theoretical one. After that commit the two are different.

**Comment by twiecki** [comment] 2015-07-22 13:22
Many thanks for the detailed bug report. I'm assigning @jsalvatier to take a look since he'd know most about this.

**Comment by baekgaard** [comment] 2015-07-22 14:14
Great, thanks @twiecki 

I just looked again at the git history and I can see the two commits mentioned are actually from separate branches that are then merged back into the master a day later or so, so there may be other commits involved too for the final bisect -- but I guess @jsalvatier would know completely since it appears that he did the merges too :-)

**Comment by jsalvatier** [comment] 2015-07-22 18:31
Hi guys, looks like this was caused by the addition of the logodds transform as a default transform to Uniform due to the Jacobian correction. This means that the actual density that its being computed is for a model where `p_logodds` is the important variable. This is stretched out, so it will have a lower density. Does that make sense?

I was able to eliminate the discrepancy you guys see by saying `p = Uniform('p', 0, 1, transform=None)`. 

This was an unfortunate confusion. Do you guys have thoughts on how we could have made this more obvious?

**Comment by twiecki** [comment] 2015-07-22 18:31
Quick progress udpate: it's the transform. If you supply `transform=None` for the Uniform you get the correct results.

**Comment by andrea-cuttone** [comment] 2015-07-23 12:24
Thanks all for the quick reply.

Adding `transform=None` indeed makes the `model.logp` return the right value. I tested this in the binomial toy example with Uniform, Beta and Exponential priors. 
This leads to a few more questions:
- is this `transform=None` needed for all random variables in a model in order to compute the exact logp?
- what is the reason behind using this transform by default? And what are the consequences of using `transform=None`: worse convergence, worse results or nothing in particular?
- are the loglikelihoods from different models **without** `transform=None` directly comparable - for example for calculating AIC/BIC/DIC? In other words, is the difference in loglikelihood between a model with and without transformed parameter exactly the same for all models?

> Do you guys have thoughts on how we could have made this more obvious?

It seems that this change in the way the loglikelihood is calculated may cause some problems when using directly the loglikelihood, so maybe the transform should be explicitly chosen?  

Thanks!

**Comment by jsalvatier** [comment] 2015-07-23 17:29
1. All random variables that are constrained have default transforms, so you'll want to set transform=None. 
2. The reason is easier, more efficient sampling. Consequence might be worse sampling. The transforms perform a change of variables from say [0, inf) into the full real line (-inf, inf) using the log transform for [0, inf) and log odds for [0, 1]. Since we are now sampling on a transformed space, we need to adjust the likelihood density for that stretching (to conserve probability). This is the adjustment you've seen. 
3. Not all the variables are transformed in the same way, so the adjustments are different.

If you guys want to avoid all this, you can add variables using `Flat('x')` which adds a variable with a totally flat prior and no transform.

**Comment by andrea-cuttone** [comment] 2015-07-26 08:49
I see, thanks. The `Flat` prior would not work for the real model we are using, but we will try to add this `transform=None` and see how that works. I'll give an update in a few days.

**Comment by twiecki** [comment] 2015-07-26 14:16
@andrea-cuttone that will certainly work. if you're doing model comparison and both models are transformed it shouldn't make a difference though.

**Comment by twiecki** [comment] 2015-08-18 06:24
@andrea-cuttone Any update?

**Comment by andrea-cuttone** [comment] 2015-08-19 13:50
Hi

sorry for the slow updates. 

We have run our real model, which is fairly complex - involving two switchpoints, poisson and hyperparameters. Running with `transform=None` gave sensible results with no apparent issues on speed or convergence. I did not compare however the exact loglikelihood of the real model with the one from pymc, as I do not have the analytical expression.

I guess this issue can be considered closed, as the logp seems indeed calculated correctly with `transform=None`. 
However I am still a bit in doubt on what is the recommended way to perform model comparison in pymc3.

**Comment by jsalvatier** [comment] 2015-08-19 19:36
I think as it stands the way to do it is with transform=None. Another for the future alternative is to make it easier to compute the logp in the original space as an auxiliary variable to be computed.

**Comment by andrea-cuttone** [comment] 2015-08-20 08:38
Sounds good. Thanks for the help. The issue can be closed for me.

**Closed as completed** 2016-05-22 18:39 UTC
