### ISSUE TITLE
Missing model argument in sampling.py init_nuts, this will cause njobs failed.

### ISSUE THREAD

**Issue by bear0330** [pymc-devs/pymc#2689] opened 2017-11-04 04:53 UTC
If you have questions about a specific use case, please post it to our discourse channel: https://discourse.pymc.io  
If you are not sure whether this is a bug or not, please also post it on discourse.

## Description of your problem
sampling.py init_nuts call pm.NUTS without model argument, this will cause multiprocess fail to get model context.

**Please provide a minimal, self-contained, and reproducible example.**
Here is a test script:
```
import numpy as np
import pymc3 as pm
import time 

def main(model):
   
    #step = pm.Metropolis(model=model)
    #step = pm.HamiltonianMC(model=model)        
    step = None
    trace = pm.sample(20000, step=step, model=model, njobs=1)
                
    #pm.traceplot(trace)
    #plt.show()

if __name__ == '__main__':
    with pm.Model() as model:
        nu = pm.Normal('nu', mu=1, sd=2)
        nu2 = pm.Normal('nu2', mu=5, sd=100)
        v = pm.Deterministic('v', nu * nu2)    
    s = time.time()
    main(model)
    print(time.time() - s)

```

**Please provide the full traceback.**
```
Traceback (most recent call last):
  File "pymc3-try.py", line 43, in <module>
    main(model)
  File "pymc3-try.py", line 13, in main
    trace = pm.sample(20000, step=step, model=model, njobs=1)
  File "C:\Miniconda2\envs\mcmc\lib\site-packages\pymc3\sampling.py", line 252, in sample
    progressbar=progressbar, **args)
  File "C:\Miniconda2\envs\mcmc\lib\site-packages\pymc3\sampling.py", line 879, in init_nuts
    step = pm.NUTS(potential=potential, **kwargs)
  File "C:\Miniconda2\envs\mcmc\lib\site-packages\pymc3\step_methods\arraystep.py", line 39, in __new__
    model = modelcontext(kwargs.get('model'))
  File "C:\Miniconda2\envs\mcmc\lib\site-packages\pymc3\model.py", line 147, in modelcontext
    return Model.get_context()
  File "C:\Miniconda2\envs\mcmc\lib\site-packages\pymc3\model.py", line 139, in get_context
    raise TypeError("No context on context stack")
TypeError: No context on context stack
```

**Please provide any additional information below.**
After add model=model, and line `step = pm.NUTS(potential=potential, **kwargs)` bug fixed.
But I am not sure whether are any other model arguments missing, maybe you should check the code.

## Versions and main components

* PyMC3 Version: 3.2
* Theano Version: 0.9
* Python Version: 3.5
* Operating system: Windows 10
* How did you install PyMC3: (conda/pip) pip
if I use conda to install PyMC3 I will get 3.0, but it still have the same bug, just not at the same line, it happens on calling advi, also model argument missing.

**Comment by junpenglao** [comment] 2017-11-04 07:43
In the model definition, you should put the pm.sample in the model context:
```python
def main(model):
    with model:
        #step = pm.Metropolis(model=model)
        #step = pm.HamiltonianMC(model=model)        
        step = None
        trace = pm.sample(20000, step=step, njobs=4)
                
    #pm.traceplot(trace)
    #plt.show()
```

Closing as it is not a bug.

**Comment by aseyboldt** [comment] 2017-11-04 09:21
Well, we provide the option to pass the model in as kwarg, which is the case in the example, so I think this should actually work. Minimal example:
```python
with pm.Model() as model:
    pm.Normal('nu')

trace = pm.sample(model=model, njobs=1)
```
This raises a no-context error.

The model arg is mentioned in the docstring of `pm.sample`:
>     model : Model (optional if in `with` context)

**Closed as completed** 2017-11-04 12:06 UTC

**Comment by junpenglao** [comment] 2017-11-04 12:07
should be fix now ;-)

**Comment by aseyboldt** [comment] 2017-11-04 20:59
@junpenglao Thanks!
