### ISSUE TITLE
Improve issue templates

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#6326] opened 2022-11-21 13:13 UTC
Numpy issue templates are just amazing. They have query parameters so you just fill the gaps

https://github.com/numpy/numpy/tree/main/.github/ISSUE_TEMPLATE

Let me know what you think of them

**Comment by michaelosthege** [comment] 2022-11-21 13:19
duplicate of #5119, but yes I'm all for it!

**Comment by ferrine** [comment] 2022-11-21 14:06
I can do this, any objections from @twiecki or @canyon289? There is also a question of attribution, is it fine to mention it in the commit message that we took it from numpy repo?

**Comment by michaelosthege** [comment] 2022-11-21 14:17
You could add something like this to the YAML file:

```yaml
# This issue template was adapted from the NumPy project
# under the BSD 3-Clause "New" or "Revised" License.
# Copyright (c) 2005-2022, NumPy Developers.
# All rights reserved.
```

**Comment by ferrine** [comment] 2022-11-21 14:35
Sounds reasonable

**Comment by canyon289** [comment] 2022-11-21 17:31
lgtm

**Closed as completed** 2022-11-22 08:28 UTC
Labels: beginner friendly
