### ISSUE TITLE
BUG: segmentation fault & possiblea leakage when using unpooled model with JAX based samplers

### ISSUE THREAD

**Issue by JovanVeljanoski** [pymc-devs/pymc#6815] opened 2023-07-04 11:51 UTC
### Describe the issue:

Hi, 

I am trying to run a large-ish unpooled model across several datasets.

The model compiles and runs well, but when I run the sampling with either  `pymc.sampling.jax.sample_numpyro_nuts` or `pymc.sampling.jax.sample_blackjax_nuts`, i get errors that I find hard to debug. 

 - In the case of `pymc.sampling.jax.sample_numpyro_nuts`, the error is: `/Users/jovan/miniconda3/envs/abnormal-new/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown   | 0/6000 [00:00<?, ?it/s]
  warnings.warn('resource_tracker: There appear to be %d '`
 - In the case of `pymc.sampling.jax.sample_blackjax_nuts`, the error is: `zsh: segmentation fault  python script.py`
 
 In case cases, i do "get lucky",  and with `sample_blackjax_nuts` the script does run and the result appear to be correct, but running the same script immediately afterwards, raises the error above. With `numpyro` the error is consistent each time. 

If I an the example (code below) in the jupyter notebook, the kernel dies in both cases.
 
There are no memory issues, i.e. I have plenty of RAM left free on the machine. 

### Reproduceable code example:

```python
import pandas as pd 

import numpy as np

import pymc as pm
import pymc.sampling.jax

from  pymc_experimental.distributions.histogram_utils import histogram_approximation


# Generate data
print('Generate data..')
num_groups = 15

data_pool = []

for _ in range(num_groups):
    loc = np.random.uniform(low=1, high=10, size=2)
    scale = np.random.uniform(low=0.5, high=2.5, size=2)
    size = np.random.randint(low=5_000, high=50_000)
    control = np.random.normal(loc=loc[0], scale=scale[0], size=size)
    variant = np.random.normal(loc=loc[1], scale=scale[1], size=size)
    
    size_binary = np.random.randint(low=100_000, high=500_000)
    control_binary = np.random.binomial(n=1, p=np.random.uniform(0.01, 0.08), size=100)
    variant_binary = np.random.binomial(n=1, p=np.random.uniform(0.01, 0.08), size=100)
    
    data_pool.append((control, variant, control_binary, variant_binary))
    

# Priors
control_prior_mean = np.array([x.mean() for (x, _, _, _) in data_pool])
variant_prior_mean = np.array([x.mean() for (_, x, _, _) in data_pool])
    
control_prior_std = np.array([x.std() for (x, _, _, _) in data_pool])
variant_prior_std = np.array([x.std() for (_, x, _, _) in data_pool])


# Modelling
print('Warming up the model..')
with pm.Model() as model:
    
    # Priors - continuous
    control_mean = pm.Normal(name="control_mean", mu=control_prior_mean, sigma=control_prior_std, shape=num_groups)
    variant_mean = pm.Normal(name="variant_mean", mu=variant_prior_mean, sigma=variant_prior_std, shape=num_groups)
    
    control_std = pm.Uniform(name="control_std", lower=0.01, upper=control_prior_std * 2, shape=num_groups)
    variant_std = pm.Uniform(name="variant_std", lower=0.01, upper=variant_prior_std * 2, shape=num_groups)
    
    # Binary
    control_cvr = pm.Beta(name="control_cvr", alpha=1, beta=1, shape=num_groups)
    variant_cvr = pm.Beta(name="variant_cvr", alpha=1, beta=1, shape=num_groups)
    
    # Equations to solve: build likelihoods
    # Iterate over all datasets!
    for i, (control_data, variant_data, control_binary, variant_binary) in enumerate(data_pool):        
        
        # Likelihood for continuous metric
        histogram_approximation(
            f"histogram_potential_control_{i}",
            pm.Normal.dist(mu=control_mean[i], sigma=control_std[i]),
            observed=control_data,
            n_quantiles=1024 * 16,
        )
        
        # Likelihood for CVR
        histogram_approximation(
            f"histogram_potential_variant_{i}",
            pm.Normal.dist(mu=variant_mean[i], sigma=variant_std[i]),
            observed=variant_data,
            n_quantiles=1024 * 16,
        )
        
        histogram_approximation(
            f"histogram_p_control_{i}",
            pm.Bernoulli.dist(p=control_cvr[i]),
            observed=control_binary,
        )
        histogram_approximation(
            f"histogram_p_variant_{i}",
            pm.Bernoulli.dist(p=variant_cvr[i]),
            observed=variant_binary,
        )        
    
    # trace = pymc.sampling.jax.sample_numpyro_nuts(  
    trace = pymc.sampling.jax.sample_blackjax_nuts(
                draws=5_000,
                tune=1_000,
                chains=4,
                target_accept=0.9, 
                progress_bar=True, 
                idata_kwargs={"log_likelihood": False},
            )
    
# To conclude
x = trace.to_dataframe()
print(x.head())
print('')
print('DONE')
```

### Error message:

 - In the case of `pymc.sampling.jax.sample_numpyro_nuts`, the error is: `/Users/jovan/miniconda3/envs/abnormal-new/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown   | 0/6000 [00:00<?, ?it/s]
  warnings.warn('resource_tracker: There appear to be %d '`
 - In the case of `pymc.sampling.jax.sample_blackjax_nuts`, the error is: `zsh: segmentation fault  python script.py`

### PyMC version information:

pymc : 5.5.0 from pip. Same behaviour observed for 5.1.2 and 5.3.0
pymc-experimental: 0.0.7 (commit 2da3c81)
jax: 0.4.13 from pip
jaxlib: 0.4.13 from pip
jaxopt: 0.7 from pip
blackjax: 0.9.6 from pip
numpyro: 0.12.1 from pip
pytensor: 2.12.3 from pip

### Context for the issue:

My appologies if I am raising this in the wrong place (not sure if I was supposed to submit this at numpyro, blackjax, or jax), but as an .. end user I could most easily make a reproducible example via pymc.

It is possible that I am abusing the model a bit, but it might be some leakage of resources somewhere..

Everything reported above has been run on Mac M1. I've not had the opportunity to try it under Linux.

**Comment by ricardoV94** [comment] 2023-07-04 12:17
My guess is that it's a JAX issue, but creating a reproducible example that's useful for them might be quite a lot of work :/

**Comment by JovanVeljanoski** [comment] 2023-07-04 12:38
Yeah, i was afraid of that :). If there is any way i can help additionally please let me know. I've not used jax directly..
At least this issue is documented. 

I assume as a workaround, one could "split" the giant model above into two separate models, one for the continuous/normal distribution and one for the binary/Bernoulli case.

**Comment by jessegrabowski** [comment] 2023-07-04 14:15
I wasn't able to reproduce the error; the model sampled fine for me with numpyro on Ubuntu (WLS2). I did set some jax and numpyro flags, I don't know if this mattered?

```
import jax
jax.config.update('jax_platform_name', 'cpu')

import numpyro
numpyro.set_platform('cpu')
numpyro.set_host_device_count(4)

# Code continues as posted --
# I used the updated sample API, also don't know if this matters at all
    trace = pm.sample(nuts_sampler='numpyro',
                  nuts_sampler_kwargs={'chain_method':'parallel'},
            draws=5_000,
            tune=1_000,
            chains=4,
            target_accept=0.9, 
        )
```

Versions:
```
pymc version: 5.5.0
jax version: 0.4.13
pytensor version: 2.12.3
numpyro version: 0.12.1
```

**Comment by JovanVeljanoski** [comment] 2023-07-04 15:13
Hey @jessegrabowski 

Thanks for the feedback. I will try to get an access to a Linux machine (my example above was on M1 Mac), and also try with your edits. 

Also, for me it also works (sometimes?) but repeated execution of the same script (2 or 3 times in a row) causes the problems mentioned. 

In any case, I will try again and report back.

**Comment by ricardoV94** [comment] 2023-07-04 15:14
May be worth testing different versions of JAX, sometimes things break between releases

**Comment by jessegrabowski** [comment] 2023-07-04 15:22
I used numpyro because I thought you were saying you always got the error with that one. I ran it once with blackjax without incident as well, though

**Comment by ricardoV94** [comment] 2024-02-06 10:01
Closing this as I assume it's not PyMC's responsibility

**Closed as completed by ricardoV94** 2024-02-06 10:01 UTC
Labels: bug, jax
