### ISSUE TITLE
Problem combining GaussianRandomWalk and Weibull distribution

### ISSUE THREAD

**Issue by romankarlstetter** [pymc-devs/pymc#3584] opened 2019-08-13 12:29 UTC
Hi,

I have data that I want to model using a Weibull distribution. I want to model it such that the beta parameter changes "over time" (data is a time series). I'm trying to model that using a Gaussian random walk, see here:

```python
with pm.Model() as model:
    sd_beta = pm.HalfCauchy('sd_beta', 100)
    mu_beta = pm.Normal('mu_beta', 0, 1)
    beta = pm.GaussianRandomWalk('beta', 
                                 mu=mu_beta,
                                 sd=sd_beta,
                                shape=len(d),
                                )
    y_obs = pm.Weibull('y_obs',
                alpha=2, #Rayleigh distribution
                beta=beta,
                observed=d)
```

Unfortunately, this does not really work, I get the following error

`TypeError: 'float' object is not subscriptable`

This is because of the following check in the Weibull distribution, I guess:

https://github.com/pymc-devs/pymc3/blob/37466665efec5907c918f59a68edb6b11bea2b9e/pymc3/distributions/continuous.py#L2866

I don't really understand what's happening here. Why is that check there and what is it used for?
Is is even possible to do what I'm trying to do or is there a conceptual problem with my model?

Thanks in advance,
Roman

**Comment by aloctavodia** [comment] 2019-08-13 14:08
The beta parameter of the Weibull distribution has to be positive. But you are setting it to a `GaussianRandomWalk` that will provide values over the real line. Thus, is you may want to transform the values of the `GaussianRandomWalk` distribution to ensure you are getting positive values, assuming this makes sense for your model. 

As this is not a bug I will close this issue and I invite you to post this question in our [discourse](https://discourse.pymc.io/).

**Comment by romankarlstetter** [comment] 2019-08-13 14:34
> 
> As this is not a bug I will close this issue and I invite you to post this question in our [discourse](https://discourse.pymc.io/).

Ok, thanks for the feedback, I'll bring up the topic there.

One suggestion: if easily possible (given this information is available at that point), the error message in this case might be improved to something like
 ` "The beta parameter of the Weibull distribution ('y_obs') has to be positive, which is not guaranteed in this case."`

**Comment by rpgoldman** [comment] 2019-08-13 17:41
`assert_negative_support` seems like a very odd name for this function, because doesn't it actually require that the support of the random variable in question must be strictly positive? Or does it require only non-negative support (i.e., is zero acceptable)?  Could we rename this? It could be done without any ramifications, since it's only used in `continuous.py`. A docstring would be nice, too.

WRT @romankarlstetter 's request for a better error message, it looks like that's there already.  Did I miss someone adding this? Or is there something wrong that causes this to be missed (see following)?

Finally, why is this only a warning, instead of an `AssertionError`? Something bad is going to happen here, so shouldn't we just abort at this point? Is the original question happening because there's an exception after the warning?

**Comment by romankarlstetter** [comment] 2019-08-14 05:27
> WRT @romankarlstetter 's request for a better error message, it looks like that's there already. Did I miss someone adding this? Or is there something wrong that causes this to be missed (see following)?

In `assert_negative_support()`, `logp()` of `var.distribution` is called, in this case an instance of `GaussianRandomWalk`. An there, the float parameter of `assert_negative_support()` is trying to be indexed like an array, which apparently does not work and throws an error before the actual error can be issued (as warning).

**Closed as not planned** 2022-08-27 18:38 UTC
