### ISSUE TITLE
ValueError: Unused step method arguments: {'return_inferencedata'}

### ISSUE THREAD

**Issue by nicospinu** [pymc-devs/pymc#4058] opened 2020-08-18 10:27 UTC
## Description of your problem

**While implementing a hierarchical Bayesian model, I could not run the sampling using the `return_inferencedata=True` argument.**

```python
with model:
       trace=pm.sample(cores=4, return_inferencedata=True)
```

**Here it is the full traceback of the bug.**
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-def2639bc677> in <module>
      1 with hierar_model:
----> 2     trace = pm.sample(cores=4, return_inferencedata=True)

C:\ProgramData\Anaconda3\lib\site-packages\pymc3\sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, **kwargs)
    430             step = assign_step_methods(model, step, step_kwargs=kwargs)
    431     else:
--> 432         step = assign_step_methods(model, step, step_kwargs=kwargs)
    433 
    434     if isinstance(step, list):

C:\ProgramData\Anaconda3\lib\site-packages\pymc3\sampling.py in assign_step_methods(model, step, methods, step_kwargs)
    185             selected_steps[selected].append(var)
    186 
--> 187     return instantiate_steppers(model, steps, selected_steps, step_kwargs)
    188 
    189 

C:\ProgramData\Anaconda3\lib\site-packages\pymc3\sampling.py in instantiate_steppers(model, steps, selected_steps, step_kwargs)
    111     unused_args = set(step_kwargs).difference(used_keys)
    112     if unused_args:
--> 113         raise ValueError("Unused step method arguments: %s" % unused_args)
    114 
    115     if len(steps) == 1:

ValueError: Unused step method arguments: {'return_inferencedata'}
```

**The BHM uses NUTS and BinaryGibbsMetropolis.**

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.8.5
* Operating system: Windows 10
* How did you install PyMC3: conda

**Comment by junpenglao** [comment] 2020-08-18 11:30
Thanks for reporting - I cannot reproduce the error. Could you try upgrading PyMC3 to the newest version (3.9.3)?

**Comment by AlexAndorra** [comment] 2020-08-18 11:43
Hi,
This feature was [introduced in 3.9.0](https://github.com/pymc-devs/pymc3/releases), so upgrading to latest (3.9.3) should work -- closing but feel free to reopen if it doesn't 😉

**Closed as completed by AlexAndorra** 2020-08-18 11:43 UTC

**Comment by nicospinu** [comment] 2020-08-18 12:45
Thank you very much!
Indeed, the issue is related to the version. Anaconda allows to install pymc3 v 3.8 and not the latest. While if I choose pip install, I get the warning related to m2w64-toolchain that makes the sampling running slowly.
If you encountered such issue, I will appreciate any suggestions.

```
>>> import pymc3 as pm
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

**Comment by AlexAndorra** [comment] 2020-08-18 13:53
This is more a usage question than a bug, which we usually answer [on our Discourse](discourse.pymc.io/). Would you mind asking your question there please?

**Comment by nicospinu** [comment] 2020-08-18 14:49
Ok, thank you
