### ISSUE TITLE
Can't Sample Bayesian Lasso Models

### ISSUE THREAD

**Issue by arose13** [pymc-devs/pymc#2884] opened 2018-03-03 03:45 UTC
I'm not sure if this is a bug so I shall explain and give the code to replicate the problem.

I'm trying to make a Bayesian lasso model for regression and I am never able to get it to sample non zero values. I'm implementing the model in these papers [The Bayesian Lasso](https://amstat.tandfonline.com/doi/abs/10.1198/016214508000000337#.WpoYH-jwZEY) and [Bayesian Lasso for genome-wide association studies](https://academic.oup.com/bioinformatics/article/27/4/516/197666) which in fact implement the same models.

I implement it with the PyMC3 code below with the exception being I use the Metropolis sampler rather than the Gibbs because 1, I do not think it is implemented in PyMC3 and 2, from what I understand Gibbs samplers are worse practical most other samplers one might want to use.

```
import numpy as np
import pymc3 as pm
import pymc3.math as pmath
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as graph
from sklearn.metrics import r2_score

# Specify Coefs
coefs = np.zeros(2000)
coefs[50] = 3
coefs[750] = -2
coefs[1500] = 1.5

graph.plot(coefs)
graph.show()

# Create noisy data
x = stats.norm.rvs(0, 1, size=(200, coefs.shape[0]))
y = x @ coefs
y += stats.norm.rvs(0, 6, size=y.shape)

print(f'Best Possible R2 = {r2_score(y, x @ coefs)}')  # R2 ~ 0.25

# PyMC3 Model
with pm.Model() as bayes_l1:
    # Priors
    lambda_sq = pm.Gamma('lambda-sq', alpha=1, beta=1)
    lambda_param = pm.Deterministic('lambda', pmath.sqrt(lambda_sq))
    
    m = pm.Laplace('m', mu=0, b=lambda_param, shape=coefs.shape)
    residual_sd = pm.Uniform('residual-sd', lower=0, upper=100)
    
    # Model
    predictions = pm.Deterministic('pred', pmath.dot(x, m))
    obs = pm.Normal('observed', mu=predictions, sd=residual_sd, observed=y)
    
    # Posterior sampling
    trace = pm.sample(
        50000, step=pm.Metropolis(),
        chains=1, njobs=1,
        compute_convergence_checks=False
    )
    pm.traceplot(trace, varnames=['m', 'lambda', 'residual-sd'])
    graph.show()
```

*Version information*
pymc3 == 3.3
theano == 1.0.1
python == 3.6

the operating system is Ubuntu and I install with conda.

**Comment by fonnesbeck** [comment] 2018-03-03 04:24
You should let PyMC choose the sampler for you unless you have a good reason not to. In this case, NUTS should be used instead of Metropolis. Metropolis is not a very efficient algorithm, and often will not adequately explore the posterior distribution.

**Comment by junpenglao** [comment] 2018-03-03 08:26
Also, you should avoid using a uniform prior as the sigma for the Normal distribution.

Bayesian Lasso is usually not doing what it is advertised to do, for similar covarites selection problem, you should consult the more recent paper by @avehtari (eg: Sparsity information and regularization in the horseshoe and other shrinkage priors). He also put out a repository with Stan code https://github.com/avehtari/modelselection_tutorial that contains a lot of informaiton.

Since this is not a bug I am closing this for now. For further modelling related discussion please move to https://discourse.pymc.io ;-)

**Closed as completed by junpenglao** 2018-03-03 08:26 UTC
