### ISSUE TITLE
Variables don't show up in pm.pairplot

### ISSUE THREAD

**Issue by rosgori** [pymc-devs/pymc#3155] opened 2018-08-15 01:58 UTC
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem

The names of the variables don't show up in a pair plot. Run the following code as a script or from IPython.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import numpy as np
import pymc3 as pm
from scipy.stats import norm
import matplotlib.pyplot as plt
import pandas as pd

df_n30 = pd.read_csv('https://raw.githubusercontent.com/JWarmenhoven/DBDA-python/master/Notebooks/data/HtWtData30.csv')

sd_h = df_n30.height.std()
mean_h = df_n30.height.mean()
zheight = (df_n30.height - mean_h)/sd_h

sd_w = df_n30.weight.std()
mean_w = df_n30.weight.mean()
zy = (df_n30.weight - mean_w)/sd_w

#### Model

with pm.Model() as model:
    
    beta0 = pm.Normal('beta0', mu=0, tau=1/10**2)
    beta1 = pm.Normal('beta1', mu=0, tau=1/10**2)
    mu =  beta0 + beta1*zheight.ravel()
    
    sigma = pm.Uniform('sigma', 10**-3, 10**3)
    nu = pm.Exponential('nu', 1/29)
    
    likelihood = pm.StudentT('likelihood', nu, mu=mu, sd=sigma, observed=zy.ravel())

with model:
    trace = pm.sample(1000)

pm.pairplot(trace)
plt.show()
```

To be clear, this happens in the *x* axis: https://www.dropbox.com/s/rmjq6vcunu5j30b/figure_2.svg?dl=0

**Please provide any additional information below.**
If you run the code in a jupyter notebook, the names of the variables appear correctly.

## Versions and main components

* PyMC3 Version: 3.5
* Theano Version: 1.0.2
* Python Version: 3.6.6
* Operating system: Ubuntu 16.04
* How did you install PyMC3: (conda/pip) conda

**Comment by aloctavodia** [comment] 2018-08-15 10:59
Thanks for taking the time to report this. As a workaround you can pass `bbox_inches='tight'` to `savefig`

**Comment by aloctavodia** [comment] 2018-09-12 15:43
Closing as I am not able to reproduce this with PyMC3 or ArviZ

**Closed as completed** 2018-09-12 15:43 UTC
