### ISSUE TITLE
Sample_ppc does not work as expected on multidimensional observed variables

### ISSUE THREAD

**Issue by Mithrillion** [pymc-devs/pymc#2536] opened 2017-09-02 06:03 UTC
Suppose I have a dataset of the following format:
> 	0	1	2	3
0	-0.044496	2.004234	1.026662	5.116454
1	0.073038	2.032703	1.108759	4.965466
2	0.089493	2.059980	0.967329	4.947103
3	-0.016191	1.868296	0.905673	4.972941
4	-0.004346	1.914541	1.007447	5.184033

(200 x 4 matrix)
Now I want to fit a regression model to predict column 2, 3 with column 0, 1. Converting an 1-D example to 2-D gives us the following:
```
with pm.Model() as model:
    intercept = pm.Normal('intercept', 0, sd=20)
    gradient = pm.Normal('gradient', 0, sd=20)
    epsilon = pm.HalfCauchy('epsilon', 5)

    obs_y = pm.Normal('obs_y', mu=intercept + gradient * df_data.values[:, :2], sd=sd, 
                        observed=df_data.values[:, -2:])

    trace = pm.sample(1000, tune=500)
```
The model runs without issue. However, when I try to sample from the posterior, I get the following:
```
with model:
    samp = pm.sample_ppc(trace, samples=100)
samp['obs_y'].shape
```
> (100, 200, 2)

Unlike in 1-D case where you would get a (100, ) / (100, 1) vector, here the sampler draws samples the shape of the observation, (200, 2), 100 times.
Is it possible to make PyMC3 explicitly recognise a batch dimension, like in Edward with "None" dimensions, so it is easier to sample from multidimensional posterior or adapt the model to new inputs?

Furthermore, when if we use a MvNormal instead of Normal, the sample_ppc function does not work: 
```
with pm.Model() as model:
    intercept = pm.Normal('intercept', 0, sd=20)
    gradient = pm.Normal('gradient', 0, sd=20)
    epsilon = pm.HalfCauchy('epsilon', 5)

    obs_y = pm.MvNormal('obs_y', mu=intercept + gradient * df_data.values[:, :2], cov=cov, 
                        observed=df_data.values[:, -2:])

    trace = pm.sample(1000, tune=500)
```
Then
```
with model:
    samp = pm.sample_ppc(trace, samples=100)
```

gives the following:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-52-fabbb7a69290> in <module>()
      1 with model:
----> 2     samp = pm.sample_ppc(trace, samples=100)

~/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/sampling.py in sample_ppc(trace, samples, model, vars, size, random_seed, progressbar)
    537             param = trace[idx]
    538             for var in vars:
--> 539                 vals = var.distribution.random(point=param, size=size)
    540                 ppc[var.name].append(vals)
    541     finally:

~/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/distributions/multivariate.py in random(self, point, size)
    156             mu, cov = draw_values([self.mu, self.cov], point=point)
    157             if mu.shape != cov[0].shape:
--> 158                 raise ValueError("Shapes for mu an cov don't match")
    159 
    160             try:

ValueError: Shapes for mu an cov don't match

Here is the sample data generation code adopted from another issue:
```
from pymc3 import  *
import pymc3 as pm
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

size = 200
true_intercept = 1
true_slope = 2

comb_x = np.array([np.linspace(0, 1, size), np.linspace(2, 3, size)]).T
true_regression_line = true_intercept + true_slope * comb_x

std_y, std_x = 0.1, 0.1 
y = true_regression_line + np.random.normal(scale=std_y, size=(size, 2))
x = comb_x + np.random.normal(scale=std_x, size=(size, 2))

df_data = pd.DataFrame(np.concatenate([x, y], axis=1))
sd = df_data.iloc[:, -2:].std()
cov = df_data.iloc[:, -2:].cov()
```

**Comment by junpenglao** [comment] 2017-09-02 06:24
> Unlike in 1-D case where you would get a (100, ) / (100, 1) vector, here the sampler draws samples the shape of the observation, (200, 2), 100 times.

This is expected behaviour. The shape of your observed node `obs_y` is (200, 2), and `pm.sample_ppc` returns the same size as your observed. 


> Is it possible to make PyMC3 explicitly recognise a batch dimension, like in Edward with "None" dimensions, so it is easier to sample from multidimensional posterior or adapt the model to new inputs?

Yes, you can use `theano.shared` ([exmaple here](http://docs.pymc.io/en/latest/advanced_theano.html#using-shared-variables) and [here](http://docs.pymc.io/en/latest/notebooks/posterior_predictive.html#Prediction)) or `pm.Minibatch` ([example here](http://docs.pymc.io/en/latest/notebooks/GLM-hierarchical-advi-minibatch.html))

Also, I got no error on the MvNormal ppc - could you please try update to master?

**Comment by Mithrillion** [comment] 2017-09-02 12:38
Thanks for the suggestion. The MvNormal issue does seem to be fixed in the latest master branch.

I am not familiar with Theano but I suppose `shared` works similarly to `tf.placeholder`, which makes sense to me.

I do not understand the use of "Minibatch" though. I suppose it actually splits the dataset and only uses a sample from the data to perform one iteration of inference, is that correct? I am not getting the same or similar result as no minibatch even if I set the batch size to be the same as the full dataset, so there must be something I am still missing.

**Comment by junpenglao** [comment] 2017-09-02 12:53
I think minibatch randomly sample with replacement, so the same item could appear more than once. In you case it is better to used theano.shared. 
Also, you cannot use minibatch with `pm.sample()`, as minibatch MCMC is a sperate class of sampling algorithm (PyMC3 only has SGFS for that currently).

More information could be found in the docstring of minibatch https://github.com/pymc-devs/pymc3/blob/master/pymc3/data.py#L93

I will close this for now as it is not a bug. If you have further question please post to discourse.pymc.io

**Closed as completed by junpenglao** 2017-09-02 12:53 UTC
