### ISSUE TITLE
Better error when using numpy on tensors.

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#754] opened 2015-06-15 17:27 UTC
Hi guys!

I was experimenting around with PyMC3 for a new project, and figured out that I needed to create a custom distribution.

I called it the "Overlap" distribution, and with the appropriate import statements, it is defined as follows:

```
class Overlap(Discrete):
    def __init__(self, m, p, *args, **kwargs):
        super(Overlap, self).__init__(*args, **kwargs)
        self.m = m
        self.p = p

    def logp(self, value):
        m = self.m
        p = self.p
        # return overlap_logp(m, p)
        return np.log(1 - (1-p) ** m)
```

One trouble I'm running into is the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-64-16ce8a903fdf> in <module>()
     28     m = Uniform('m', 0, 50)
     29     overlap = Poisson('overlap', m, observed=overlaps)
---> 30     reassort = Overlap('reassort', m, p, observed=reassortant_found)
     31 
     32 with model:

/Users/ericmjl/anaconda/lib/python3.4/site-packages/pymc3-3.0-py3.4.egg/pymc3/distributions/distribution.py in __new__(cls, name, *args, **kwargs)
     17             data = kwargs.pop('observed', None)
     18             dist = cls.dist(*args, **kwargs)
---> 19             return model.Var(name, dist, data)
     20         elif name is None:
     21             return object.__new__(cls) #for pickle

/Users/ericmjl/anaconda/lib/python3.4/site-packages/pymc3-3.0-py3.4.egg/pymc3/model.py in Var(self, name, dist, data)
    144             self.free_RVs.append(var)
    145         else:
--> 146             var = ObservedRV(name=name, data=data, distribution=dist, model=self)
    147             self.observed_RVs.append(var)
    148         self.add_random_variable(var)

/Users/ericmjl/anaconda/lib/python3.4/site-packages/pymc3-3.0-py3.4.egg/pymc3/model.py in __init__(self, name, data, distribution, model)
    379             args = [t.as_tensor_variable(args[0], name=name)]
    380 
--> 381         self.logp_elemwiset = distribution.logp(*args)
    382         self.model = model
    383         self.distribution = distribution

<ipython-input-64-16ce8a903fdf> in logp(self, value)
     11         p = self.p
     12         # return overlap_logp(m, p)
---> 13         return np.log(1 - (1-p) ** m)
     14 
     15 # @as_op(itypes=[T.dscalar], otypes=[T.dscalar])

AttributeError: 'TensorVariable' object has no attribute 'log'
```

I had modelled this custom distribution after the custom Beta distribution found here: http://pymc-devs.github.io/pymc3/getting_started/#arbitrary-distributions, with the only difference being that I didn't define a sub-function as in the example. 

What might be the issue here? I've been trying to debug this for a few hours now, but haven't had much progress, so I was hoping to consult you guys :).

**Comment by ericmjl** [comment] 2015-06-15 17:44
hmmm.... so it looks like changing `np.log` to `theano.tensor.log` solved the issue... this may have been my own misunderstanding of the underpinnings of PyMC. I'm sorry if this took up your time!

**Comment by aflaxman** [comment] 2015-06-15 18:34
I wonder if there is a way to make this error message clearer, since I have run into trouble like it before, too.  Here is a self-contained code block that reproduces the issue @ericmjl described above:

```
import numpy as np, pymc3 as pm

class Overlap(pm.Discrete):
    def __init__(self, m, p, *args, **kwargs):
        super(Overlap, self).__init__(*args, **kwargs)
        self.m = m
        self.p = p

    def logp(self, value):
        m = self.m
        p = self.p
        # return overlap_logp(m, p)
        return np.log(1 - (1-p) ** m)

with pm.Model() as m:
    p = pm.Uniform('p', 0, 1)
    X = Overlap('X', m=10, p=p, observed=[1,2,3])
    t = pm.find_MAP()
```

As he discovered (after perhaps too much painful work) the following small change makes it work:

```
import numpy as np, pymc3 as pm, theano.tensor as tt

class Overlap(pm.Discrete):
    def __init__(self, m, p, *args, **kwargs):
        super(Overlap, self).__init__(*args, **kwargs)
        self.m = m
        self.p = p

    def logp(self, value):
        m = self.m
        p = self.p
        # return overlap_logp(m, p)
        return tt.log(1 - (1-p) ** m)

with pm.Model() as m:
    p = pm.Uniform('p', 0, 1)
    X = Overlap('X', m=10, p=p, observed=[1,2,3])
    t = pm.find_MAP()
```

I would like it if the error message in the first code block said something specifically about trying theano instead of numpy.  Here are some smaller examples of where this could also help:

```
import numpy as np, pymc3 as pm

with pm.Model() as m:
    p = pm.Uniform('p', 0, 1)
    q = np.log(p)
    t = pm.find_MAP()
```

and

```
import numpy as np, pymc3 as pm

with pm.Model() as m:
    p = pm.Uniform('p', 0, 1)
    q = np.exp(m.logpt)
    t = pm.find_MAP()
```

**Comment by jsalvatier** [comment] 2015-06-16 21:56
A very good point @aflaxman . Would you mind making a [Theano issue](https://github.com/Theano/Theano/issues) about making the Numpnumpy/theano misuse error clearer? I think it will be easiest to handle at the theano level. 

Also `np.abs(p)` worked for me, which is beyond confusing.

**Comment by aloctavodia** [comment] 2017-07-06 09:53
Closing as this is no longer an issue. In fact the offending model now runs. Feel free to reopen if necessary.

**Closed as completed by aloctavodia** 2017-07-06 09:53 UTC
