### ISSUE TITLE
There were 6 divergences after tuning. Increase `target_accept` or reparameterize.

### ISSUE THREAD

**Issue by kunyaoli** [pymc-devs/pymc#4355] opened 2020-12-19 03:38 UTC
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io

## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
`with pm.Model() as model_5_7:
    a = pm.Normal('a', mu=10, sd=100)
    bn = pm.Normal('bn', mu=0, sd=1, shape=2)
    sigma = pm.Uniform('sigma', lower=0, upper=1)
    mu = pm.Deterministic('mu', a + bn[0] * dcc['neocortex.perc'] + bn[1] * dcc['log_mass'])
    kcal = pm.Normal('kcal', mu=mu, sd=sigma, observed=dcc['kcal.per.g'])
    trace_5_7 = pm.sample(1000, tune=1000)`
```

**Please provide the full traceback.**
```python
[Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [sigma, bn, a]
Sampling 2 chains: 100%|███████████████████████████████████████████████████████| 4000/4000 [00:20<00:00, 198.18draws/s]
There were 6 divergences after tuning. Increase `target_accept` or reparameterize.
There was 1 divergence after tuning. Increase `target_accept` or reparameterize.]
```
it's tell me "There were 6 divergences after tuning. Increase `target_accept` or reparameterize",this is an error?what this mean?and what should i do? thank you!
**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:3.6
* Theano Version:1.05
* Python Version:3.7
* Operating system: win10
* How did you install PyMC3: (conda)

**Comment by ColCarroll** [comment] 2020-12-19 04:06
This is a warning - it means that the process completed successfully, but the sampler encountered some problems that you may want to investigate. The two suggestions in the warnings are good ones!

Please open a discussion (or do a search!) on https://discourse.pymc.io/ for a more thorough discussion, but I'm closing this since it is not a bug/issue.

**Closed as completed by ColCarroll** 2020-12-19 04:06 UTC
Labels: question

**Comment by kunyaoli** [comment] 2020-12-19 07:31
thank you
