### ISSUE TITLE
I get `NotImplementedError` while using `pm.fit` with custom theano/aesara function

### ISSUE THREAD

**Issue by DostalJ** [pymc-devs/pymc#5680] opened 2022-04-01 17:44 UTC
## I get `NotImplementedError` while using `pm.fit` with custom theano/aesara function

I need to use a custom function defined in Aesara in my model. But attempting to do variational inference using `pm.fit`, I get empty `NotImplementedError`. Sampling (NUTS, ...) works fine.

When the line `@aesara.compile.ops.as_op(itypes=[tt.dvector, tt.dscalar], otypes=[tt.dvector])` is commented out, everything works fine. (I need to define the function with `aesara.compile.ops.as_op` because I use [scipy.special.wofz](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.wofz.html#scipy.special.wofz)).

It seems like pymc3 is not able to assign a correct way to calculate the gradients for the custom aesara function. But I do not understand the aesara codebase enough to validate this.

This issue can be reproduced for both pymc3 (3.11.5) as well as pymc (4.0.0b6). Also for both MacOs (M1) and Ubuntu machine.

Minimal reproducible example is provided below.

```python
import numpy as np
import pymc as pm
import aesara
import aesara.tensor as tt

# Custom theano function
@aesara.compile.ops.as_op(itypes=[tt.dvector, tt.dscalar], otypes=[tt.dvector])
def custom_function(x, alpha):
    return x * alpha

# Toy data generation
ALPHA = 1.7
MEASUREMENT_STD = 1.0

x_data = np.random.uniform(0, 10, size=20)
y_data = np.random.normal(loc=x_data * ALPHA, scale=MEASUREMENT_STD)

x_data_ = tt.as_tensor_variable(x_data.astype(np.float64))

# Pymc model
with pm.Model() as model:
    alpha = pm.Normal('alpha', mu=0, sigma=1)
    y = custom_function(x_data_, alpha)
    likelihood = pm.Normal('likelihood', mu=y, sigma=MEASUREMENT_STD, observed=y_data)

with model:
    vi_result = pm.fit()
```

**Full traceback.**

<details><summary>Complete error traceback</summary>

```python
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Input In [2], in <cell line: 26>()
     24     likelihood = pm.Normal('likelihood', mu=y, sigma=MEASUREMENT_STD, observed=y_data)
     26 with model:
---> 27     vi_result = pm.fit()

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/variational/inference.py:830, in fit(n, local_rv, method, model, random_seed, start, inf_kwargs, **kwargs)
    828 else:
    829     raise TypeError(f"method should be one of {set(_select.keys())} or Inference instance")
--> 830 return inference.fit(n, **kwargs)

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/variational/inference.py:144, in Inference.fit(self, n, score, callbacks, progressbar, **kwargs)
    142     callbacks = []
    143 score = self._maybe_score(score)
--> 144 step_func = self.objective.step_function(score=score, **kwargs)
    145 if progressbar:
    146     progress = progress_bar(range(n), display=progressbar)

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/configparser.py:47, in _ChangeFlagsDecorator.__call__.<locals>.res(*args, **kwargs)
     44 @wraps(f)
     45 def res(*args, **kwargs):
     46     with self:
---> 47         return f(*args, **kwargs)

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/variational/opvi.py:354, in ObjectiveFunction.step_function(self, obj_n_mc, tf_n_mc, obj_optimizer, test_optimizer, more_obj_params, more_tf_params, more_updates, more_replacements, total_grad_norm_constraint, score, fn_kwargs)
    352 if score and not self.op.returns_loss:
    353     raise NotImplementedError("%s does not have loss" % self.op)
--> 354 updates = self.updates(
    355     obj_n_mc=obj_n_mc,
    356     tf_n_mc=tf_n_mc,
    357     obj_optimizer=obj_optimizer,
    358     test_optimizer=test_optimizer,
    359     more_obj_params=more_obj_params,
    360     more_tf_params=more_tf_params,
    361     more_updates=more_updates,
    362     more_replacements=more_replacements,
    363     total_grad_norm_constraint=total_grad_norm_constraint,
    364 )
    365 if score:
    366     step_fn = compile_pymc([], updates.loss, updates=updates, **fn_kwargs)

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/variational/opvi.py:243, in ObjectiveFunction.updates(self, obj_n_mc, tf_n_mc, obj_optimizer, test_optimizer, more_obj_params, more_tf_params, more_updates, more_replacements, total_grad_norm_constraint)
    241     if more_tf_params:
    242         _warn_not_used("more_tf_params", self.op)
--> 243 self.add_obj_updates(
    244     resulting_updates,
    245     obj_n_mc=obj_n_mc,
    246     obj_optimizer=obj_optimizer,
    247     more_obj_params=more_obj_params,
    248     more_replacements=more_replacements,
    249     total_grad_norm_constraint=total_grad_norm_constraint,
    250 )
    251 resulting_updates.update(more_updates)
    252 return resulting_updates

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/variational/opvi.py:291, in ObjectiveFunction.add_obj_updates(self, updates, obj_n_mc, obj_optimizer, more_obj_params, more_replacements, total_grad_norm_constraint)
    287     more_replacements = dict()
    288 obj_target = self(
    289     obj_n_mc, more_obj_params=more_obj_params, more_replacements=more_replacements
    290 )
--> 291 grads = pm.updates.get_or_compute_grads(obj_target, self.obj_params + more_obj_params)
    292 if total_grad_norm_constraint is not None:
    293     grads = pm.total_norm_constraint(grads, total_grad_norm_constraint)

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/variational/updates.py:176, in get_or_compute_grads(loss_or_grads, params)
    174     return loss_or_grads
    175 else:
--> 176     return aesara.grad(loss_or_grads, params)

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:630, in grad(cost, wrt, consider_constant, disconnected_inputs, add_names, known_grads, return_disconnected, null_gradients)
    627     if hasattr(g.type, "dtype"):
    628         assert g.type.dtype in aesara.tensor.type.float_dtypes
--> 630 rval = _populate_grad_dict(var_to_app_to_idx, grad_dict, wrt, cost_name)
    632 for i in range(len(rval)):
    633     if isinstance(rval[i].type, NullType):

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1434, in _populate_grad_dict(var_to_app_to_idx, grad_dict, wrt, cost_name)
   1431     # end if cache miss
   1432     return grad_dict[var]
-> 1434 rval = [access_grad_cache(elem) for elem in wrt]
   1436 return rval

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1434, in <listcomp>(.0)
   1431     # end if cache miss
   1432     return grad_dict[var]
-> 1434 rval = [access_grad_cache(elem) for elem in wrt]
   1436 return rval

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1387, in _populate_grad_dict.<locals>.access_grad_cache(var)
   1384 for node in node_to_idx:
   1385     for idx in node_to_idx[node]:
-> 1387         term = access_term_cache(node)[idx]
   1389         if not isinstance(term, Variable):
   1390             raise TypeError(
   1391                 f"{node.op}.grad returned {type(term)}, expected"
   1392                 " Variable instance."
   1393             )

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1059, in _populate_grad_dict.<locals>.access_term_cache(node)
   1055 if node not in term_dict:
   1057     inputs = node.inputs
-> 1059     output_grads = [access_grad_cache(var) for var in node.outputs]
   1061     # list of bools indicating if each output is connected to the cost
   1062     outputs_connected = [
   1063         not isinstance(g.type, DisconnectedType) for g in output_grads
   1064     ]

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1059, in <listcomp>(.0)
   1055 if node not in term_dict:
   1057     inputs = node.inputs
-> 1059     output_grads = [access_grad_cache(var) for var in node.outputs]
   1061     # list of bools indicating if each output is connected to the cost
   1062     outputs_connected = [
   1063         not isinstance(g.type, DisconnectedType) for g in output_grads
   1064     ]

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1387, in _populate_grad_dict.<locals>.access_grad_cache(var)
   1384 for node in node_to_idx:
   1385     for idx in node_to_idx[node]:
-> 1387         term = access_term_cache(node)[idx]
   1389         if not isinstance(term, Variable):
   1390             raise TypeError(
   1391                 f"{node.op}.grad returned {type(term)}, expected"
   1392                 " Variable instance."
   1393             )

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1059, in _populate_grad_dict.<locals>.access_term_cache(node)
   1055 if node not in term_dict:
   1057     inputs = node.inputs
-> 1059     output_grads = [access_grad_cache(var) for var in node.outputs]
   1061     # list of bools indicating if each output is connected to the cost
   1062     outputs_connected = [
   1063         not isinstance(g.type, DisconnectedType) for g in output_grads
   1064     ]

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1059, in <listcomp>(.0)
   1055 if node not in term_dict:
   1057     inputs = node.inputs
-> 1059     output_grads = [access_grad_cache(var) for var in node.outputs]
   1061     # list of bools indicating if each output is connected to the cost
   1062     outputs_connected = [
   1063         not isinstance(g.type, DisconnectedType) for g in output_grads
   1064     ]

    [... skipping similar frames: _populate_grad_dict.<locals>.access_grad_cache at line 1387 (3 times), <listcomp> at line 1059 (2 times), _populate_grad_dict.<locals>.access_term_cache at line 1059 (2 times)]

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1059, in _populate_grad_dict.<locals>.access_term_cache(node)
   1055 if node not in term_dict:
   1057     inputs = node.inputs
-> 1059     output_grads = [access_grad_cache(var) for var in node.outputs]
   1061     # list of bools indicating if each output is connected to the cost
   1062     outputs_connected = [
   1063         not isinstance(g.type, DisconnectedType) for g in output_grads
   1064     ]

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1059, in <listcomp>(.0)
   1055 if node not in term_dict:
   1057     inputs = node.inputs
-> 1059     output_grads = [access_grad_cache(var) for var in node.outputs]
   1061     # list of bools indicating if each output is connected to the cost
   1062     outputs_connected = [
   1063         not isinstance(g.type, DisconnectedType) for g in output_grads
   1064     ]

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1387, in _populate_grad_dict.<locals>.access_grad_cache(var)
   1384 for node in node_to_idx:
   1385     for idx in node_to_idx[node]:
-> 1387         term = access_term_cache(node)[idx]
   1389         if not isinstance(term, Variable):
   1390             raise TypeError(
   1391                 f"{node.op}.grad returned {type(term)}, expected"
   1392                 " Variable instance."
   1393             )

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/gradient.py:1214, in _populate_grad_dict.<locals>.access_term_cache(node)
   1206         if o_shape != g_shape:
   1207             raise ValueError(
   1208                 "Got a gradient of shape "
   1209                 + str(o_shape)
   1210                 + " on an output of shape "
   1211                 + str(g_shape)
   1212             )
-> 1214 input_grads = node.op.L_op(inputs, node.outputs, new_output_grads)
   1216 if input_grads is None:
   1217     raise TypeError(
   1218         f"{node.op}.grad returned NoneType, expected iterable."
   1219     )

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/graph/op.py:369, in Op.L_op(self, inputs, outputs, output_grads)
    345 def L_op(
    346     self,
    347     inputs: List[Variable],
    348     outputs: List[Variable],
    349     output_grads: List[Variable],
    350 ) -> List[Variable]:
    351     r"""Construct a graph for the L-operator.
    352 
    353     This method is primarily used by `Lop` and dispatches to
   (...)
    367 
    368     """
--> 369     return self.grad(inputs, output_grads)

File ~/miniforge3/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/graph/op.py:343, in Op.grad(self, inputs, output_grads)
    319 def grad(
    320     self, inputs: List[Variable], output_grads: List[Variable]
    321 ) -> List[Variable]:
    322     """Construct a graph for the gradient with respect to each input variable.
    323 
    324     Each returned `Variable` represents the gradient with respect to that
   (...)
    341 
    342     """
--> 343     raise NotImplementedError()

NotImplementedError: 
```

</details>

## Versions and main components

* PyMC/PyMC3 Version: 4.0.0b6 (reproducible also on 3.11.5)
* Aesara/Theano Version: 2.5.1
* Python Version: 3.9.12
* Operating system: MacOS Monterey (arm64)
* How did you install PyMC/PyMC3: conda (probably)

**Comment by ricardoV94** [comment] 2022-04-01 18:04
There's a lot going on here. The important thing is that when you define your own operator you have to define the gradient method yourself.

NUTS is probably not working, but instead PyMC switches to a compound step sampler, with some variables sampled with NUTS and others with Slice

Instead, when you remove the decorator, the function returns normal theano/aesara expresions with conventional `Op`s for which it knows the gradients.

These links explains how to create `Op`s with gradients: 

https://docs.pymc.io/projects/examples/en/latest/case_studies/blackbox_external_likelihood_numpy.html

https://theano-pymc.readthedocs.io/en/latest/extending/extending_theano.html

I am closing this issue as it is not a bug but a user question. Feel free to open a topic on Discourse for help with writing your own Op with a gradient method.

https://discourse.pymc.io/

**Closed as completed** 2022-04-01 18:07 UTC
Labels: question

**Comment by DostalJ** [comment] 2022-04-05 07:45
Thank you, that is all I needed!
Sorry for misusing GitHub Issues.

**Comment by ricardoV94** [comment] 2022-04-05 07:47
No worries, I am glad it was useful
