### ISSUE TITLE
broadcasting in metropolis

### ISSUE THREAD

**Issue by fjaekel** [pymc-devs/pymc#1304] opened 2016-08-26 10:02 UTC
Using explicit shapes sampling with Metropolis throws a mis-match error but NUTS does not.

``` python
from pymc3 import * # pymc 3.0, Theano 0.82
import numpy as np

# some data
x = np.array([0.,1.,2.,3.,4.])

# silly model with infered shapes
with Model() as model:
    a = Uniform('a') # infered shape 
    b = Uniform('b') # infered shape
    X = Exponential('X',lam = a+b,observed=x)

# and no problems with Metropolis
with model:
    step = Metropolis(vars = [a,b])
    trace = sample(100,step=step)

# with explicit shapes
with Model() as model:
    a = Uniform('a',shape=1) # explicit shape
    b = Uniform('b',shape=1) # explicit shape
    X = Exponential('X',lam = a+b,observed=x)

# NUTS works (compiling takes very long)
with model:
    trace = sample(100)

# but sample with Metropolis throws an error
with model:
    step = Metropolis(vars = [a,b])
    trace = sample(100,step=step)
```

I expected `a+b` to be broadcasted but there's a mis-match error:

``` python
ValueError: Input dimension mis-match. (input[0].shape[0] = 5, input[1].shape[0] = 1)
```

I guess that setting the shape explicitly prevents broadcasting, i.e. broadcastable is  `(False,)`. It's confusing that NUTS still works, however.

Even if I try to make `a` and `b` the correct size, I couldn't get it to work:

``` python
with Model() as model:
    a = Uniform('a',shape=1) # explicit shape
    b = Uniform('b',shape=1) # explicit shape
    A = a*np.ones(len(x))
    B = b*np.ones(len(x))
    X = Exponential('X',lam = A+B,observed=x)

# this also throws an error
with model:
    step = Metropolis(vars = [a,b])
    trace = sample(100,step=step)

ValueError: Input dimension mis-match. (input[0].shape[0] = 5, input[1].shape[0] = 1)
```

I could imagine that theano collapses the array of ones to a scalar and that `A` and `B` are therefore not actually of length `len(x)`-- which might explain the error message where one of the inputs only has length 1.

I also tried using `tile` but this resulted in another brodcasting-related error message:

``` python
import theano.tensor as T

with Model() as model:
    a = Uniform('a',shape=1) # explicit shape
    b = Uniform('b',shape=1) # explicit shape
    X = Exponential('X',
                    lam = T.tile(a,len(x))+T.tile(b,len(x)),
                    observed=x)

# now calling Metropolis causes an error already
with model:
    step = Metropolis(vars = [a,b])
    trace = sample(100,step=step)

TypeError: The broadcastable pattern of the input is incorrect for this op. 
Expected (False, True), got (False, False).
```

**Comment by twiecki** [comment] 2016-08-26 10:56
Possible dupe of https://github.com/pymc-devs/pymc3/issues/1083 which has some more thoughts.

**Comment by fjaekel** [comment] 2016-08-26 11:41
Yes, this is definitely the same issue as #1083. I forgot to mention in my post that you need to compute a function of `a` and `b` for the problem to arise. As #1083 also points out, the following works just fine:

``` python
with Model() as model:
    a = Uniform('a',shape=1) # explicit shape
    X = Exponential('X',lam = a,observed=x)
    step = Metropolis(vars = [a])
    trace = sample(100,step=step)
```

**Comment by junpenglao** [comment] 2017-04-16 15:33
For any one running into similar shape related problem in Metropolis, doing below resolved the problem:
```python
lam = a+b
X = Exponential('X', lam = lam.flatten(), observed=x)
```

**Closed as completed** 2018-12-22 12:11 UTC

**Comment by helmutsimon** [comment] 2019-01-02 05:53
I have had a similar problem with the example below (solving linear model with AR residuals without using the timeseries.AR distribution). There is a broadcast error for p=1, not for p>1. The problem does not occur if default NUTS is used, but processing is then much slower. I have tried flattening everything in sight, but it has not helped.

```import numpy as np
from pymc3 import *
from pymc3.distributions.continuous import Normal, HalfNormal
import theano.tensor as tt
from statsmodels.tsa.arima_process import arma_generate_sample
import statsmodels.tsa.api as smt
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt


def run_MCMC_ARp(x, y, draws, p, resmdl):
    phi_means = resmdl.params[:p]
    phi_sd = resmdl.bse[:p]
        
    with Model() as model8:
        alpha = Normal('alpha', mu=0, sd=10) 
        beta = Normal('beta', mu=0, sd=10) 
        sd = HalfNormal('sd', sd=10)
        phi = Normal('phi', mu=phi_means, sd=phi_sd, shape=p)
        y = tt.as_tensor(y)
        x = tt.as_tensor(x)
        y_r = y[p:]
        x_r = x[p:]
        resids = y - beta * x - alpha
        
        u = tt.add(*[phi[i] * resids[p - (i + 1):-(i + 1)] for i in range(p)])
        mu = alpha + beta * x_r + u          
        data = Normal('y_r', mu=mu.flatten(), sd=sd, observed=y_r)

    with model8:
        step = Metropolis([phi])
        tune = int(draws / 5)
        trace = sample(draws, tune=tune, step=step) 
        
    print(summary(trace, varnames=['alpha', 'beta', 'sd', 'phi']))
    plt.show(forestplot(trace, varnames=['alpha', 'beta', 'sd', 'phi']))
    traceplot(trace, varnames=['alpha', 'beta', 'sd', 'phi'])
    return trace


#Generate some data (linear model with AR residuals)
arparams = np.array([0.1, 0.15, 0.2, 0.3])
maparams = np.array([.01, .03, .05])
phi = np.insert(- arparams, 0, 1)
theta = np.insert(maparams, 0, 1)
nsample = 10000
sd = 0.02
residuals = arma_generate_sample(phi, theta, nsample, sd,  burnin=1000)
alpha = .25
beta = .01
x = np.random.rand(nsample)
y = alpha + x * beta + residuals

#Use MCMC to fit an AR(p) model to the data
p = 1
best_mdl = smt.ARMA(residuals, order=(p, 0)).fit(method='mle', trend='nc')
trace = run_MCMC_ARp(x, y, 2000, p, best_mdl)
```
