### ISSUE TITLE
New variables not sampled in posterior predictive when using InferenceData

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/pymc#5695] opened 2022-04-07 11:51 UTC
## Description of your problem

I'm trying to do some predictions and forecasts that involve GPs, and deterministics. I run inference on an initial model, but then for the predictions I have to add new RVs and deterministics that are conditioned on the new time points. This doesn't seem to be possible at the moment.

**Please provide a minimal, self-contained, and reproducible example.**
```python
with pm.Model() as m:
    a = pm.Normal("a")
    b = pm.Normal("b", a, 0.1, observed=np.random.randn(10)* 0.1 + 3)
    ida = pm.sample()
# You sample on one model, then add deterministics on another and try to draw ppc samples
with m:
    d = pm.Deterministic("d", m["a"] - 4)
    c = pm.Normal("c", d, size=5)
    ppc = pm.sample_posterior_predictive(ida, var_names="c")
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_14672/2975257511.py in <module>
      2     d = pm.Deterministic("d", m["a"] - 4)
      3     c = pm.Normal("c", d, size=5)
----> 4     ppc = pm.sample_posterior_predictive(ida, var_names="c")
      5 ppc

~/repos/pymc3/pymc/sampling.py in sample_posterior_predictive(trace, samples, model, var_names, size, keep_size, random_seed, progressbar, mode, return_inferencedata, extend_inferencedata, predictions, idata_kwargs)
   1769                 param = _trace[idx % len_trace]
   1770 
-> 1771             values = sampler_fn(*(param[n] for n in input_names))
   1772 
   1773             for k, v in zip(vars_, values):

~/repos/pymc3/pymc/sampling.py in <genexpr>(.0)
   1769                 param = _trace[idx % len_trace]
   1770 
-> 1771             values = sampler_fn(*(param[n] for n in input_names))
   1772 
   1773             for k, v in zip(vars_, values):

KeyError: 'd'
```

</details>

**Please provide any additional information below.**

## Versions and main components

* PyMC/PyMC3 Version: 4.0.0b6
* Aesara/Theano Version: 2.5.1
* Python Version:
* Operating system:
* How did you install PyMC/PyMC3: (conda/pip)

**Comment by OriolAbril** [comment] 2022-04-07 20:41
Does it work if you use `var_names=["c", "d"]`? I think posterior predictive sampling doesn't draw/recompute deterministics unless explicitly requested, `d` is not on the trace so it needs to be computed in order to be used in `c`. I know there is an issue about sampling deterministics automatically but can't find it right now. @ricardoV94 will know better

**Comment by lucianopaz** [comment] 2022-04-08 11:10
When `"d"` is added to the `var_names`, it works. It also works if `d` isn't wrapped by a `Deterministic`. Anyway, I think that you shouldn't have to explicitly add all intermediate deterministics to be able to draw samples from the posterior predictive. I'll try to dig deeper into this issue

**Comment by ricardoV94** [comment] 2022-04-08 11:19
This is a duplicate of https://github.com/pymc-devs/pymc/issues/5302

**Comment by lucianopaz** [comment] 2022-04-08 11:45
@ricardoV94, it's actually not the same issue as #5302. When the call to `sample` has `return_inferencedata=False`, the above code works. The reason this happens is because the `MultiTrace.varnames` does not include `"d"`, so the `d` tensor is not appended to the `input_names` list (see [here](https://github.com/pymc-devs/pymc/blob/main/pymc/sampling.py#L1738-L1742)). When passing something that isn't a `MultiTrace`, the graph from the requested `var_names` to the leaf nodes is walked, and any tensor that is registered in the model that isn't a leaf RV is stored in the list (see [here](https://github.com/pymc-devs/pymc/blob/main/pymc/sampling.py#L1724-L1730)). We can fix this inconsistency and get posterior_predictives to work in this scenario by simply adding a condition that checks whether `rv.name` is in the `_trace` points. I'll open a PR with this.

**Comment by ricardoV94** [comment] 2022-04-08 11:50
You're right @lucianopaz, we should just use the same logic regardless of the backend, so separate the varnames collection from the model.named_vars collection

**Comment by ricardoV94** [comment] 2022-04-08 11:52
Changed the issue name to better reflect the distinct issue

**Closed as completed** 2022-04-11 14:58 UTC
Labels: bug
