### ISSUE TITLE
idioms for mixture models and inference convergence/speed?

### ISSUE THREAD

**Issue by yarden** [pymc-devs/pymc#1776] opened 2017-02-12 22:43 UTC
I'm having trouble fitting simple Gaussian mixture models in PyMC3. On only 500 data points, default inference (NUTS with advi) takes 3-4 minutes. Metropolis inference doesn't seem to work well on this problem. It's unclear if this is a failure (or bug) of inference, or if it's an issue in the way I've defined the model. The code is [here](https://gist.github.com/yarden/4025ba0e621bb708993a6e436a1b62a3) and the core definition of the mixture uses ``NormalMixture`` (as was suggested by @twiecki [here](https://github.com/pymc-devs/pymc3/issues/1621)):

```
   with pm.Model() as basic_model:
        weights = pm.Dirichlet("weights",
                               np.ones_like(np.ones(num_mixtures)))
        # uniform prior on mean (mu)
        mu = pm.Uniform("mu", mu_min, mu_max, shape=(num_mixtures,))
        # uniform prior on standard deviation (sd)
        sd = pm.Uniform("sd", sd_min, sd_max, shape=(num_mixtures,))
        obs = pm.NormalMixture("obs", weights, mu, sd=sd,#tau=tau,
                               observed=data)
```

Part of the confusion for me in debugging this is that there are several very different ways to define (finite) mixture models in PyMC3 in the documentation and other resources, and it's not clear which one is the "preferred" one -- or at least, which inference approach should be used with each model writing idiom. The different ways of writing simple mixtures I spotted with PyMC3 were:

1. Using explicit categorical variables for assignments (with ``pm.Categorical``), which appears to make the simple ``Metropolis()`` step method fail (as described [here](http://blog.booleanbiotech.com/static/Mixture%20of%20Gaussians%20in%20PyMC3.html) in detail). (It seems that with categorical variables for assignments in the model, one needs either Gibbs sampling or [categorical variable specific steps](https://github.com/pymc-devs/pymc3/issues/443#issuecomment-131806612) to make sampling-based inference work?)
2. Using [``DensityDist`` and custom log-likelihood functions](https://pymc-devs.github.io/pymc3/notebooks/gaussian-mixture-model-advi.html) -- here, ADVI inference is used.
3. Using categorical  [``pm.Potential`` functions](https://pymc-devs.github.io/pymc3/notebooks/gaussian_mixture_model.html) (to solve label-switching problem, it seems).
4. Using``NormalMixture`` (or ``Mixture`` class), without explicitly modeling categorical assignments, as suggested by @twiecki [here](https://github.com/pymc-devs/pymc3/issues/1621).

All these approaches encode essentially the same Gaussian mixture model. It'd be helpful to have some guidelines on the "canonical" solution here, because these models are so frequently used and familiar, and some suggestions about the right inference method to use with each. For instance, why is the default (NUTS + advi) so slow given the way I've written the mixture model? 

Thanks very much.

Best, Yarden

**Comment by twiecki** [comment] 2017-02-13 08:25
That's indeed not explained consistently. Should improve those docs.

4. is the best solution. Does the trace / convergence look OK?

**Comment by aseyboldt** [comment] 2017-02-13 11:33
About the long run time: Most of the time is spent in advi, the number of iterations is way larger than it should be (set n_init to maybe 30000 for this problem). But even then, nuts is quite slow and the effective sample size isn't great either. Part of the problem is the mass matrix. The code uses a diagonal mass matrix, which is appropriate for high dimensional problems, but for a 5 dimensional problem with covariances in the posterior I'd rather use a full mass matrix. Something like this should work better:

```python
with basic_model:
    trace1 = pm.sample(1000, init='advi', n_init=50000, tune=500)
    samples = np.array([basic_model.dict_to_array(p) for p in trace1[500:]])
    cov = np.cov(samples.T)
    step = pm.NUTS(scaling=cov, is_cov=True)
    start = [trace1[-i - 1] for i in [0, 100, 200, 300]]
    trace2 = pm.sample(2000, step=step, init=None, start=start, njobs=4, tune=1000)
```

On my laptop that takes about 1,5min (or 1min on master). Still not great if we compare it to stan, which takes about a minute to compile and then fits the model in 8s

```stan
data {
    int<lower=1> K;
    int<lower=1> N;
    real y[N];
}
parameters {
    simplex[K] theta;
    real mu[K];
    real<lower=0> sigma[K];
}
model {
    real ps[K];
    sigma ~ cauchy(0, 2.5);
    mu ~ normal(0, 10);
    
    for (n in 1:N) {
        for (k in 1:K) {
            ps[k] = log(theta[k]) + normal_lpdf(y[n] | mu[k], sigma[k]);
        }
        target += log_sum_exp(ps);
    }
}
```

I guess reasons for the difference might be:
- stan is using a diagonal mass matrix (I couldn't get it to converge with a full mass matrix) and pymc3 uses a full mass matrix.
- The mass matrix adaptation works differently: stan does its adaptation in the warmup, pymc3 in advi and a separate chain. 
- pymc3 spends time building the computational graph. That's part of the compilation phase for stan
- I guess there is quite a bit of python overhead for small models like this. (eg In the grad evaluations `Split` takes up about 35% of the runtime).

The raw sampling speed after adaptation is about 800 samples/s for stan and 200 samples/s for pymc3 (running only one chain at a time). Gradient evaluations take 120μs for stan and 300μs for pymc3.

**Comment by twiecki** [comment] 2017-02-13 11:51
@aseyboldt Thanks for looking into this. Split is being coded in C: https://github.com/Theano/Theano/pull/5499 If you want, I'd be quite curious if that speeds things up.

I also have a PR that tries to do nuts init more similar to Stan: https://github.com/pymc-devs/pymc3/pull/1738

**Comment by aseyboldt** [comment] 2017-02-13 14:11
Sorry, there was a typo in my stan code. I wrote `log(K)` instead of `log(k)`.

The timings of the gradient evaluations didn't change much, but the posterior is more complicated now.  Stan takes something like 12s for most chains and from time to time the sampler seems to get stuck in a really bad local optimum. I did not observe this with pymc3. I guess using advi to initialize the chains has the advantage (or disadvantage depending on how you want to look at it) that you can force the sampler into a particular region of the posterior.

**Comment by fonnesbeck** [comment] 2017-02-13 14:20
I've been meaning to submit a quick PR that drastically reduces the default `n_init` for ADVI initialization.  It seems like there is very little benefit to running ADVI close to the posterior mode, given what we know about its relationship to the typical set, right? Has anyone played with this at all?

**Comment by twiecki** [comment] 2017-02-13 14:22
Really what we should do is have a dynamic measure of convergence and stop dynamically.

**Comment by fonnesbeck** [comment] 2017-02-13 14:26
We don't require convergence when using ADVI for initialization, do we? All we want is a point that is in or near the typical set, then we let NUTS (or whatever step method) take over and sample.

**Comment by twiecki** [comment] 2017-02-13 14:30
I think the cov matrix is more critical and would feel more comfortable if we had convergence there.

**Comment by yarden** [comment] 2017-02-13 19:04
Thanks for all these comments. I was able to narrow down a case where there appears to be a convergence problem using the recommended method of ``NormalMixture``. The script is: [test_pymc_mixture.py](https://gist.github.com/yarden/4e3edce000ad772449780309eaf0a26d). It runs the same Metropolis-based inference twice on identical data, which gives these very different results (the first set of result appear to be close to the correct posterior mean; the second set of results are very off). It might be a helpful test case. 

I'd be interested in any suggestions you might have on the best way to solve this inference problem in PyMC? I'm not sure ADVI would solve this issue but regardless, having a shorter default initialization sounds like a good idea as @fonnesbeck said.

![pymc-issue](https://cloud.githubusercontent.com/assets/96318/22898432/4c21c49e-f1f5-11e6-929d-84e48575aba2.png)

**Comment by aseyboldt** [comment] 2017-02-14 02:47
This is pretty much expected behaviour. Your posterior has multiple modes (both chains describe "reasonable" explanations for the dataset) and if they are separated by a large enough energy barrier, nuts won't jump between them. If you initialize several chains from the same mode, you can more or less force all of them to end up in the same mode – that's what I wrote earlier –, but nuts and metropolis won't give you an overview about which modes exist.
How to sample from multimodal posteriors is an open question, but tempering should help. I've seen a few papers about using tempering in hamiltonian mcmc, but I don't know of any general purpose implementation. In a low dimensional problem like this you might be able to get away with using some kind of metropolis sampling (maybe using http://dan.iel.fm/emcee/current/user/pt/, which you should be able to feed a pymc3 model).

**Comment by yarden** [comment] 2017-02-14 04:14
I'm not sure the posterior here is multimodal; or at least, I don't think these two modes are equal. It looks to me like the second solution should have a substantially poorer fit to the data - though I'm not sure how to access the log scores in PyMC3? In the first solution, the green Gaussian explains the bulk of the data and the red Gaussian accounts for the "bump" on the right.

**Comment by twiecki** [comment] 2017-02-14 07:35
Mixture models are almost always multi-modal. You could add potentials to break the symmetry (e.g. http://pymc-devs.github.io/pymc3/notebooks/gaussian_mixture_model.html).

**Comment by yarden** [comment] 2017-02-14 14:18
By symmetry you mean multimodes induced by label switching? If so it doesn't look like the two modes PyMC finds in my example are symmetric. I tried to correct for label switching when processing the posterior samples in my code, but I am not sure if this is right ([lines 69-74](https://gist.github.com/yarden/4e3edce000ad772449780309eaf0a26d#file-test_pymc_mixture-py-L69) in code).

**Comment by twiecki** [comment] 2017-02-14 15:05
True, it seems like you legitimately have two modes. At least your plot above strongly suggests so (you need to add the two distributions to see how well it matches the data). These are challenging for sure. You could try SVGD which was recently merged, or, as @aseyboldt suggested emcee (https://github.com/pymc-devs/pymc3/pull/1689). I'm closing this but feel free to ask more questions.

**Closed as completed by twiecki** 2017-02-14 15:05 UTC

**Comment by yarden** [comment] 2017-02-14 16:04
@twiecki thanks. Can you comment on whether my treatment of label switching suffices or whether ``pm.Potential`` needs to be used (like in the [example](http://pymc-devs.github.io/pymc3/notebooks/gaussian_mixture_model.html) you mentioned)?  I.e., can label switching be dealt with post-sampling or does it need to be in the model?

**Comment by twiecki** [comment] 2017-02-14 16:42
No, you need to use Potential in your model, changing the samples later is a bit odd.

**Comment by yarden** [comment] 2017-02-15 02:48
I don't see why modifying the samples afterwards wouldn't achieve the same purpose; I think of label switching as a problem of inference (that affects certain queries to the model), and it seems strange to build a solution for label switching into the model itself. Anyway, I'm not sure I understand the use of ``pm.Potential`` to deal with label switching in the example you linked to and can't find documentation about it (it's mentioned in various GitHub issues). Hopefully the new docs on mixtures will clarify this. I'm happy to try to contribute to docs in whatever way I can but for now I'm still confused about how to properly write down mixtures in PyMC3.
