### ISSUE TITLE
Error installing pymc3 in Windows 10

### ISSUE THREAD

**Issue by rladeira** [pymc-devs/pymc#4128] opened 2020-09-23 17:54 UTC
## Description of your problem

I'm having some trouble trying to properly configure pymc3 in a machine with Windows 10 as the Operating System.

Any advice on how to accomplish this task? Just trying the commands from the documentation didn't work here.

**Please provide a minimal, self-contained, and reproducible example.**

Using conda, I've created a fresh environment with the following commands:

```bash
conda create -n env_pymc3 -c conda-forge cloudpickle ipykernel libpython m2w64-toolchain mkl pygpu theano pymc3 parameterized
```
After the installation, Theano is at least being imported without visible errors.

```python
import theano
```

However, trying to load pymc3 module, an exception is raised:

```python
import pymc3

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-200e74b8195d> in <module>
----> 1 import pymc3

~\anaconda3\envs\env_pymc3\lib\site-packages\pymc3\__init__.py in <module>
     39
     40 from .blocking import *
---> 41 from .distributions import *
     42 from .distributions import transforms
     43 from .glm import *

~\anaconda3\envs\env_pymc3\lib\site-packages\pymc3\distributions\__init__.py in <module>
     13 #   limitations under the License.
     14
---> 15 from . import timeseries
     16 from . import transforms
     17 from . import shape_utils

~\anaconda3\envs\env_pymc3\lib\site-packages\pymc3\distributions\timeseries.py in <module>
     20 import numpy as np
     21
---> 22 from pymc3.util import get_variable_name
     23 from .continuous import get_tau_sigma, Normal, Flat
     24 from .shape_utils import to_tuple

~\anaconda3\envs\env_pymc3\lib\site-packages\pymc3\util.py in <module>
     18
     19 import xarray
---> 20 import arviz
     21 from numpy import asscalar, ndarray
     22

~\anaconda3\envs\env_pymc3\lib\site-packages\arviz\__init__.py in <module>
     26
     27 from .rcparams import rcParams, rc_context
---> 28 from .data import *
     29 from .stats import *
     30 from .plots import *

~\anaconda3\envs\env_pymc3\lib\site-packages\arviz\data\__init__.py in <module>
      1 """Code for loading and manipulating data structures."""
----> 2 from .inference_data import InferenceData, concat
      3 from .io_netcdf import from_netcdf, to_netcdf
      4 from .datasets import load_arviz_data, list_datasets, clear_data_home
      5 from .base import numpy_to_data_array, dict_to_dataset, CoordSpec, DimSpec

~\anaconda3\envs\env_pymc3\lib\site-packages\arviz\data\inference_data.py in <module>
     13 from xarray.core.options import OPTIONS
     14
---> 15 from ..utils import _subset_list, HtmlTemplate
     16 from ..rcparams import rcParams
     17

~\anaconda3\envs\env_pymc3\lib\site-packages\arviz\utils.py in <module>
    668
    669
--> 670 class HtmlTemplate:
    671     """Contain html templates for InferenceData repr."""
    672

~\anaconda3\envs\env_pymc3\lib\site-packages\arviz\utils.py in HtmlTemplate()
    694             """
    695     specific_style = ".xr-wrap{width:700px!important;}"
--> 696     css_template = f"<style> {xr.core.formatting_html.CSS_STYLE}{specific_style} </style>"

AttributeError: module 'xarray.core.formatting_html' has no attribute 'CSS_STYLE'
```

## Versions and main components

* PyMC3 Version: 3.9.3
* Theano Version: 1.0.5
* Python Version: 3.8.5
* Operating system: Windows 10
* How did you install PyMC3: conda

**Comment by MarcoGorelli** [comment] 2020-09-23 18:01
Thanks for the report - duplicate of #4122

**Comment by MarcoGorelli** [comment] 2020-09-30 16:00
@michaelosthege looks like this is fixed now, can it be closed?

**Comment by michaelosthege** [comment] 2020-09-30 16:04
Yes, I think so.

**Closed as completed by michaelosthege** 2020-09-30 16:04 UTC
