### ISSUE TITLE
Model raises exception with floatX=float32

### ISSUE THREAD

**Issue by tdihp** [pymc-devs/pymc#1146] opened 2016-05-26 10:09 UTC
Hi I'm trying to make a model, featuring scan in FreeRV logic. It works with default theano settings but fail when one of the following is set:
- floatX=float32
- mode=DebugMode

Here's the [source code](https://gist.github.com/tdihp/f78739b738ade3ccd5907984194ebcd0)

Using pymc3 master branch with theano 0.8.2

In case of float32, the exception is:

```
  File "puppetmodel.py", line 68, in main
    step = pm.NUTS()
  File "python2.7/site-packages/pymc3/step_methods/nuts.py", line 97, in __init__
    self.leapfrog1_dE = leapfrog1_dE(model.logpt, vars, shared, self.potential, profile=profile)
  File "python2.7/site-packages/pymc3/step_methods/nuts.py", line 209, in leapfrog1_dE
    q1, p1 = leapfrog(H, q, p, 1, e)
  File "python2.7/site-packages/pymc3/step_methods/hmc.py", line 123, in leapfrog
    p = p - (e/2) * -dlogp(q)  # do a half step momentum update to finish off
  File "python2.7/site-packages/pymc3/theanof.py", line 214, in __call__
    return theano.clone(self.tensor, { oldinput : input }, strict=False)

  ...
  File "python2.7/site-packages/theano/gof/op.py", line 633, in __call__
    (i, ins, node))
ValueError: Cannot compute test value: input 0 (Shape.0) of Op Subtensor{int64}(Shape.0, Constant{0}) missing default value
```

while in DebugMode:

```
  File "puppetmodel.py", line 73, in <module>
    main()
  File "puppetmodel.py", line 68, in main
    step = pm.NUTS()
  File "python2.7/site-packages/pymc3/step_methods/nuts.py", line 69, in __init__
    scaling = guess_scaling(Point(scaling, model=model), model=model, vars = vars)
  File "python2.7/site-packages/pymc3/tuning/scaling.py", line 109, in guess_scaling
    h = find_hessian_diag(point, vars, model=model)
  File "python2.7/site-packages/pymc3/tuning/scaling.py", line 103, in find_hessian_diag
    H = model.fastfn(hessian_diag(model.logpt, vars))
  File "python2.7/site-packages/pymc3/memoize.py", line 14, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "python2.7/site-packages/pymc3/theanof.py", line 103, in hessian_diag
    return -t.concatenate([hessian_diag1(f, v) for v in vars], axis=0)
  File "python2.7/site-packages/pymc3/theanof.py", line 94, in hessian_diag1
    return theano.map(hess_ii, idx)[0]
  File "python2.7/site-packages/theano/scan_module/scan_views.py", line 69, in map
    name=name)
  File "python2.7/site-packages/theano/scan_module/scan.py", line 1041, in scan
    scan_outs = local_op(*scan_inputs)
  File "python2.7/site-packages/theano/gof/op.py", line 668, in __call__
    required = thunk()
  File "python2.7/site-packages/theano/scan_module/scan_op.py", line 951, in rval
    r = p(n, [x[0] for x in i], o)
  File "python2.7/site-packages/theano/scan_module/scan_op.py", line 940, in <lambda>
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 415, in theano.scan_module.scan_perform.perform (/home/pp/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.10-64/scan_perform/mod.cpp:4409)
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (/home/pp/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.10-64/scan_perform/mod.cpp:4193)
  File "python2.7/site-packages/theano/compile/debugmode.py", line 2279, in deco
    return f()
  File "python2.7/site-packages/theano/compile/debugmode.py", line 1936, in f
    "%s" % (r, storage_map[r][0])))
theano.compile.debugmode.InvalidValueError: InvalidValueError
        type(variable) = TensorType(float32, scalar)
        variable       = TensorConstant{-inf}
        type(value)    = <type 'numpy.ndarray'>
        dtype(value)   = float32
        shape(value)   = ()
        value          = -inf
        min(value)     = -inf
        max(value)     = -inf
        isfinite       = False
        client_node    = None
        hint           = Graph Input 'TensorConstant{-inf}' has invalid value -inf
        specific_hint  = none
        context        = ...
  TensorConstant{-inf} [id A]
```

It would be very nice if somebody help me out, thanks.

**Comment by twiecki** [comment] 2016-05-26 10:46
@nouiz any idea?

**Comment by nouiz** [comment] 2016-05-26 15:09
The error with floatX=float32 is due to an error in your code or pymc3. Mostly, Theano compute_test_value is enabled automatically by PyMC3 and one input variable don't have test value. This cause this error.

http://deeplearning.net/software/theano/tutorial/debug_faq.html#using-test-values

The one in DebugMode is that one input of the Theano function is -inf and DebugMode raise an error in that case. If that is expected, you can use this Theano flag to tell DebugMode to not raise error for inf/nan: DebugMode.check_finite=False

**Comment by tdihp** [comment] 2016-05-27 02:22
Thanks @nouiz.

So floatX=float32 exception is likely because some input variable don't have test value, but in default float64 setting theano took a different path, so the test never occurred?

I'm quite sure my model has only one nonlinear function which is `tanh`, which is smooth, so `-inf` should be a valid error to me.

I'm having a hard time locating the bad theano variable, is there some good way to do this kind of debug?

**Comment by tdihp** [comment] 2016-05-27 09:44
update:

I've found why the test_value exception raised:
`leapfrog1_dE` in `nuts.py` used `dscalar` and `dvector`.

However after remove the 'initial d's there's more exception, continuing.

**Comment by twiecki** [comment] 2016-08-11 17:39
This should be fixed now.

**Closed as completed by twiecki** 2016-08-11 17:39 UTC

**Comment by skatenerd** [comment] 2017-03-29 18:49
I'm seeing very similar behavior with `Theano == 0.9.0` and `3.1rc3`.  The problem goes away when I remove `floatX=float32`.  I'm not sure if this is the right place to ask for help (vs the Theano repo).  

I can get by right now by removing the `floatX` flag, but I'm a new user and I'm not sure if it's safe to do that and keep moving forward.

In any case, I thought you might like to know that the fix may have been incomplete, as the `NUTS` sampler is crashing under similar circumstances.

```
  File "go.py", line 10, in go
    trace = sample(self.simulations, NUTS())
  File "/usr/local/lib/python2.7/dist-packages/pymc3/sampling.py", line 193, in sample
    return sample_func(**sample_args)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/sampling.py", line 210, in _sample
    for it, strace in enumerate(sampling):
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 833, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python2.7/dist-packages/pymc3/sampling.py", line 309, in _iter_sample
    point, states = step.step(point)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/step_methods/arraystep.py", line 151, in step
    apoint, stats = self.astep(bij.map(point))
  File "/usr/local/lib/python2.7/dist-packages/pymc3/step_methods/hmc/nuts.py", line 173, in astep
    diverging, turning = tree.extend(direction)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/step_methods/hmc/nuts.py", line 264, in extend
    self.right, self.depth, floatX(np.asarray(self.step_size)))
  File "/usr/local/lib/python2.7/dist-packages/pymc3/step_methods/hmc/nuts.py", line 314, in _build_subtree
    tree2, diverging, turning = self._build_subtree(tree1.right, depth - 1, epsilon)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/step_methods/hmc/nuts.py", line 293, in _build_subtree
    right = self.leapfrog(left.q, left.p, left.q_grad, epsilon)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
TypeError: expected type_num 11 (NPY_FLOAT32) got 12
Apply node that caused the error: Elemwise{Composite{(i0 + (i1 * i2 * i3))}}(p, TensorConstant{(1,) of 0.5}, InplaceDimShuffle{x}.0, <TensorT
ype(float64, vector)>)
Toposort index: 7
Inputs types: [TensorType(float32, vector), TensorType(float64, (True,)), TensorType(float32, (True,)), TensorType(float64, vector)]
Inputs shapes: [(20,), (1,), (1,), (20,)]
Inputs strides: [(8,), (8,), (4,), (8,)]
Inputs values: ['not shown', array([ 0.5]), array([ 0.1182177], dtype=float32), 'not shown']
Outputs clients: [[Elemwise{Composite{(i0 + (i1 * i2 * i3))}}(Elemwise{Composite{(i0 + (i1 * i2 * i3))}}.0, TensorConstant{(1,) of 0.5}, Inpl
aceDimShuffle{x}.0, Reshape{1}.0), Elemwise{Composite{(i0 + (i1 * i2 * i3))}}[(0, 3)](inarray, InplaceDimShuffle{x}.0, TensorConstant{[ 0.004
739...00552486]}, Elemwise{Composite{(i0 + (i1 * i2 * i3))}}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by s
etting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by twiecki** [comment] 2017-03-29 19:00
Can you post the model? Possibly you don't input float32 values everywhere (e.g. test-values).

**Comment by skatenerd** [comment] 2017-03-29 19:35
The code is proprietary, and I haven't had the time to find a minimal example that reproduces the problem.

However, this is only happening in unit-test and not in production, so your theory about float32 ("test") values sounds promising.

Could you link me to some background resources on the concept of "test-values"?

**Comment by twiecki** [comment] 2017-03-30 12:16
Basically, all data you input into PyMC3 must be float32, for example:
`pm.Normal('x', mu=np.asarray([0, 0, 0]).astype('float32'), sd=np.asarray([1, 1, 1]).astype('float32'), test_value=np.asarray([0, 0, 0]).astype('float32'))`.

**Comment by michaelosthege** [comment] 2017-09-21 11:31
The issue seems to be with 0-constant:

```python
import pymc3

#u = pymc3.Uniform.dist(lower=0.01, upper=1.4) # FAIL (missing test value)
#u = pymc3.Uniform.dist(lower=0.01, upper=1.4, testval=0.5)     # OK
#u = pymc3.Uniform.dist(lower=0.01, upper=1.4, testval=2.2)     # OK
#u = pymc3.Uniform.dist(lower=0.01, upper=11.4, testval=2.2)    # OK
#u = pymc3.Uniform.dist(lower=0.01, upper=10.6545, testval=2.2) # OK
#u = pymc3.Uniform.dist(lower=0.01, upper=10.5123, testval=2.2) # OK
#u = pymc3.Uniform.dist(lower=0.01, upper=10.5000, testval=2.2)  # FAIL (cannot compute test value)
#u = pymc3.Uniform.dist(lower=0.0, upper=1.4, testval=0.5)      # FAIL (cannot compute test value)

with pymc3.Model() as pmodel:
    #pymc3.Uniform("u", lower=0.0, upper=1.4, testval=0.5)
    pmodel.Var("u", u)
```

Might be worth to create a separate issue for it...

EDIT: it's even weirder. There seem to be some magic numbers that cause trouble. (float precision?)

Also see #2589
