### ISSUE TITLE
discreteuniform not working

### ISSUE THREAD

**Issue by majidaldo** [pymc-devs/pymc#1412] opened 2016-09-29 18:00 UTC
Am I missing something here?!

```
model = pm.Model()

with model:

    x= pm.DiscreteUniform('x',lower=0,upper=10)
    pm.sample(10)
```

```
Assigned Metropolis to x
Truncated Traceback (Use C-c C-x to view full TB):
C:\Users\Majid\Miniconda\envs\schedule34\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    857         t0_fn = time.time()
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:
    861             if hasattr(self.fn, 'position_of_error'):

TypeError: expected type_num 9 (NPY_INT64) got 7
Apply node that caused the error: Elemwise{Composite{(Switch((GE(i0, i1) * LE(i0, i2)), i3, i4) - Switch((GE(i5, i1) * LE(i5, i2)), i3, i4))}}(Subtensor{int64}.0, TensorConstant{0}, TensorConstant{24}, TensorConstant{-3.2188758248682006}, TensorConstant{-inf}, Subtensor{int64}.0)
Toposort index: 2
Inputs types: [TensorType(int64, scalar), TensorType(int32, scalar), TensorType(int32, scalar), TensorType(float64, scalar), TensorType(float32, scalar), TensorType(int64, scalar)]
Inputs shapes: [(), (), (), (), (), ()]
Inputs strides: [(), (), (), (), (), ()]
Inputs values: [array(12), array(0), array(24), array(-3.2188758248682006), array(-inf, dtype=float32), array(12)]
Outputs clients: [['output']]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by fonnesbeck** [comment] 2016-09-29 18:41
I can't replicate this here:

```
model = pm.Model()

with model:

    x= pm.DiscreteUniform('x',lower=0,upper=10)
    pm.sample(10)

## -- End pasted text --
Assigned Metropolis to x
 [-----------------100%-----------------] 10 of 10 complete in 0.0 sec
```

Things to try:
- delete your `~/.theano` directory
- ensure you are using PyMC3 built from master
- ensure you are using Theano from master

**Comment by majidaldo** [comment] 2016-09-29 19:51
sigh. I do. I deleted the theano cache. Here's the full traceback. 

It might go away if a make a new computing environment.

```
Assigned Metropolis to x
-------------------------------------------------------------------------
TypeError                               Traceback (most recent call last)
C:\Users\Majid\Miniconda\envs\schedule34\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    865             outputs =\
--> 866                 self.fn() if output_subset is None else\
    867                 self.fn(output_subset=output_subset)

TypeError: expected type_num 9 (NPY_INT64) got 7

During handling of the above exception, another exception occurred:

TypeError                               Traceback (most recent call last)
<ipython-input-2-178528eff1c9> in <module>()
      4 
      5     x= pm.DiscreteUniform('x',lower=0,upper=10)
----> 6     pm.sample(10)

C:\Users\Majid\Miniconda\envs\schedule34\lib\site-packages\pymc3\sampling.py in sample(draws, step, start, trace, chain, njobs, tune, progressbar, model, random_seed)
    153         sample_func = _sample
    154 
--> 155     return sample_func(**sample_args)
    156 
    157 

C:\Users\Majid\Miniconda\envs\schedule34\lib\site-packages\pymc3\sampling.py in _sample(draws, step, start, trace, chain, tune, progressbar, model, random_seed)
    162     progress = progress_bar(draws)
    163     try:
--> 164         for i, strace in enumerate(sampling):
    165             if progressbar:
    166                 progress.update(i)

C:\Users\Majid\Miniconda\envs\schedule34\lib\site-packages\pymc3\sampling.py in _iter_sample(draws, step, start, trace, chain, tune, model, random_seed)
    245         if i == tune:
    246             step = stop_tuning(step)
--> 247         point = step.step(point)
    248         strace.record(point)
    249         yield strace

C:\Users\Majid\Miniconda\envs\schedule34\lib\site-packages\pymc3\step_methods\arraystep.py in step(self, point)
    140         bij = DictToArrayBijection(self.ordering, point)
    141 
--> 142         apoint = self.astep(bij.map(point))
    143         return bij.rmap(apoint)
    144 

C:\Users\Majid\Miniconda\envs\schedule34\lib\site-packages\pymc3\step_methods\metropolis.py in astep(self, q0)
    135             q = q0 + delta
    136 
--> 137         q_new = metrop_select(self.delta_logp(q, q0), q, q0)
    138 
    139         if q_new is q:

C:\Users\Majid\Miniconda\envs\schedule34\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    877                     node=self.fn.nodes[self.fn.position_of_error],
    878                     thunk=thunk,
--> 879                     storage_map=getattr(self.fn, 'storage_map', None))
    880             else:
    881                 # old-style linkers raise their own exceptions

C:\Users\Majid\Miniconda\envs\schedule34\lib\site-packages\theano\gof\link.py in raise_with_op(node, thunk, exc_info, storage_map)
    323         # extra long error message in that case.
    324         pass
--> 325     reraise(exc_type, exc_value, exc_trace)
    326 
    327 

C:\Users\Majid\Miniconda\envs\schedule34\lib\site-packages\six.py in reraise(tp, value, tb)
    683             value = tp()
    684         if value.__traceback__ is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value
    687 

C:\Users\Majid\Miniconda\envs\schedule34\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    864         try:
    865             outputs =\
--> 866                 self.fn() if output_subset is None else\
    867                 self.fn(output_subset=output_subset)
    868         except Exception:

TypeError: expected type_num 9 (NPY_INT64) got 7
Apply node that caused the error: Elemwise{Composite{(Switch(Identity((GE(i0, i1) * LE(i0, i2))), i3, i4) - Switch(Identity((GE(i5, i1) * LE(i5, i2))), i3, i4))}}(InplaceDimShuffle{}.0, TensorConstant{0}, TensorConstant{10}, TensorConstant{-2.3978952727983707}, TensorConstant{-inf}, InplaceDimShuffle{}.0)
Toposort index: 2
Inputs types: [TensorType(int64, scalar), TensorType(int32, scalar), TensorType(int32, scalar), TensorType(float64, scalar), TensorType(float32, scalar), TensorType(int64, scalar)]
Inputs shapes: [(), (), (), (), (), ()]
Inputs strides: [(), (), (), (), (), ()]
Inputs values: [array(5), array(0), array(10), array(-2.3978952727983707), array(-inf, dtype=float32), array(5)]
Outputs clients: [['output']]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by fonnesbeck** [comment] 2016-09-29 19:54
Yeah, try making a new virtualenv with `conda`. This appears to be the same as #994

**Comment by majidaldo** [comment] 2016-10-02 23:15
looks like the similar errors are all from windows users

**Comment by fonnesbeck** [comment] 2016-10-18 19:59
Closing as duplicate of #994

**Closed as completed by fonnesbeck** 2016-10-18 19:59 UTC
