### ISSUE TITLE
BUG: Flaky test `test_truncation_specialized_op`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#6384] opened 2022-12-11 14:38 UTC
### Describe the issue:

It failed in #6304 and on main: https://github.com/pymc-devs/pymc/actions/runs/3665014447/jobs/6195812078

### Reproduceable code example:

```python
pytest -v pymc/tests/distributions/test_truncated.py::test_truncation_specialized_op
```

### Error message:

```shell
FAILED pymc/tests/distributions/test_truncated.py::test_truncation_specialized_op[observed] - assert False
 +  where False = isinstance(<pytensor.tensor.elemwise.Elemwise object at 0x7fdf5924e1a0>, TruncatedNormalRV)
 +    where <pytensor.tensor.elemwise.Elemwise object at 0x7fdf5924e1a0> = Elemwise{identity}(AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=True}.0).op
 +      where Elemwise{identity}(AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=True}.0) = xt.owne
```

### PyMC version information:

main

**Comment by ricardoV94** [comment] 2022-12-14 07:15
I cannot reproduce the failure locally. Could it be Windows specific?

**Comment by ricardoV94** [comment] 2022-12-14 10:42
Failed again in https://github.com/pymc-devs/pymc/actions/runs/3693633480/jobs/6253850355

It is very strange. Looks like the dispatch may be broken?

**Comment by michaelosthege** [comment] 2022-12-14 17:30
Just a wild speculation, but what if somewhere during graph rewrites there's a non-deterministic order of operations? Could happen by iterating over a set, for example.

**Comment by larryshamalama** [comment] 2023-01-07 13:30
Just to chip in after some weeks: I still can't reproduce this bug locally... I found out that it just failed recently again [here](https://github.com/pymc-devs/pymc/actions/runs/3861238203/jobs/6582091526)

**Comment by larryshamalama** [comment] 2023-02-03 15:27
@michaelosthege With your recent PR merged, this test seems to now pass...? Did you make any change to the test or the code?

https://github.com/pymc-devs/pymc/actions/runs/4084608130/jobs/7041511557#step:7:34

**Comment by ricardoV94** [comment] 2023-02-03 15:36
This is flaky, I wouldn't read to much to it having passed once

**Comment by michaelosthege** [comment] 2023-02-03 15:37
AFAIK this test is still flaky - I just got lucky in my PR and merge. Also, my PR was unrelated

**Comment by ricardoV94** [comment] 2023-02-14 09:21
Found the reason, that tests sets `observed=np.empty(100)`, which sometimes PyMC converts to a maskedarray, and then we get automatic imputation on the TruncatedRV! It's non deterministic, because it depends on the contents of  `np.empty`

**Comment by larryshamalama** [comment] 2023-02-14 15:00
I see the non deterministic aspect of `np.empty(100)`, but why would this inhibit substitution the Op to a `TruncatedNormalRV`?

**Comment by ricardoV94** [comment] 2023-02-14 15:38
Because when there are `nan` in the observation the automatic imputation in PyMC is triggered. The variable returned after automatic-imputation is not a pure RV, but a set_subtensor that joins the observed and missing components of the partially observed RV

**Comment by larryshamalama** [comment] 2023-02-14 15:49
> Because when there are `nan` in the observation the automatic imputation in PyMC is triggered. The variable returned after automatic-imputation is not a pure RV, but a set_subtensor that joins the observed and missing components of the partially observed RV

AHHHHHHHH, great that you have figured this out 👏 

However, would this potentially cause problems elsewhere when imputing for `nan`s before performing `node_rewrite`s?

**Comment by ricardoV94** [comment] 2023-02-14 15:50
Imputing for `nan` is the correct behavior. The problem is the test did not expect this to happen (that was not the point of the test)

**Closed as completed** 2023-02-15 07:56 UTC
Labels: bug, tests, needs info
