### ISSUE TITLE
"Advanced usage of Theano in PyMC3" seems to be broken

### ISSUE THREAD

**Issue by DeliciousHair** [pymc-devs/pymc#3832] opened 2020-03-17 14:31 UTC
I am attempting to create my own custom theano Op, using the [provided example](https://docs.pymc.io/Advanced_usage_of_Theano_in_PyMC3.html) as a roadmap. However, the example seems to be broken at present.

In particular:
```python
>>> theano.config.compute_test_value = 'ignore'
>>> theano.tests.unittest_tools.verify_grad(MuFromTheta(), (np.array(0.2),))

GradientErrorTraceback (most recent call last)
<ipython-input-19-73c57006efe2> in <module>
      1 theano.config.compute_test_value = 'ignore'
----> 2 theano.tests.unittest_tools.verify_grad(MuFromTheta(), (np.array(0.2),))

/usr/local/lib/python3.7/dist-packages/theano/tests/unittest_tools.py in verify_grad(op, pt, n_tests, rng, *args, **kwargs)
     90         seed_rng()
     91         rng = np.random
---> 92     T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)
     93 
     94 #

/usr/local/lib/python3.7/dist-packages/theano/gradient.py in verify_grad(fun, pt, n_tests, rng, eps, out_type, abs_tol, rel_tol, mode, cast_to_output_type, no_debug_ref)
   1793                                          num_grad.gf[max_arg].flatten()[max_err_pos],
   1794                                          max_abs_err, max_rel_err,
-> 1795                                          abs_tol, rel_tol)
   1796 
   1797             # get new random projection for next test

GradientError: GradientError: numeric gradient and analytic gradient exceed tolerance:
        At position 0 of argument 0 with shape (),
            val1 = -0.123826      ,  val2 = 0.000000
            abs. error = 0.123826,  abs. tolerance = 0.000100
            rel. error = 1.000000,  rel. tolerance = 0.000100
Exception args: 
The error happened with the following inputs:, [array(0.2)], 
The value of eps is:, None, 
The out_type is:, None
```

Really not sure what the problem is here, but it does impact as the end result at the end of the demo is complete junk as a result.

environment:
ubuntu 19.10 (docker)
pymc3 3.8
theano 1.0.4
numpy 1.18.1

All python libraries installed via pip (as opposed to apt)

**Comment by brandonwillard** [comment] 2020-03-17 16:47
If you can provide a complete [MWE](https://en.wikipedia.org/wiki/Minimal_working_example), we might be able to help you debug it.  In other words, what changes did you make to the example?

**Comment by DeliciousHair** [comment] 2020-03-17 21:00
Absolutely! However, I am simply using the code from the tutorial directly:

```python
import numpy as np

import theano
import theano.tensor as tt
import theano.tests.unittest_tools

from scipy import optimize, special


def func(mu, theta):
    thetamu = theta * mu
    value = np.log(mu) + np.logaddexp(0, thetamu)
    return value

def jac(mu, theta):
    thetamu = theta * mu
    jac = theta * special.expit(thetamu) + 1 / mu
    return jac

def mu_from_theta(theta):
    return optimize.newton(func, 1, fprime=jac, args=(0.4,))


class MuFromTheta(tt.Op):
    itypes = [tt.dscalar]
    otypes = [tt.dscalar]

    def perform(self, node, inputs, output):
        theta, = inputs
        mu = mu_from_theta(theta)
        output[0][0] = np.array(mu)

    def grad(self, inputs, g):
        theta, = inputs
        mu = self(theta)
        thetamu = theta * mu
        return [- g[0] * mu ** 2 / (1 + thetamu + tt.exp(-thetamu))]
```

Attempting to do:
```python
>>> theano.config.compute_test_value = 'ignore'
>>> theano.tests.unittest_tools.verify_grad(MuFromTheta(), (np.array(0.2),))
```

will lead to the error in the first post. In terms of junk results (maybe they're not, just seems so), if we ignore the issue in the `grad()` calculation and push ahead, it leads to:

```python
import pymc3 as pm

tt_mu_from_theta = MuFromTheta()

with pm.Model() as model:
    theta = pm.HalfNormal('theta', sigma=1)
    mu = pm.Deterministic('mu', tt_mu_from_theta(theta))
    pm.Normal('y', mu=mu, sigma=0.1, observed=[0.2, 0.21, 0.3])

    trace = pm.sample()
```
```python
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [theta]
Sampling 4 chains, 0 divergences: 100%|██████████| 4000/4000 [03:15<00:00, 20.44draws/s] 
The chain reached the maximum tree depth. Increase max_treedepth, increase target_accept or reparameterize.
The chain reached the maximum tree depth. Increase max_treedepth, increase target_accept or reparameterize.
The rhat statistic is larger than 1.2 for some parameters.
The estimated number of effective samples is smaller than 200 for some parameters.
```
![image](https://user-images.githubusercontent.com/6540809/76900936-65f0b380-68ee-11ea-90cd-3fe259a1f7f1.png)

**EDIT**
In fact, there is nothing wrong with `grad()` at all, been looking in the wrong place! Typo is in `mu_from_theta()`, which should be:

```python
def mu_from_theta(theta):
    return optimize.newton(func, 1, fprime=jac, args=(theta,))
```

and all is then well.

**Comment by brandonwillard** [comment] 2020-03-17 22:39
Ah, yeah, I get the same `GradientError`.  

Looks like this issue could be caused by any number of things (e.g. typo in the `mu_from_theta`/`MuFromTheta.grad` math, discrepancy between the Newton-Raphson estimation in `mu_from_theta` and Theano's hand-built finite difference gradient function used by `verify_grad`, etc.)

Regarding the purpose of that example, I'm not seeing any obvious problems involving the creation of a custom `tt.Op`.  A custom `tt.Op` seems to have been created properly, even if the example calculation isn't matching the test.  

In the meantime, if you're interested, check out [Theano's own examples for a custom `tt.Op`](http://deeplearning.net/software/theano/extending/extending_theano.html).

**Comment by brandonwillard** [comment] 2020-03-17 22:41
Ah, just saw your edit.  If you want, please, put in a PR for that fix and we can close this when it's merged.

**Closed as completed** 2020-03-17 23:43 UTC
