### ISSUE TITLE
situation where posterior predictive sampling does not work when changing the shape of observed data

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc#5666] opened 2022-03-28 18:12 UTC
## Description of your problem
Posterior predictive sampling is not working in all cases when shape of observed data is changed.

### What does _not_ work

```python
import pymc as pm
import numpy as np

x = np.random.randn(100)
y = 0 + 1 * x + np.random.randn(100)*0.2

with pm.Model() as model:
    sigma = pm.HalfNormal("sigma")
    β0 = pm.Normal("β0", mu=0, sigma=1)
    β1 = pm.Normal("β1", mu=0, sigma=1)
    _x = pm.MutableData("x", x, dims='obs_id')
    mu = pm.Deterministic("mu", β0 + β1 * _x, dims='obs_id')
    pm.Normal("y", mu=mu, sigma=sigma, observed=y, dims='obs_id')
    idata = pm.sample()
    
# posterior predictive inference
N = 20
with model:
    xi = np.linspace(np.min(x), np.max(x), N)
    pm.set_data({"x": xi})
    idata.extend(pm.sample_posterior_predictive(idata))
    
assert idata.posterior_predictive.dims['obs_id'] == N
```

The assertion fails, `obs_id` has the original data length, not the new length of `N`. And this happens despite labelling the dims of `mu`.

### What _does_ work
If you force `mu` to be sampled (by adding `var_names` to `pm.sample_posterior_predictive`), then it does work. 

```python
with pm.Model() as model:
    sigma = pm.HalfNormal("sigma")
    β0 = pm.Normal("β0", mu=0, sigma=1)
    β1 = pm.Normal("β1", mu=0, sigma=1)
    _x = pm.MutableData("x", x, dims='obs_id')
    mu = pm.Deterministic("mu", β0 + β1 * _x, dims='obs_id')
    pm.Normal("y", mu=mu, sigma=sigma, observed=y, dims='obs_id')
    idata = pm.sample()
    
# posterior predictive inference
N = 20
with model:
    xi = np.linspace(np.min(x), np.max(x), N)
    pm.set_data({"x": xi})
    idata.extend(pm.sample_posterior_predictive(idata, var_names=['y', 'mu']))
    
assert idata.posterior_predictive.dims['obs_id'] == N
```
The assertion passes.

It also works if you make `mu` not a deterministic.

Whether this is classified as a bug or undesirable behaviour, I do not know. Either way I think preferable behaviour would be if the first example did work.

## Versions and main components

Python implementation: CPython
Python version       : 3.9.9
IPython version      : 7.31.0

pymc  : 4.0.0b5
aesara: 2.5.1

Compiler    : Clang 11.1.0 
OS          : Darwin
Release     : 21.4.0
Machine     : x86_64
Processor   : i386
CPU cores   : 8
Architecture: 64bit

**Comment by ricardoV94** [comment] 2022-03-28 18:27
Sounds like a duplicate of #5302

**Closed as completed** 2022-03-28 18:29 UTC
