### ISSUE TITLE
ADVI fit not reproducible

### ISSUE THREAD

**Issue by chdamianos** [pymc-devs/pymc#3395] opened 2019-03-07 09:47 UTC
## Description of your problem
When I restart the Jupyter Python kernel and repeat a model fit with `pm.fit(method='fullrank_advi')` the results are not reproducible, whereas the model fit with `pm.sample()` is reproducible.

Running the following code (in the same kernel) I get both repeatable and reproducible results for both `pm.fit(method='fullrank_advi')`  and `pm.sample()`
```python
import numpy as np
import pymc3 as pm
import pandas as pd 
import pickle
np.random.seed(1234)

# model
n = 20 # The number of data points
x = np.linspace(0, 10, n)
X = x[:, None] # The inputs to the GP, they must be arranged as a column vector
# Define the true covariance function and its parameters
c_true = 0.0
cov_func = pm.gp.cov.Constant(c_true)
# A mean function that is constant everywhere
mean_true = 10
mean_func = pm.gp.mean.Constant(mean_true)
# The latent function values are one sample from a multivariate normal
f_true = np.random.multivariate_normal(mean_func(X).eval(), 
                                       cov_func(X).eval(), 1).flatten()
# The observed data is the latent function plus a small amount of IID Gaussian noise
# The standard deviation of the noise is sigma_true
sigma_true = 2.0
y = f_true + sigma_true * np.random.randn(n)
with pm.Model() as model:    
    # Gaussian process parameters
    mean = pm.Uniform("mean", lower=0, upper=20)   
    cov =  pm.gp.cov.Constant(0)
    mean = pm.gp.mean.Constant(c=mean)
    gp = pm.gp.Marginal(mean_func=mean, cov_func=cov)
    # likelihood
    sigma = pm.HalfCauchy("sigma", beta=5)
    obs = gp.marginal_likelihood("obs", X=X, y=y, noise=sigma)
# mcmc
mcmcResults = []
for _ in range(5):
    with model:
        mcmc_trace = pm.sample(5000, njobs = 1, chains=1, random_seed=1234)
        flatTrace = []
        for varname in mcmc_trace.varnames:
            flatTrace = flatTrace + list(mcmc_trace.get_values(varname).flatten())
        mcmcResults.append(np.array(flatTrace))
print('mcmc is reapeatable ? {}'.format((mcmcResults==mcmcResults[0]).all()))

# advi
adviResults=[]
for _ in range(5):
    with model:
        advi_fit = pm.fit(n=10000, method='fullrank_advi', random_seed=1234,
                         callbacks=[pm.callbacks.CheckParametersConvergence(diff='absolute',tolerance=0.001)])
        advi_trace = advi_fit.sample(5000)
        flattenValues = []
        for varname in advi_trace.varnames:
            flattenValues = flattenValues + list(advi_trace.get_values(varname).flatten())
        adviResults.append(np.array(flattenValues))
print('advi is reapeatable ? {}'.format((adviResults==adviResults[0]).all()))
# save repeatability results
resultsDict = {'adviResults' : adviResults,'mcmcResults' : mcmcResults}
f = open('repeatability_results.p','wb')
pickle.dump(resultsDict, f)
f.close()

# load results for reproducibility runs 
f = open('repeatability_results.p','rb')
previousResults = pickle.load(f)
f.close()
# mcmc
mcmcResults = []
for _ in range(5):
    with model:
        mcmc_trace = pm.sample(5000, njobs = 1, chains=1, random_seed=1234)
        flatTrace = []
        for varname in mcmc_trace.varnames:
            flatTrace = flatTrace + list(mcmc_trace.get_values(varname).flatten())
        mcmcResults.append(np.array(flatTrace))
mcmcResultsPrevious = previousResults['mcmcResults']
print('mcmc is reproducible? {}'.format((mcmcResultsPrevious == mcmcResults[0]).all()))

# advi
adviResults=[]
for _ in range(5):
    with model:
        advi_fit = pm.fit(n=10000, method='fullrank_advi', random_seed=1234,
                         callbacks=[pm.callbacks.CheckParametersConvergence(diff='absolute',tolerance=0.001)])
        advi_trace = advi_fit.sample(5000)
        flattenValues = []
        for varname in advi_trace.varnames:
            flattenValues = flattenValues + list(advi_trace.get_values(varname).flatten())
        adviResults.append(np.array(flattenValues))
adviResultsPrevious = previousResults['adviResults']
print('advi is reproducible? {}'.format((adviResultsPrevious == adviResults[0]).all())) 
```
 When I restart the Python kernel (from Jupyter select Kernel and then Restart & Clear Output) and run it again loading the previous results (from `repeatability_results.p`) the `pm.fit(method='fullrank_advi')` is not reproducible but `pm.sample()` is reproducible.
```python
import numpy as np
import pymc3 as pm
import pandas as pd 
import pickle
np.random.seed(1234)

# model
n = 20 # The number of data points
x = np.linspace(0, 10, n)
X = x[:, None] # The inputs to the GP, they must be arranged as a column vector
# Define the true covariance function and its parameters
c_true = 0.0
cov_func = pm.gp.cov.Constant(c_true)
# A mean function that is constant everywhere
mean_true = 10
mean_func = pm.gp.mean.Constant(mean_true)
# The latent function values are one sample from a multivariate normal
f_true = np.random.multivariate_normal(mean_func(X).eval(), 
                                       cov_func(X).eval(), 1).flatten()
# The observed data is the latent function plus a small amount of IID Gaussian noise
# The standard deviation of the noise is sigma_true
sigma_true = 2.0
y = f_true + sigma_true * np.random.randn(n)
with pm.Model() as model:    
    # Gaussian process parameters
    mean = pm.Uniform("mean", lower=0, upper=20)   
    cov =  pm.gp.cov.Constant(0)
    mean = pm.gp.mean.Constant(c=mean)
    gp = pm.gp.Marginal(mean_func=mean, cov_func=cov)
    # likelihood
    sigma = pm.HalfCauchy("sigma", beta=5)
    obs = gp.marginal_likelihood("obs", X=X, y=y, noise=sigma)

f = open('repeatability_results.p','rb')
previousResults = pickle.load(f)
f.close()

# mcmc
mcmcResults = []
for _ in range(5):
    with model:
        mcmc_trace = pm.sample(5000, njobs = 1, chains=1, random_seed=1234)
        flatTrace = []
        for varname in mcmc_trace.varnames:
            flatTrace = flatTrace + list(mcmc_trace.get_values(varname).flatten())
        mcmcResults.append(np.array(flatTrace))
mcmcResultsPrevious = previousResults['mcmcResults']
print('mcmc is reproducible? {}'.format((mcmcResultsPrevious == mcmcResults[0]).all()))

# advi
adviResults=[]
for _ in range(5):
    with model:
        advi_fit = pm.fit(n=10000, method='fullrank_advi', random_seed=1234,
                         callbacks=[pm.callbacks.CheckParametersConvergence(diff='absolute',tolerance=0.001)])
        advi_trace = advi_fit.sample(5000)
        flattenValues = []
        for varname in advi_trace.varnames:
            flattenValues = flattenValues + list(advi_trace.get_values(varname).flatten())
        adviResults.append(np.array(flattenValues))
adviResultsPrevious = previousResults['adviResults']
print('advi is reproducible? {}'.format((adviResultsPrevious == adviResults[0]).all())) 
```

## Versions and main components

* PyMC3 Version: 3.6
* Theano Version: 1.0.3
* Python Version: 3.6.8
* Operating system: Windows-10-10.0.17134-SP0
* How did you install PyMC3: (conda/pip) I used the following conda env `pymc3GP.yml` file
```yml
name: pymc3GP
dependencies:
  - python
  - cloudpickle
  - ipykernel
  - mingw
  - libpython
  - m2w64-toolchain
  - mkl=2017
  - pygpu
  - theano
  - pymc3
  - parameterized
```
and the command `conda env create -f pymc3GP.yml`
* IPython Version: 7.3.0
* pickle Version: 4.0
* numpy Version: 1.13.3
* pandas Version: 0.24.1
* jupyter Version: 4.4.0

**Comment by ferrine** [comment] 2019-03-08 07:35
I willl look into it

**Comment by chdamianos** [comment] 2019-03-08 16:02
thanks @ferrine !

**Comment by ferrine** [comment] 2019-03-27 22:32
I tried to run the code and reproduced the issue. I compared this to ADVI and found that NonFullRank ADVI is reproducible (the result is as expected). That seems weird since code in FullRankADVI has minor differences and manual check gave me no clue why it could be so, but this leads to non-reproducible results. I also checked the random generators for `pm.tt_rng(42)` between processes and again got identical results. I will compare FullRank case in detail next time.

**Comment by damianosSemmle** [comment] 2019-03-29 08:58
@ferrine I also tried with `advi` instead of `fullrank_advi` and I can confirm that it's reproducible.

**Comment by chdamianos** [comment] 2019-03-29 09:05
@ferrine I also tried with `advi` instead of `fullrank_advi` and I can confirm that it's reproducible.

**Comment by Baillebaille** [comment] 2020-05-17 20:34
I have a similar issue with `pm.fit(method="advi",  random_seed=42)` : 
When the model is fitted twice in the same python script, results are exactly the same,
but when I run twice the same script, results are different.

Here is the reproducer I have : 

```python import numpy as np
import theano
import theano.tensor as tt
import pymc3 as pm
print(np.__version__)
print(theano.__version__)
print(pm.__version__)

off_team = [0, 1, 2, 3, 4]
def_team = [2, 3, 4, 1, 0]
score_obs = [2, 0, 1, 0, 2]

mean_score = np.mean(score_obs)
num_players = len(set(off_team))


with pm.Model() as model:

    off_coefs = pm.Normal('off_coefs', 0, sd=100, shape=num_players)
    def_coefs = pm.Normal('def_coefs', 0, sd=100, shape=num_players)

    off_centered = pm.Deterministic('off_centered', off_coefs - tt.mean(off_coefs))
    def_centered = pm.Deterministic('def_centered', def_coefs - tt.mean(def_coefs))

    std = pm.Uniform('std', 0.01, 20)

    intercept = pm.Normal('intercept', mean_score, sd=10)

    mus = off_centered[off_team] + def_centered[def_team] + intercept
    target = pm.Normal('target', mu=mus, sd=std, observed=score_obs)

with model:
    approx = pm.fit(n=5000,method="advi", random_seed=42)
    trace1 = approx.sample(draws=3)

with model:
    approx = pm.fit(n=5000,method="advi", random_seed=42)
    trace2 = approx.sample(draws=3)

print(np.abs(pm.trace_to_dataframe(trace1)-pm.trace_to_dataframe(trace2)).max())
print(pm.trace_to_dataframe(trace1)["off_coefs__0"])
```
I'm using
* python version 3.8.2 on macos 10.15.4
* pymc3 version 3.8 (installed with pip)
* numpy version 1.18.3 (installed with pip)
* theano version 1.0.4 (installed with pip)

**Comment by fonnesbeck** [comment] 2020-05-17 23:57
You should not expect identical results from the two fits in the script above. The second call to `fit` will simply pick up where the first left off, so the two fits are not starting in the same state. You would have to create a new instance of the model to be run in the second fit for a fair comparison.

**Comment by Baillebaille** [comment] 2020-05-18 07:32
Yet I get identical results from the two fits in this script. It's when I run twice the very same script that results are different from previous run.
And it seems to come from ADVI inference. With sampling, I don't have this problem.
Replacing :
```python
with model:
    approx = pm.fit(n=5000,method="advi", random_seed=42)
    trace1 = approx.sample(draws=3)

with model:
    approx = pm.fit(n=5000,method="advi", random_seed=42)
    trace2 = approx.sample(draws=3)
```
by
```python
with model:
    #approx = pm.fit(n=5000,method="advi", random_seed=42)
    #trace1 = approx.sample(draws=3)
    trace1 =  pm.sample(tune=10, draws=3, cores=1, random_seed=42)

with model:
    #approx = pm.fit(n=5000,method="advi", random_seed=42)
    #trace2 = approx.sample(draws=3)
    trace2 =  pm.sample(tune=10, draws=3, cores=1, random_seed=42)
```
The new script gives the very same results each run.

**Comment by twiecki** [comment] 2020-07-27 10:03
CC @ferrine

**Comment by ferrine** [comment] 2020-07-28 08:13
it is `sample` method that is not reproducible. sampling is done on theano symbolic side. Smth similar is discussed in #4024

**Comment by twiecki** [comment] 2020-07-28 18:43
Closing as a dupe of https://github.com/pymc-devs/pymc3/issues/4024 then.

**Closed as completed by twiecki** 2020-07-28 18:43 UTC
