### ISSUE TITLE
GPU Failure in minimal model

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#1939] opened 2017-03-23 05:38 UTC
The following minimal model dies on GPUs:

```
import pymc3 as pm

kids = np.array([180489, 191817, 190830])
amman_prop = 0.35

with pm.Model() as model:
    n_amman = pm.Binomial('n_amman', kids, amman_prop, shape=3)
    pm.sample(2)


[...]

MethodNotDefined: ('perform', <class 'theano.gpuarray.elemwise.GpuElemwise'>, 'GpuElemwise', 'Did you used Theano flags mode=FAST_COMPILE? You can use optimizer=fast_compile instead.')
Apply node that caused the error: Gpugammaln(GpuElemwise{add,no_inplace}.0)
Toposort index: 11
Inputs types: [GpuArrayType<None>(int64, (False,))]
Inputs shapes: [(3,)]
Inputs strides: [(8,)]
Inputs values: [gpuarray.array([63174, 67135, 66791])]
Outputs clients: [[GpuElemwise{Composite{Switch(Identity((GE(i0, i1) * LE(i0, i2))), (((i3 - i4) - i5) + Switch(i6, i7, (i8 * i0)) + Switch(i9, i10, (i11 * (i12 - i0)))), i13)}}[(0, 4)]<gpuarray>(GpuSubtensor{int64:int64:}.0, GpuArrayConstant{[0]}, GpuArrayConstant{[180489 191817 190830]}, GpuArrayConstant{[ 2004053.0658844   2141508.97245093  2129505.3523473 ]}, Gpugammaln.0, Gpugammaln.0, GpuArrayConstant{[False]}, GpuArrayConstant{[-inf]}, GpuArrayConstant{[-1.04982209]}, GpuArrayConstant{[False]}, GpuArrayConstant{[-inf]}, GpuArrayConstant{[-0.43078294]}, GpuArrayConstant{[180489 191817 190830]}, GpuArrayConstant{[-inf]})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

```

**Comment by kyleabeauchamp** [comment] 2017-03-23 05:46
Works with `optimizer=None` in my theanorc, although I'm not 100% certain that still runs on the GPU device.

**Comment by twiecki** [comment] 2017-03-23 09:03
Seems similar to the previous error that also was about GammaLn. I wonder if this is a theano issue.

**Comment by twiecki** [comment] 2017-03-23 09:05
I.e. it's possible that the function just isn't implemented on the GPU. @nouiz should GammaLn work on the GPU?

**Comment by nouiz** [comment] 2017-03-23 11:56
It should work on the GPU. But that isn't is problem.

What Theano flag do you use? Do you use mode=FAST_COMPILE? This disable c code compilation and the GPU back-end need that. If you want faster compilation, but keep the c code generation to keep the GPU back-end, use the flags optimizer=fast_compile instead.

**Comment by kyleabeauchamp** [comment] 2017-03-23 16:27
I tried default settings of optimizer and `optimizer=fast_compile` with no luck IIRC---the only flags that got it working were `optimizer=None`.

**Comment by nouiz** [comment] 2017-03-23 16:40
Do you have a c++ compiler installed? WHich OS are you on?

**Comment by kyleabeauchamp** [comment] 2017-03-23 16:42
I'm on pymc3 master, theano master, libgpuarray master, and the cuda (libgpuarray) backend for theano, python 3.6 (anaconda), ubuntu 16.04 and a GTX 1060 GPU (cuda 8).  I also tried Theano 0.9RC4 with same result.

I have a working C++ compiler.  Won't know the exact version until I get home tonight.

**Comment by nouiz** [comment] 2017-03-23 17:00
Something is disabling Theano g++ code. Can you print just before compiling
that Theano function that:
print(config.mode)
print(config.optimizer)

do you pass a mode parameter to theano.function?

**Comment by kyleabeauchamp** [comment] 2017-03-24 01:50
```
import pymc3 as pm
from theano import config

kids = np.array([180489, 191817, 190830])
amman_prop = 0.35

print(config.mode)
print(config.optimizer)

with pm.Model() as model:
    n_amman = pm.Binomial('n_amman', kids, amman_prop, shape=3)
    pm.sample(2)

Mode
fast_run
[...]
# Errors as before

```

**Comment by kyleabeauchamp** [comment] 2017-03-24 01:50
```
g++
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
```

**Comment by kyleabeauchamp** [comment] 2017-03-24 04:24
Here is verbose traceback:

```

MethodNotDefined: ('perform', <class 'theano.gpuarray.elemwise.GpuElemwise'>, 'GpuElemwise', 'Did you used Theano flags mode=FAST_COMPILE? You can use optimizer=fast_compile instead.')
Apply node that caused the error: Gpugammaln(GpuElemwise{add,no_inplace}.0)
Toposort index: 13
Inputs types: [GpuArrayType<None>(int64, (False,))]
Inputs shapes: [(3,)]
Inputs strides: [(8,)]
Inputs values: [gpuarray.array([63173, 67138, 66790])]
Inputs type_num: [7]
Outputs clients: [[GpuElemwise{Composite{Switch(Identity((GE(i0, i1) * LE(i0, i2))), (((i3 - i4) - i5) + Switch(i6, i7, (i8 * i0)) + Switch(i9, i10, (i11 * (i12 - i0)))), i13)}}[(0, 4)]<gpuarray>(GpuSubtensor{int64:int64:}.0, GpuArrayConstant{[0]}, GpuArrayConstant{[180489 191817 190830]}, GpuArrayConstant{[ 2004053.0658844   2141508.97245093  2129505.3523473 ]}, Gpugammaln.0, Gpugammaln.0, GpuArrayConstant{[False]}, GpuArrayConstant{[-inf]}, GpuArrayConstant{[-1.04982209]}, GpuArrayConstant{[False]}, GpuArrayConstant{[-inf]}, GpuArrayConstant{[-0.43078294]}, GpuArrayConstant{[180489 191817 190830]}, GpuArrayConstant{[-inf]})]]

Debugprint of the apply node: 
Gpugammaln [id A] <GpuArrayType<None>(float64, (False,))> ''   
 |GpuElemwise{add,no_inplace} [id B] <GpuArrayType<None>(int64, (False,))> ''   
   |GpuArrayConstant{[1]} [id C] <GpuArrayType<None>(int64, (True,))>
   |GpuSubtensor{int64:int64:} [id D] <GpuArrayType<None>(int64, (False,))> ''   
     |GpuFromHost<None> [id E] <GpuArrayType<None>(int64, (False,))> ''   
     | |inarray1 [id F] <TensorType(int64, vector)>
     |Constant{0} [id G] <int64>
     |Constant{3} [id H] <int64>

Storage map footprint:
 - inarray1, Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - inarray, Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - GpuArrayConstant{[180490 191818 190831]}, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - GpuArrayConstant{[180489 191817 190830]}, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - GpuArrayConstant{[ 2004053.0658844   2141508.97245093  2129505.3523473 ]}, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - GpuSubtensor{int64:int64:}.0, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - GpuElemwise{add,no_inplace}.0, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - Constant{0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{3}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - GpuArrayConstant{[1]}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - GpuArrayConstant{[-1.04982209]}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - GpuArrayConstant{[-0.43078294]}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - GpuArrayConstant{[-inf]}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - GpuArrayConstant{[0]}, Shape: (1,), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 - GpuArrayConstant{[False]}, Shape: (1,), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 TotalSize: 214.0 Byte(s) 0.000 GB
 TotalSize inputs: 166.0 Byte(s) 0.000 GB

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
```

**Comment by kyleabeauchamp** [comment] 2017-03-24 05:13
Debug mode traceback:

```
InvalidValueError: InvalidValueError
        type(variable) = TensorType(float32, (True,))
        variable       = TensorConstant{(1,) of -inf}
        type(value)    = <class 'numpy.ndarray'>
        dtype(value)   = float32
        shape(value)   = (1,)
        value          = [-inf]
        min(value)     = -inf
        max(value)     = -inf
        isfinite       = False
        client_node    = None
        hint           = Graph Input 'TensorConstant{(1,) of -inf}' has invalid value [-inf]
        specific_hint  = none
        context        = ...
  TensorConstant{(1,) of -inf} [id A]
```

**Comment by kyleabeauchamp** [comment] 2017-03-24 05:14
The hint suggests perhaps it's due to a value of `-inf`?

**Comment by kyleabeauchamp** [comment] 2017-03-24 05:16
This could be related to #1146

**Comment by kyleabeauchamp** [comment] 2017-03-24 05:40
When running in cuda + debug, I also see a lot of these INF hints when running test_distributions.py

**Comment by kyleabeauchamp** [comment] 2017-03-25 16:46
Does anyone else have any ideas here?  I'm still ramping up on learning the inner workings of pymc3+theano interactions, so I'm at a loss.

**Comment by twiecki** [comment] 2017-03-25 17:15
```python
In [6]: np.array(np.inf).dtype
Out[6]: dtype('float64')
```

Perhaps we need to cast inf when we return it in the bound?

**Comment by twiecki** [comment] 2017-03-25 17:16
https://github.com/pymc-devs/pymc3/blob/4a713dc4519b2da8ad6e9b25240840d82dd02572/pymc3/distributions/dist_math.py#L43

**Comment by kyleabeauchamp** [comment] 2017-03-26 00:32
Nope, that one didn't work.  Still looking.  

```
-    return tt.switch(alltrue(conditions), logp, -np.inf)
+   return tt.switch(alltrue(conditions), logp, floatX(-np.inf))
```

**Comment by kyleabeauchamp** [comment] 2017-03-26 00:58
I guess my question is where the `-inf` is being introduced.  E.g. something has to have a test value that leads to neginf logp.

**Comment by aseyboldt** [comment] 2017-03-26 14:34
I don't have access to a nvidia gpu at the moment, so I can't test this myself. But if I could, I'd try something like this:
- Figure out for which input you can trigger the issue: Try calling `model.logp_array(point)` for different points, starting with `point = model.dict_to_array(model.test_point)`.
- Try to recreate the issue without theano:
```python
p = tt.scalar('p')
p.tag.test_value = np.array(0.35).astype('f')
n = tt.ivector('n')  # maybe try vector, too. In case it is related to the integer dtype
n.tag.test_value = kids
vals = tt.vector('vals')
vals.tag.test_value = np.zeros(3).astype('f')
logp = ... # some of the stuff in Bernoulli.logp
logp = theano.function([n, p, vals], logp)

# Somehow trigger the issue by calling logp with different values
```

**Comment by kyleabeauchamp** [comment] 2017-03-27 03:53
Will try to follow your advice.  Below are some more notes from various explorations.

1.  Poisson, NegativeBin, Binomial fail during the sampling stage (delta logp)
2.  Normal, Uniform, DiscreteUniform, Geomtric work fine

The key factor is probably the gammaLn calculation.  However, it seems to work just fine on its own during manual calculations.  I only see the errors during the sampling.

**Comment by twiecki** [comment] 2017-03-27 09:11
Do they fail for all parameter values, or only some?

**Comment by aseyboldt** [comment] 2017-03-27 12:46
I've got an idea. Try this theano expression:
```
tt.switch(n > 0, pm.gammaln(n), 0.)
```
and evaluate for negative values.
I think `tt.switch` sometimes evaluates both branches, and sometimes it does not.

**Comment by nouiz** [comment] 2017-03-27 13:05
switch always evaluate both branch. Then is select the values it want.

Using debugmode won't help your original problem.

Can you print theano.config.cxx? To know if Theano is able to find a
compiler. If not, it should print a warning.

Also print theano.config.mode (should be "Mode") and theano.config.linker
(should be "cvm")

**Comment by aseyboldt** [comment] 2017-03-27 13:12
Ah, so maybe `gammaln` raises an exception only on the gpu, but returns nan or inf or something on the cpu?

@nouiz I thought I'd seen it compiled down to something like `cond ? expr1 : expr2`, but maybe my memory is playing tricks on me, and it was in fact `cond ? value1 : value2`

*Edit* Well, reading the error message again, I guess this isn't it after all, sorry.

**Comment by kyleabeauchamp** [comment] 2017-03-28 05:35
AFAIK fails on all parameter values.


```
print(theano.config.cxx)
print(theano.config.mode)
print(theano.config.linker)

[...]

/usr/bin/g++
Mode
cvm

```

**Comment by kyleabeauchamp** [comment] 2017-03-29 06:42
One more update:  the model works when `device = gpu` but fails when `device = cuda`!

**Comment by twiecki** [comment] 2017-03-29 07:29
I've never seen `device = cuda`, I imagine that could cause theano to use some out-of-date code. So everything is fine with device = gpu?

**Comment by nouiz** [comment] 2017-03-29 14:25
device=cuda is the new GPU back-end. It should work.

Can you give me one script that I could just execute that reproduce this
problem (and the pymc3 version that you use?) The new back-end should
support this. It will help find if the problem is your environment or
Theano.

Make sure to use Theano 0.9 or more recent.

**Comment by kyleabeauchamp** [comment] 2017-03-30 03:33
Here is the driver script: https://gist.github.com/kyleabeauchamp/d0307c63bdd96e2e0d93ffdab2a56372

pymc3 version 3.1rc3
theano 0.9.0

**Comment by nouiz** [comment] 2017-03-30 12:31
I'm able to reproduce it.

The problem is that the input is in dtype int*, while the c code for
gammaln only support float* inputs.

I can probably changes that to have int8, int16 inputs supported, but I'm
not sure it is a good idea to make it support int64 as inputs, as it will
be downcasted to float*. Can you update your code to have the inputs in
float*

**Comment by kyleabeauchamp** [comment] 2017-03-30 15:22
To be clear: I see the error also if I cast my input to float32, which I just added to the gist.

**Comment by kyleabeauchamp** [comment] 2017-03-30 15:23
E.g. I suspect the pymc code somewhere re-casts the values to integers.

**Comment by kyleabeauchamp** [comment] 2017-04-01 01:35
Thanks @nouiz  I was able to use your suggestion to define a minimal workaround for this error: #1979

Now we just need to figure out the best way to elegantly apply this idea more broadly in other locations.

**Comment by nouiz** [comment] 2017-04-04 12:50
I have this PR that make gammaln work in the new gpu back-end:

https://github.com/Theano/Theano/pull/5806

But you still have the upcast from int64 to float64. Could you use int16
instead? This will upcast to float32 and won't cause the usage of float64.

In the old back-end, the gammaln was on the CPU, that is why there was no
error. Not it should be on the GPU.

**Comment by kyleabeauchamp** [comment] 2017-04-05 03:27
Thanks.  Theano master now fixes this issue.  

The remaining TODO is to deal with the floatX(int64) auto-upcast to float64, which is presumably a performance issue.  I'm going to punt on that one in the interest of getting more tests running first.

**Comment by kyleabeauchamp** [comment] 2017-04-07 06:32
OK I've got another minimal test failure case.  The python script and output is here: https://gist.github.com/kyleabeauchamp/a8b9f6315e1693765e4639e984b6fe1f

In short, a model containing **both** a Binomial and Uniform (unrelated + independent) will fail on the CUDA platform.  The same model runs on the GPU platform.  Leaving out **either** of the variables fixes the issue.  Testing was run with latest Theano and pymc3.  

Pretty strange IMHO...

**Comment by nouiz** [comment] 2017-04-14 00:07
I have a PR on Theano that remove this new errors, but I got another one after. Here is the PR:

https://github.com/Theano/Theano/pull/5850

**Comment by nouiz** [comment] 2017-04-14 00:11
The problem is that the shared variable named: n_amman_shared don't a gpu values as it should, it have a CPU values...

This is in the new back-end.

**Comment by nouiz** [comment] 2017-04-14 01:12
The last fix is in pymc3:

https://github.com/pymc-devs/pymc3/pull/2029

**Comment by kyleabeauchamp** [comment] 2017-04-14 04:06
Here's my latest error log: https://gist.github.com/kyleabeauchamp/a8b9f6315e1693765e4639e984b6fe1f#file-latest_logs-txt

**Closed as completed** 2017-04-14 09:58 UTC
